import type { AcademyUnitDefinition } from '../../../schema'

const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const SPROUT_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'

export const mutationsUnit: AcademyUnitDefinition = {
  id: 'unit-2-3',
  slug: 'la-loterie-des-mutations',
  chapterId: 'chapter-2',
  schemaVersion: 2,
  title: 'La Loterie des Mutations',
  shortTitle: 'Évolution',
  pathLabel: 'Hasard et survie',
  subtitle: 'Adaptation, hasard, et survie au fil des générations.',
  concept: 'Mutations, sélection naturelle, adaptation',
  conceptIds: ['evolution-natural-selection', 'mutation-randomness', 'population-genetics'],
  kind: 'fauna',
  iconKey: 'dna',
  masteryGoal: 'Comprendre l\'évolution comme filtrage du hasard, pas comme progression.',
  order: 3,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: 'Voir l\'évolution sans direction ni but : un filtre, pas une volonté.',
  mascot: 'ondine',
  rewardAmount: 25,

  authoredDiscovery: [
    {
      id: 'c2-mut-disc-1-hook',
      type: 'STORY',
      conceptId: 'evolution-natural-selection',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : la girafe n\'a pas voulu son long cou.',
      screens: [
        {
          text: "Une girafe n'a pas décidé d'avoir un long cou. Personne ne l'a programmée. Comment cette adaptation est-elle apparue ?",
          imagePrompt: 'Girafe au coucher du soleil',
          imageUrl: FIELD_IMAGE,
          kind: 'hook',
          boldTokens: ['décidé'],
        },
      ],
    },
    {
      id: 'c2-mut-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'mutation-randomness',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester la misconception « espèces choisissent leurs adaptations ».',
      question: 'Vrai ou faux ?',
      card: { title: "Les espèces décident des adaptations dont elles ont besoin pour survivre.", subtitle: 'Intuition' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bien vu. Les mutations sont aléatoires. La sélection les filtre, ensuite.',
      incorrectFeedback: 'Misconception. Aucune décision : c\'est un filtre, pas une volonté.',
      explanation: 'Mutation = hasard. Sélection = filtre.',
      misconceptionId: 'mutation-is-conscious',
    },
    {
      id: 'c2-mut-disc-3-reveal',
      type: 'STORY',
      conceptId: 'evolution-natural-selection',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler le mécanisme.',
      screens: [
        {
          text: 'Les mutations apparaissent au hasard à chaque génération. Certaines sont neutres, d\'autres nuisibles, quelques-unes utiles.',
          imagePrompt: 'ADN avec variations',
          imageUrl: SPROUT_IMAGE,
          kind: 'reveal',
          boldTokens: ['hasard'],
        },
        {
          text: "Les individus avec des mutations utiles survivent mieux et se reproduisent plus. Au fil des générations, l'espèce change. C'est l'évolution.",
          imagePrompt: 'Pinsons de Darwin',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['générations'],
        },
      ],
    },
    {
      id: 'c2-mut-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'mutation-randomness',
      difficulty: 'medium',
      cognitiveTags: ['generation', 'misconception'],
      learningObjective: 'Identifier le caractère aléatoire des mutations.',
      question: "Comment apparaissent les mutations génétiques ?",
      options: [
        { text: 'Au hasard, à chaque génération', isCorrect: true, feedback: 'Exact. Hasard pur. La sélection filtre ensuite.' },
        { text: "L'espèce les choisit consciemment", isCorrect: false, feedback: 'Misconception très répandue.', misconceptionId: 'mutation-is-conscious' },
        { text: "L'environnement les fabrique sur commande", isCorrect: false, feedback: 'Pas sur commande. Hasard, puis filtre.' },
      ],
      hint: 'Pense à un loto, pas à un choix.',
    },
    {
      id: 'c2-mut-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir l\'idée que évoluer = progresser.',
      question: 'Vrai ou faux ?',
      card: { title: "Évoluer signifie progresser vers plus complexe ou mieux.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. L\'évolution n\'a pas de direction. Une bactérie est aussi « évoluée » qu\'un humain.',
      incorrectFeedback: 'Faux. Pas de progrès, juste filtrage selon l\'environnement.',
      explanation: 'Gould (1996) : « Full House » démolit ce mythe.',
      misconceptionId: 'evolution-is-progress',
    },
    {
      id: 'c2-mut-disc-6-build',
      type: 'STORY',
      conceptId: 'population-genetics',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: "L'évolution opère sur une population, pas un individu.",
      screens: [
        {
          text: "Un individu n'évolue pas. C'est la population qui change à travers les générations. Une girafe seule ne peut pas allonger son cou.",
          imagePrompt: 'Population de girafes sur plusieurs générations',
          imageUrl: FIELD_IMAGE,
          kind: 'build-up',
          boldTokens: ['population'],
        },
      ],
    },
    {
      id: 'c2-mut-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Reconstituer le mécanisme darwinien.',
      instruction: 'Ordonne les étapes de la sélection naturelle :',
      axis: 'horizontal',
      axisRationale: 'Chronologie des étapes.',
      slotCount: 3,
      items: [
        { id: 'cm-1', text: '🎲 Mutation au hasard' },
        { id: 'cm-2', text: '🏆 Survie du mieux adapté' },
        { id: 'cm-3', text: '🧬 Transmission aux descendants' },
      ],
      correctFeedback: 'Parfait. Mécanisme darwinien acquis.',
      incorrectFeedback: 'Hasard d\'abord, sélection ensuite, transmission à la fin.',
    },
    {
      id: 'c2-mut-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'evolution-natural-selection',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint Darwin.',
      question: 'Vrai ou faux ?',
      card: { title: 'Charles Darwin a formulé la théorie de la sélection naturelle.', subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Voyage aux Galápagos, 1859.',
      incorrectFeedback: 'Si. « De l\'origine des espèces ».',
      explanation: 'Théorie ensuite confirmée massivement par la génétique.',
    },
    {
      id: 'c2-mut-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Sprint : adaptation relative.',
      question: 'Vrai ou faux ?',
      card: { title: "Une espèce parfaitement adaptée à son milieu est protégée pour toujours.", subtitle: 'Sprint 2' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Si l\'environnement change, elle disparaît.',
      incorrectFeedback: 'Faux. L\'adaptation est relative.',
      explanation: 'Hyper-spécialistes = très fragiles face aux changements.',
      misconceptionId: 'species-perfectly-adapted',
    },
    {
      id: 'c2-mut-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'mutation-randomness',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: 'Différencier individu et population.',
      question: 'Une girafe seule peut-elle allonger son cou au cours de sa vie ?',
      options: [
        { text: 'Non, l\'évolution opère sur des générations, pas un individu', isCorrect: true, feedback: 'Exact. Population, pas individu.' },
        { text: 'Oui, en s\'étirant tous les jours', isCorrect: false, feedback: 'Misconception lamarckienne.', misconceptionId: 'individual-evolves' },
        { text: 'Oui, par décision génétique', isCorrect: false, feedback: 'Aucune décision possible.', misconceptionId: 'mutation-is-conscious' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c2-mut-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'evolution-natural-selection',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Reconstituer une évolution complète sur générations.',
      instruction: 'Ordonne l\'évolution de la girafe :',
      axis: 'horizontal',
      axisRationale: 'Chronologie sur générations.',
      slotCount: 4,
      items: [
        { id: 'cmb-1', text: '🎲 Mutation cou un peu plus long' },
        { id: 'cmb-2', text: '🌳 Atteint feuilles hautes' },
        { id: 'cmb-3', text: '🏆 Survit mieux' },
        { id: 'cmb-4', text: '🧬 Transmet aux petits' },
        { id: 'cmb-distract', text: '💪 Étire son cou volontairement', isDistractor: true },
      ],
      correctFeedback: 'Excellent. L\'étirement volontaire n\'a aucun rôle.',
      incorrectFeedback: 'Indice : un seul item est faux (lamarckien).',
    },
    {
      id: 'c2-mut-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser l\'évolution.',
      question: 'Comment décrire le mieux l\'évolution ?',
      options: [
        { text: 'Filtrage par l\'environnement de mutations aléatoires', isCorrect: true, feedback: 'Exact. Hasard + filtre.' },
        { text: 'Progression vers le mieux', isCorrect: false, feedback: 'Misconception classique.', misconceptionId: 'evolution-is-progress' },
        { text: 'Décision consciente des espèces', isCorrect: false, feedback: 'Aucune décision.', misconceptionId: 'mutation-is-conscious' },
      ],
    },
  ],

  pool: [
    {
      id: 'c2-mut-pool-sw-galapagos',
      type: 'SWIPE',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Pinsons de Darwin.',
      question: 'Vrai ou faux ?',
      card: { title: 'Aux Galápagos, des pinsons ont développé des becs différents selon les îles.', subtitle: 'Évolution' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Adaptation locale, observation classique de Darwin.',
      incorrectFeedback: 'Si. Cas d\'école.',
      explanation: 'Isolement + sélection locale = spéciation.',
    },
    {
      id: 'c2-mut-pool-sw-bacteria-resistance',
      type: 'SWIPE',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Antibiorésistance.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les bactéries résistantes aux antibiotiques sont un cas réel d\'évolution.', subtitle: 'Évolution' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Évolution observée en temps réel.',
      incorrectFeedback: 'Si. C\'est une preuve directe.',
      explanation: 'Pression de sélection humaine accélère l\'évolution.',
    },
    {
      id: 'c2-mut-pool-sw-mutation-direction',
      type: 'SWIPE',
      conceptId: 'mutation-randomness',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Mutations sans direction.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les mutations apparaissent dans la direction des besoins de l\'espèce.', subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Hasard pur. La sélection filtre seulement après.',
      incorrectFeedback: 'Faux. Aucune direction préalable.',
      explanation: 'Mutation = aléatoire. Sélection = directionnelle.',
      misconceptionId: 'mutation-is-conscious',
    },
    {
      id: 'c2-mut-pool-sw-progress',
      type: 'SWIPE',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Évolution sans progrès.',
      question: 'Vrai ou faux ?',
      card: { title: "Un humain est plus 'évolué' qu'une bactérie.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Tous deux sont aboutis pour leur environnement.',
      incorrectFeedback: 'Faux. Évolution = adaptation, pas progrès.',
      explanation: 'Bactéries existent depuis 3,5 milliards d\'années.',
      misconceptionId: 'evolution-is-progress',
    },
    {
      id: 'c2-mut-pool-q-darwin',
      type: 'QUIZ',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Identifier Darwin.',
      question: 'Quel scientifique a formulé la sélection naturelle ?',
      options: [
        { text: 'Charles Darwin', isCorrect: true, feedback: 'Exact. 1859.' },
        { text: 'Albert Einstein', isCorrect: false, feedback: 'Physicien, pas biologiste.' },
        { text: 'Marie Curie', isCorrect: false, feedback: 'Physicienne, radioactivité.' },
      ],
    },
    {
      id: 'c2-mut-pool-q-meta-evol',
      type: 'QUIZ',
      conceptId: 'evolution-natural-selection',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Choisir la définition juste.',
      question: 'Comment décrire l\'évolution ?',
      options: [
        { text: 'Changement des fréquences génétiques d\'une population au fil des générations', isCorrect: true, feedback: 'Exact. Définition scientifique.' },
        { text: 'Progression d\'une espèce vers la perfection', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'evolution-is-progress' },
        { text: 'Transformation d\'un individu', isCorrect: false, feedback: 'Misconception lamarckienne.', misconceptionId: 'individual-evolves' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c2-mut-pool-q-pop-not-ind',
      type: 'QUIZ',
      conceptId: 'population-genetics',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Population vs individu.',
      question: 'Qui évolue dans la nature ?',
      options: [
        { text: 'Les populations, à travers les générations', isCorrect: true, feedback: 'Exact.' },
        { text: 'Les individus, au cours de leur vie', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'individual-evolves' },
        { text: 'Les écosystèmes uniquement', isCorrect: false, feedback: 'Aussi mais pas la définition principale.' },
      ],
    },
    {
      id: 'c2-mut-pool-d-evolution',
      type: 'DRAG_DROP',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Reconstituer la sélection naturelle.',
      instruction: 'Ordonne le mécanisme :',
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 3,
      items: [
        { id: 'cmev-1', text: '🎲 Variations aléatoires' },
        { id: 'cmev-2', text: '🏆 Sélection par environnement' },
        { id: 'cmev-3', text: '🧬 Transmission' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Hasard → filtre → transmission.',
    },
    {
      id: 'c2-mut-pool-d-history',
      type: 'DRAG_DROP',
      conceptId: 'evolution-natural-selection',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Évolution dans le temps.',
      instruction: 'Du plus ancien au plus récent :',
      axis: 'horizontal',
      axisRationale: 'Chronologie évolutive.',
      slotCount: 4,
      items: [
        { id: 'cmh-1', text: '🦠 Bactéries' },
        { id: 'cmh-2', text: '🐟 Poissons' },
        { id: 'cmh-3', text: '🦎 Reptiles' },
        { id: 'cmh-4', text: '🐺 Mammifères' },
      ],
      correctFeedback: 'Parfait. Arbre du vivant respecté.',
      incorrectFeedback: 'Bactéries d\'abord, mammifères en dernier.',
    },
    {
      id: 'c2-mut-pool-sw-extinction',
      type: 'SWIPE',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Extinction = règle.',
      question: 'Vrai ou faux ?',
      card: { title: '99 % des espèces qui ont existé sont aujourd\'hui éteintes.', subtitle: 'Évolution' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. L\'extinction est la norme.',
      incorrectFeedback: 'Si. Notre époque ne fait pas exception.',
      explanation: 'Sélection naturelle implique disparitions massives.',
    },
    {
      id: 'c2-mut-pool-sw-resistance-evolves',
      type: 'SWIPE',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Résistance évolue.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les insectes peuvent évoluer pour résister à un pesticide en quelques générations.', subtitle: 'Évolution rapide' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Pression de sélection forte = évolution rapide.',
      incorrectFeedback: 'Si. C\'est pourquoi les pesticides perdent leur efficacité.',
      explanation: 'Évolution observée en temps réel.',
    },
    {
      id: 'c2-mut-pool-sw-isolation',
      type: 'SWIPE',
      conceptId: 'evolution-natural-selection',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Isolement et spéciation.',
      question: 'Vrai ou faux ?',
      card: { title: "L'isolement géographique peut faire naître de nouvelles espèces.", subtitle: 'Spéciation' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Madagascar, Galápagos = laboratoires d\'évolution.',
      incorrectFeedback: 'Si. Spéciation allopatrique.',
      explanation: 'Isolement + sélection locale = nouvelle espèce.',
      interleavesConceptIds: ['endemism-isolation'],
    },
  ],

  authoredLegendary: [
    {
      id: 'c2-mut-leg-1-hook',
      type: 'STORY',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le boss évolution.',
      screens: [
        {
          text: '14 questions pour valider que tu vois l\'évolution sans direction ni but.',
          imagePrompt: 'Arbre du vivant',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['sans'],
        },
      ],
    },
    {
      id: 'c2-mut-leg-2-q',
      type: 'QUIZ',
      conceptId: 'mutation-randomness',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Mutations aléatoires.',
      question: 'Comment apparaissent les mutations ?',
      options: [
        { text: 'Au hasard', isCorrect: true, feedback: 'Exact.' },
        { text: 'Sur commande de l\'espèce', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'mutation-is-conscious' },
        { text: 'Selon les besoins immédiats', isCorrect: false, feedback: 'Pas selon les besoins.', misconceptionId: 'mutation-is-conscious' },
      ],
    },
    {
      id: 'c2-mut-leg-3-q',
      type: 'QUIZ',
      conceptId: 'evolution-natural-selection',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Évolution sans direction.',
      question: 'L\'évolution mène-t-elle à un état parfait ?',
      options: [
        { text: 'Non, elle filtre selon l\'environnement (qui change)', isCorrect: true, feedback: 'Exact. Pas de fin.' },
        { text: 'Oui, vers la perfection', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'evolution-is-progress' },
        { text: 'Oui, vers plus d\'intelligence', isCorrect: false, feedback: 'Pas de direction prédéfinie.', misconceptionId: 'evolution-is-progress' },
      ],
    },
    {
      id: 'c2-mut-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'evolution-natural-selection',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Reconstituer la sélection naturelle.',
      instruction: 'Ordonne le mécanisme darwinien :',
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 4,
      items: [
        { id: 'cmlg-1', text: '🎲 Variations aléatoires' },
        { id: 'cmlg-2', text: '🌍 Pression environnementale' },
        { id: 'cmlg-3', text: '🏆 Survie différentielle' },
        { id: 'cmlg-4', text: '🧬 Transmission' },
        { id: 'cmlg-distract', text: '💭 Décision consciente', isDistractor: true },
      ],
      correctFeedback: 'Excellent. Aucune décision dans le mécanisme.',
      incorrectFeedback: 'Indice : un item est faux.',
    },
    {
      id: 'c2-mut-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'population-genetics',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Population vs individu.',
      question: 'Vrai ou faux ?',
      card: { title: "Un individu peut évoluer au cours de sa vie.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Population, pas individu.',
      incorrectFeedback: 'Non. L\'évolution opère sur générations.',
      explanation: 'Antimisconception lamarckien.',
      misconceptionId: 'individual-evolves',
    },
    {
      id: 'c2-mut-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Adaptation relative.',
      question: 'Vrai ou faux ?',
      card: { title: "Une espèce hyper-spécialisée est plus fragile face aux changements.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Spécialiste = fragile.',
      incorrectFeedback: 'Si. Généralistes survivent mieux.',
      explanation: 'Spécialiste perd vite si son milieu disparaît.',
      misconceptionId: 'species-perfectly-adapted',
    },
    {
      id: 'c2-mut-leg-7-q',
      type: 'QUIZ',
      conceptId: 'evolution-natural-selection',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Choisir la définition juste.',
      question: 'Comment résumer l\'évolution ?',
      options: [
        { text: 'Hasard (mutations) + filtre (sélection) + générations', isCorrect: true, feedback: 'Exact. Triade.' },
        { text: 'Décision consciente + adaptation', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'mutation-is-conscious' },
        { text: 'Progression vers la perfection', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'evolution-is-progress' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c2-mut-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'evolution-natural-selection',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Évolution + entrelacement.',
      instruction: "Ordonne ces éléments dans une histoire évolutive :",
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 4,
      items: [
        { id: 'cmli-1', text: '🦠 Bactéries (3,5 Ga)' },
        { id: 'cmli-2', text: '🐟 Poissons (500 Ma)' },
        { id: 'cmli-3', text: '🐺 Mammifères (200 Ma)' },
        { id: 'cmli-4', text: '👤 Humains (300 ka)' },
      ],
      correctFeedback: 'Excellent. Arbre du vivant complet.',
      incorrectFeedback: 'Bactéries d\'abord, humains en dernier.',
      interleavesConceptIds: ['ecosystem-flow'],
    },
    {
      id: 'c2-mut-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint Darwin.',
      question: 'Vrai ou faux ?',
      card: { title: 'Charles Darwin a expliqué l\'évolution par sélection naturelle.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. 1859.',
      incorrectFeedback: 'Si. Théorie fondatrice.',
      explanation: '« De l\'origine des espèces ».',
    },
    {
      id: 'c2-mut-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'mutation-randomness',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Sprint mutations.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les espèces choisissent leurs adaptations.', subtitle: 'Sprint' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Hasard, pas choix.',
      incorrectFeedback: 'Non. Aucune décision.',
      explanation: 'Mutations aléatoires.',
      misconceptionId: 'mutation-is-conscious',
    },
    {
      id: 'c2-mut-leg-11-q',
      type: 'QUIZ',
      conceptId: 'evolution-natural-selection',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthétiser : adaptation et environnement.',
      question: 'Pourquoi une « adaptation parfaite » peut-elle se retourner contre une espèce ?',
      options: [
        { text: 'Si l\'environnement change, elle ne peut plus suivre', isCorrect: true, feedback: 'Exact. Spécialisation = fragilité.' },
        { text: 'Parce qu\'elle devient trop intelligente', isCorrect: false, feedback: 'Aucun rapport.' },
        { text: 'Parce qu\'elle perd ses prédateurs', isCorrect: false, feedback: 'Pas le sujet.' },
      ],
    },
    {
      id: 'c2-mut-leg-12-reveal',
      type: 'STORY',
      conceptId: 'evolution-natural-selection',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective.',
      screens: [
        {
          text: 'L\'évolution n\'a pas de but. Elle filtre du hasard. C\'est précisément ce qui rend la diversité du vivant si fascinante.',
          imagePrompt: 'Multitude d\'espèces différentes',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['filtre'],
        },
      ],
    },
    {
      id: 'c2-mut-leg-13-q',
      type: 'QUIZ',
      conceptId: 'evolution-natural-selection',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Choisir un geste cohérent.',
      question: 'Quelle action soutient la diversité évolutive ?',
      options: [
        { text: 'Préserver des habitats variés et la biodiversité', isCorrect: true, feedback: 'Exact.' },
        { text: 'Standardiser les espèces utiles', isCorrect: false, feedback: 'Inverse. Monoculture = fragilité.' },
        { text: 'Stériliser les milieux', isCorrect: false, feedback: 'Tue la diversité.', misconceptionId: 'dead-soil-is-clean' },
      ],
    },
    {
      id: 'c2-mut-leg-14-closure',
      type: 'STORY',
      conceptId: 'evolution-natural-selection',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer la transition vers Chap 3.',
      screens: [
        {
          text: 'Tu connais la grammaire des espèces : prédation, alliances, évolution. Au Chap 3 : les grands cycles qui font tourner la planète.',
          imagePrompt: 'Cycle géologique illustré',
          imageUrl: SPROUT_IMAGE,
          kind: 'closure',
          boldTokens: ['cycles'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'c2-mut-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir l\'évolution sans direction.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'c2-mut-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser l\'évolution.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.5, interleaveFromPreviousUnits: 1 },
    },
    {
      id: 'c2-mut-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler l\'évolution dans des cas pièges.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.6, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'c2-mut-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise de l\'évolution.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 25, label: '25 Graines' },
    },
  ],
}
