import type { AcademyUnitDefinition } from '../../../schema'

const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const SPROUT_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'

export const predatorsUnit: AcademyUnitDefinition = {
  id: 'unit-2-1',
  slug: 'le-festin-des-predateurs',
  chapterId: 'chapter-2',
  schemaVersion: 2,
  title: 'Le Festin des Prédateurs',
  shortTitle: 'Prédateurs',
  pathLabel: 'Chaîne du vivant',
  subtitle: 'Proies, prédateurs, et l\'équilibre invisible.',
  concept: 'Proies, prédateurs, équilibre',
  conceptIds: ['food-chain-link', 'predator-regulation', 'trophic-cascade'],
  kind: 'fauna',
  iconKey: 'wolf',
  masteryGoal: 'Comprendre que les prédateurs régulent et stabilisent les écosystèmes.',
  order: 1,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: 'Voir le prédateur comme régulateur, pas comme destructeur.',
  mascot: 'abeille-transparente',
  rewardAmount: 20,

  authoredDiscovery: [
    {
      id: 'c2-pred-disc-1-hook',
      type: 'STORY',
      conceptId: 'predator-regulation',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : un loup peut sauver une rivière.',
      screens: [
        {
          text: 'En 1995, on a réintroduit 14 loups à Yellowstone. 20 ans plus tard, des rivières avaient changé de cours. Comment ?',
          imagePrompt: 'Loup observant une vallée',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['rivières'],
        },
      ],
    },
    {
      id: 'c2-pred-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'predator-regulation',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester la misconception « prédateurs = méchants ».',
      question: 'Vrai ou faux ?',
      card: { title: "Les grands prédateurs déstabilisent les écosystèmes en chassant.", subtitle: 'Intuition' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bien vu. Inverse : ils stabilisent en régulant les proies.',
      incorrectFeedback: 'Misconception classique. Sans eux, les herbivores explosent et la végétation s\'effondre.',
      explanation: 'Yellowstone : retour du loup → restauration des rivières.',
      misconceptionId: 'predators-are-villains',
    },
    {
      id: 'c2-pred-disc-3-reveal',
      type: 'STORY',
      conceptId: 'trophic-cascade',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler la cascade trophique.',
      screens: [
        {
          text: 'Sans loup, les cerfs broutent toute la végétation des berges. Les berges s\'érodent, les rivières changent.',
          imagePrompt: 'Berge érodée par cerfs',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['berges'],
        },
        {
          text: 'Le loup régule les cerfs. Les berges se végétalisent. La rivière retrouve son cours. C\'est la cascade trophique.',
          imagePrompt: 'Rivière avec berges restaurées',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['cascade'],
        },
      ],
    },
    {
      id: 'c2-pred-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'predator-regulation',
      difficulty: 'medium',
      cognitiveTags: ['generation', 'misconception'],
      learningObjective: 'Identifier le rôle écologique des prédateurs.',
      question: 'À quoi sert un grand prédateur dans un écosystème ?',
      options: [
        { text: 'À réguler les populations de proies et stabiliser tout', isCorrect: true, feedback: 'Exact. Régulateur, pas destructeur.' },
        { text: 'À détruire l\'écosystème', isCorrect: false, feedback: 'Inverse. Sa disparition cause un déséquilibre.', misconceptionId: 'predators-are-villains' },
        { text: 'À rien de particulier', isCorrect: false, feedback: 'Faux. Espèce-clé.', misconceptionId: 'predators-are-villains' },
      ],
      hint: 'Pense à ce qui se passe sans prédateurs.',
    },
    {
      id: 'c2-pred-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir l\'idée que la base = animaux.',
      question: 'Vrai ou faux ?',
      card: { title: 'À la base de toute chaîne alimentaire terrestre, on trouve un animal.', subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. La base est toujours un producteur (plante, algue).',
      incorrectFeedback: 'Faux. Pas de plantes = pas de chaîne.',
      explanation: 'Producteurs = base obligatoire (vu au chap 1).',
    },
    {
      id: 'c2-pred-disc-6-build',
      type: 'STORY',
      conceptId: 'food-chain-link',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Introduire les niveaux trophiques.',
      screens: [
        {
          text: 'Plantes (1) → herbivores (2) → carnivores (3) → super-prédateurs (4). Chaque étage est un niveau trophique.',
          imagePrompt: 'Pyramide trophique illustrée',
          imageUrl: SPROUT_IMAGE,
          kind: 'build-up',
          boldTokens: ['trophique'],
        },
      ],
    },
    {
      id: 'c2-pred-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Hiérarchiser une chaîne trophique.',
      instruction: 'Empile la pyramide trophique :',
      axis: 'vertical',
      axisRationale: 'Pyramide trophique = vertical. Producteurs en bas, prédateurs au sommet.',
      slotCount: 4,
      items: [
        { id: 'cp-1', text: '🌿 Plante' },
        { id: 'cp-2', text: '🐛 Chenille' },
        { id: 'cp-3', text: '🐦 Oiseau' },
        { id: 'cp-4', text: '🦅 Aigle' },
      ],
      correctFeedback: 'Parfait. Pyramide classique acquise.',
      incorrectFeedback: 'Indice : producteur en bas, super-prédateur au sommet.',
    },
    {
      id: 'c2-pred-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'food-chain-link',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : moins de prédateurs en haut.',
      question: 'Vrai ou faux ?',
      card: { title: 'Il y a beaucoup moins de loups que de cerfs dans une forêt.', subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Pyramide énergétique : ~10 % par étage.',
      incorrectFeedback: 'Si. Plus on monte, moins il y en a.',
      explanation: 'Règle des 10 %.',
    },
    {
      id: 'c2-pred-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'trophic-cascade',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Sprint : suppression prédateur = cascade.',
      question: 'Vrai ou faux ?',
      card: { title: 'Supprimer un super-prédateur peut tout fragiliser en chaîne.', subtitle: 'Sprint 2' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Cascade trophique documentée.',
      incorrectFeedback: 'Si. Effet domino prouvé partout.',
      explanation: 'Yellowstone, étoile Pisaster, requins.',
      misconceptionId: 'predators-are-villains',
    },
    {
      id: 'c2-pred-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'predator-regulation',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: "Identifier l'effet de la chasse aux loups.",
      question: 'Si on extermine tous les loups d\'une forêt, que se passe-t-il à long terme ?',
      options: [
        { text: 'Les cerfs explosent, broutent tout, la forêt se dégrade', isCorrect: true, feedback: 'Exact. Cas réel observé en Europe et Amérique du Nord.' },
        { text: "Rien de spécial", isCorrect: false, feedback: 'Faux. Effet documenté.', misconceptionId: 'predators-are-villains' },
        { text: "L'écosystème devient plus stable", isCorrect: false, feedback: 'Inverse. Sans régulateur, déséquilibre.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c2-pred-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'trophic-cascade',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Reconstituer la cascade Yellowstone.',
      instruction: 'Ordonne la cascade après réintroduction du loup :',
      axis: 'horizontal',
      axisRationale: 'Chronologie causale.',
      slotCount: 4,
      items: [
        { id: 'cpc-1', text: '🐺 Loup réintroduit' },
        { id: 'cpc-2', text: '🦌 Moins de cerfs' },
        { id: 'cpc-3', text: '🌿 Berges revégétalisées' },
        { id: 'cpc-4', text: '🏞️ Rivières restaurées' },
        { id: 'cpc-distract', text: '🪨 Roches vibrantes', isDistractor: true },
      ],
      correctFeedback: 'Excellent. Les roches n\'ont rien à voir.',
      incorrectFeedback: 'Indice : un seul item est absurde.',
    },
    {
      id: 'c2-pred-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'predator-regulation',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser le rôle des prédateurs.',
      question: 'Comment qualifier le rôle d\'un grand prédateur ?',
      options: [
        { text: 'Espèce-clé qui stabilise tout l\'écosystème', isCorrect: true, feedback: 'Exact. Pivot fonctionnel.' },
        { text: 'Nuisible à éliminer', isCorrect: false, feedback: 'Misconception culturelle. Inversion des effets.', misconceptionId: 'predators-are-villains' },
        { text: 'Espèce sans importance', isCorrect: false, feedback: 'Faux. Sa disparition crée une cascade.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c2-pred-pool-sw-prey-explosion',
      type: 'SWIPE',
      conceptId: 'predator-regulation',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Effet de la disparition des prédateurs.',
      question: 'Vrai ou faux ?',
      card: { title: 'Sans prédateurs, les populations de proies s\'autorégulent toutes seules.', subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Sans régulation externe, elles explosent puis s\'effondrent.',
      incorrectFeedback: 'Non. L\'autorégulation seule suffit rarement à long terme.',
      explanation: 'Cycles « boom-bust » documentés.',
      misconceptionId: 'predators-are-villains',
    },
    {
      id: 'c2-pred-pool-sw-pisaster',
      type: 'SWIPE',
      conceptId: 'trophic-cascade',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: "L'étoile de mer Pisaster comme espèce-clé.",
      question: 'Vrai ou faux ?',
      card: { title: 'Une étoile de mer peut être une espèce-clé d\'un écosystème.', subtitle: 'Pisaster' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Sans Pisaster, les moules dominent et la diversité chute.',
      incorrectFeedback: 'Si. Étude classique de Robert Paine (1966).',
      explanation: 'Concept d\'espèce-clé inventé à partir de cette étude.',
    },
    {
      id: 'c2-pred-pool-sw-shark',
      type: 'SWIPE',
      conceptId: 'trophic-cascade',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Requins comme régulateurs marins.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les requins jouent un rôle stabilisateur dans les océans.', subtitle: 'Marin' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Sans eux, prolifération de méduses, désordre dans la chaîne.',
      incorrectFeedback: 'Si. Régulateurs marins essentiels.',
      explanation: 'Disparition des requins → cascades documentées.',
    },
    {
      id: 'c2-pred-pool-sw-decomp-trophic',
      type: 'SWIPE',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Décomposeurs au sein de la chaîne.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les décomposeurs s\'occupent uniquement des super-prédateurs morts.', subtitle: 'Décomposeurs' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Ils recyclent à TOUS les niveaux trophiques.',
      incorrectFeedback: 'Faux. Plantes mortes, herbivores morts, prédateurs morts : tout passe par eux.',
      explanation: 'Décomposeurs = transverses.',
      interleavesConceptIds: ['decomposers-role'],
    },
    {
      id: 'c2-pred-pool-q-energy-loss',
      type: 'QUIZ',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Pyramide énergétique.',
      question: 'Pourquoi y a-t-il rarement plus de 4-5 niveaux trophiques ?',
      options: [
        { text: 'À chaque étage, ~90 % de l\'énergie est perdue en chaleur', isCorrect: true, feedback: 'Exact. Au 5e étage, il ne reste presque rien.' },
        { text: 'Parce que les animaux sont fatigués', isCorrect: false, feedback: 'Pas une explication écologique.' },
        { text: 'Aucune raison', isCorrect: false, feedback: 'Il y en a une, et c\'est physique.' },
      ],
      interleavesConceptIds: ['ecosystem-flow'],
    },
    {
      id: 'c2-pred-pool-q-keystone-def',
      type: 'QUIZ',
      conceptId: 'predator-regulation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Définir une espèce-clé.',
      question: 'Qu\'est-ce qu\'une espèce-clé (keystone) ?',
      options: [
        { text: 'Espèce dont la disparition cause un effondrement disproportionné', isCorrect: true, feedback: 'Exact. Effet « pivot ».' },
        { text: 'Espèce la plus nombreuse', isCorrect: false, feedback: 'Pas forcément. Une keystone peut être rare.' },
        { text: 'Espèce la plus visible', isCorrect: false, feedback: 'Visibilité ≠ importance écologique.' },
      ],
    },
    {
      id: 'c2-pred-pool-q-trophic-meta',
      type: 'QUIZ',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Identifier la base de la chaîne.',
      question: 'À quoi correspond le 1er niveau trophique ?',
      options: [
        { text: 'Producteurs (plantes, algues)', isCorrect: true, feedback: 'Exact. Ils captent l\'énergie solaire.' },
        { text: 'Consommateurs primaires', isCorrect: false, feedback: 'Ils sont au niveau 2.' },
        { text: 'Super-prédateurs', isCorrect: false, feedback: 'Ils sont au sommet, niveau 4-5.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c2-pred-pool-d-chain',
      type: 'DRAG_DROP',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Reconstituer une chaîne courte.',
      instruction: 'Ordonne la chaîne :',
      axis: 'horizontal',
      axisRationale: 'Sens du flux d\'énergie.',
      slotCount: 3,
      items: [
        { id: 'cpch-1', text: '🌾 Blé' },
        { id: 'cpch-2', text: '🐀 Souris' },
        { id: 'cpch-3', text: '🦉 Hibou' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Sens unique : producteur → herbivore → carnivore.',
    },
    {
      id: 'c2-pred-pool-d-pyramid-marine',
      type: 'DRAG_DROP',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Pyramide marine.',
      instruction: 'Empile la pyramide marine :',
      axis: 'vertical',
      axisRationale: 'Pyramide trophique.',
      slotCount: 4,
      items: [
        { id: 'cpm-1', text: '🌿 Phytoplancton' },
        { id: 'cpm-2', text: '🦐 Krill' },
        { id: 'cpm-3', text: '🐟 Poissons' },
        { id: 'cpm-4', text: '🦈 Requin' },
      ],
      correctFeedback: 'Excellent. Pyramide marine classique.',
      incorrectFeedback: 'Phytoplancton à la base, requin au sommet.',
    },
    {
      id: 'c2-pred-pool-sw-omni',
      type: 'SWIPE',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "Notion d'omnivore.",
      question: 'Vrai ou faux ?',
      card: { title: "Un humain peut occuper plusieurs niveaux trophiques en même temps.", subtitle: 'Omnivore' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Salade = niveau 2, viande = niveau 3+.',
      incorrectFeedback: 'Si. Les omnivores varient leur niveau selon le repas.',
      explanation: 'Omnivore = flexible dans la chaîne.',
    },
    {
      id: 'c2-pred-pool-sw-deer-no-wolf',
      type: 'SWIPE',
      conceptId: 'predator-regulation',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Sans prédateurs, herbivores explosent.',
      question: 'Vrai ou faux ?',
      card: { title: 'Une forêt sans prédateurs est plus saine pour les herbivores.', subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Surpopulation = famine + maladies pour les herbivores eux-mêmes.',
      incorrectFeedback: 'Faux. Sans régulation, ils s\'autodétruisent par surpopulation.',
      explanation: 'Population trop dense = maladies + ressources épuisées.',
      misconceptionId: 'predators-are-villains',
    },
    {
      id: 'c2-pred-pool-q-cascade-meta',
      type: 'QUIZ',
      conceptId: 'trophic-cascade',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Définir la cascade trophique.',
      question: 'Qu\'est-ce qu\'une cascade trophique ?',
      options: [
        { text: 'Effet en chaîne descendant suite à une modification au sommet', isCorrect: true, feedback: 'Exact. Du haut vers le bas.' },
        { text: 'Un cours d\'eau dans une forêt', isCorrect: false, feedback: 'Pas le sens écologique.' },
        { text: 'L\'arrivée du Soleil au matin', isCorrect: false, feedback: 'Aucun rapport.' },
      ],
      confidenceCheck: true,
    },
  ],

  authoredLegendary: [
    {
      id: 'c2-pred-leg-1-hook',
      type: 'STORY',
      conceptId: 'predator-regulation',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le boss prédateurs.',
      screens: [
        {
          text: '14 questions pour valider que tu vois le prédateur comme régulateur, pas comme méchant.',
          imagePrompt: 'Loup dans la neige',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['régulateur'],
        },
      ],
    },
    {
      id: 'c2-pred-leg-2-q',
      type: 'QUIZ',
      conceptId: 'predator-regulation',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Rôle des prédateurs.',
      question: 'Quel est le rôle écologique principal d\'un super-prédateur ?',
      options: [
        { text: 'Réguler et stabiliser', isCorrect: true, feedback: 'Exact. Espèce-clé.' },
        { text: 'Déstabiliser', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'predators-are-villains' },
        { text: 'Décorer la forêt', isCorrect: false, feedback: 'Esthétique mais pas la fonction.' },
      ],
    },
    {
      id: 'c2-pred-leg-3-q',
      type: 'QUIZ',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Identifier la base.',
      question: "Qui se trouve à la base d'une chaîne alimentaire terrestre ?",
      options: [
        { text: 'Les producteurs (plantes, algues)', isCorrect: true, feedback: 'Exact. Toujours.' },
        { text: 'Les super-prédateurs', isCorrect: false, feedback: 'Au sommet, pas à la base.' },
        { text: 'Les décomposeurs', isCorrect: false, feedback: 'Transverses, pas la base.' },
      ],
    },
    {
      id: 'c2-pred-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Pyramide complète.',
      instruction: 'Empile la pyramide complète :',
      axis: 'vertical',
      axisRationale: 'Pyramide trophique.',
      slotCount: 5,
      items: [
        { id: 'cpl-1', text: '🌿 Producteurs' },
        { id: 'cpl-2', text: '🐛 Herbivores' },
        { id: 'cpl-3', text: '🐦 Carnivores' },
        { id: 'cpl-4', text: '🦅 Super-prédateurs' },
        { id: 'cpl-5', text: '🍄 Décomposeurs' },
        { id: 'cpl-distract', text: '☀️ Soleil', isDistractor: true },
      ],
      correctFeedback: 'Excellent. Le Soleil alimente, hors pyramide.',
      incorrectFeedback: 'Indice : un item est externe.',
    },
    {
      id: 'c2-pred-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'trophic-cascade',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Cascade trophique.',
      question: 'Vrai ou faux ?',
      card: { title: 'Supprimer un super-prédateur cause un effondrement en cascade.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Yellowstone l\'a prouvé.',
      incorrectFeedback: 'Si. Effet documenté.',
      explanation: 'Cascade trophique = signature d\'écosystème vivant.',
      misconceptionId: 'predators-are-villains',
    },
    {
      id: 'c2-pred-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Pyramide trophique.',
      question: 'Vrai ou faux ?',
      card: { title: 'Il y a beaucoup plus de plantes que de carnivores.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Pyramide énergétique.',
      incorrectFeedback: 'Si. Règle des 10 %.',
      explanation: 'Pyramide d\'Eltonien.',
    },
    {
      id: 'c2-pred-leg-7-q',
      type: 'QUIZ',
      conceptId: 'predator-regulation',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Choisir la formulation juste.',
      question: 'Comment décrire le mieux le rôle d\'un prédateur ?',
      options: [
        { text: 'Régulateur des proies, stabilisateur de l\'écosystème', isCorrect: true, feedback: 'Exact.' },
        { text: 'Destructeur', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'predators-are-villains' },
        { text: 'Producteur', isCorrect: false, feedback: 'Confusion. Producteur = plante.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c2-pred-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'trophic-cascade',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Cascade Yellowstone complète.',
      instruction: 'Ordonne la cascade Yellowstone :',
      axis: 'horizontal',
      axisRationale: 'Chronologie causale.',
      slotCount: 5,
      items: [
        { id: 'cple-1', text: '🐺 Loup réintroduit' },
        { id: 'cple-2', text: '🦌 Cerfs régulés' },
        { id: 'cple-3', text: '🌳 Berges revégétalisées' },
        { id: 'cple-4', text: '🦫 Castors reviennent' },
        { id: 'cple-5', text: '🏞️ Rivières restaurées' },
      ],
      correctFeedback: 'Excellent. Cascade complète maîtrisée.',
      incorrectFeedback: 'Indice : loup déclenche, rivière conclut.',
      interleavesConceptIds: ['ecosystem-flow'],
    },
    {
      id: 'c2-pred-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'predator-regulation',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Sprint : prédateurs utiles.',
      question: 'Vrai ou faux ?',
      card: { title: 'Une forêt avec prédateurs est plus saine qu\'une forêt sans.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Régulation = stabilité.',
      incorrectFeedback: 'Si. Vu en cours.',
      explanation: 'Yellowstone = cas d\'école.',
      misconceptionId: 'predators-are-villains',
    },
    {
      id: 'c2-pred-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : producteurs à la base.',
      question: 'Vrai ou faux ?',
      card: { title: 'Sans plantes, il ne peut y avoir aucune chaîne alimentaire terrestre.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Producteurs = base obligatoire.',
      incorrectFeedback: 'Si. Pas de plantes = pas de chaîne.',
      explanation: 'Vu au chap 1.',
    },
    {
      id: 'c2-pred-leg-11-q',
      type: 'QUIZ',
      conceptId: 'predator-regulation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthétiser : interdépendance.',
      question: 'Pourquoi protéger les grands prédateurs ?',
      options: [
        { text: 'Parce qu\'ils maintiennent tout l\'écosystème en équilibre', isCorrect: true, feedback: 'Exact. Espèce-clé.' },
        { text: 'Parce qu\'ils sont jolis', isCorrect: false, feedback: 'Esthétique seul ne suffit pas.' },
        { text: 'Parce qu\'ils ne servent à rien', isCorrect: false, feedback: 'Inverse.', misconceptionId: 'predators-are-villains' },
      ],
    },
    {
      id: 'c2-pred-leg-12-reveal',
      type: 'STORY',
      conceptId: 'predator-regulation',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective : changement de regard.',
      screens: [
        {
          text: 'Un prédateur n\'est pas un méchant. C\'est un pivot. Quand tu en vois un, tu vois une forêt qui marche.',
          imagePrompt: 'Loup et cerfs dans une vallée saine',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['pivot'],
        },
      ],
    },
    {
      id: 'c2-pred-leg-13-q',
      type: 'QUIZ',
      conceptId: 'predator-regulation',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Choisir un geste cohérent.',
      question: 'Quelle action soutient les écosystèmes via les prédateurs ?',
      options: [
        { text: 'Soutenir la réintroduction et protection des grands carnivores', isCorrect: true, feedback: 'Exact. Pratique éprouvée.' },
        { text: 'Chasser les loups pour protéger les cerfs', isCorrect: false, feedback: 'Inverse de la science.', misconceptionId: 'predators-are-villains' },
        { text: 'Construire des clôtures partout', isCorrect: false, feedback: 'Fragmente les écosystèmes.' },
      ],
    },
    {
      id: 'c2-pred-leg-14-closure',
      type: 'STORY',
      conceptId: 'predator-regulation',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer la transition vers Alliances Invisibles.',
      screens: [
        {
          text: 'Tu sais que les espèces se mangent. Mais elles s\'allient aussi en secret. Bienvenue dans le monde des symbioses.',
          imagePrompt: 'Poisson-clown dans anémone',
          imageUrl: FIELD_IMAGE,
          kind: 'closure',
          boldTokens: ['allient'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'c2-pred-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir le rôle régulateur des prédateurs.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'c2-pred-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser le rôle des prédateurs.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 1 },
    },
    {
      id: 'c2-pred-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler le concept dans des cas pièges.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'c2-pred-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise du rôle des prédateurs.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 20, label: '20 Graines' },
    },
  ],
}
