import type { AcademyUnitDefinition } from '../../../schema'

const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const WATER_IMAGE =
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1000&auto=format&fit=crop'

export const madagascarUnit: AcademyUnitDefinition = {
  id: 'unit-4-1',
  slug: 'lile-aux-lemuriens',
  chapterId: 'chapter-4',
  schemaVersion: 2,
  title: "L'Île aux Lémuriens",
  shortTitle: 'Madagascar',
  pathLabel: 'Île unique',
  subtitle: "Le laboratoire secret de la nature.",
  concept: 'Endémisme, isolement, biodiversité unique',
  conceptIds: ['endemism-isolation', 'biodiversity-madagascar', 'biodiversity-island'],
  kind: 'fauna',
  iconKey: 'island',
  masteryGoal: 'Comprendre l\'endémisme comme moteur de biodiversité unique.',
  order: 1,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: 'Voir l\'isolement géographique comme fabrique d\'espèces uniques.',
  mascot: 'sylva',
  rewardAmount: 40,

  authoredDiscovery: [
    {
      id: 'c4-mada-disc-1-hook',
      type: 'STORY',
      conceptId: 'endemism-isolation',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe de Madagascar.',
      screens: [
        {
          text: 'Madagascar : ~90 % des espèces animales et végétales ne vivent nulle part ailleurs sur Terre. Comment ?',
          imagePrompt: 'Madagascar vue du ciel avec lémuriens',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['90 %'],
        },
      ],
    },
    {
      id: 'c4-mada-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'endemism-isolation',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester l\'idée que les lémuriens vivent partout.',
      question: 'Vrai ou faux ?',
      card: { title: "Les lémuriens vivent dans plusieurs pays du monde.", subtitle: 'Intuition' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bien vu. Tous les ~100 espèces de lémuriens ne vivent QU\'à Madagascar.',
      incorrectFeedback: 'Faux. Endémisme strict.',
      explanation: 'Lémuriens = Madagascar uniquement.',
      misconceptionId: 'lemurs-everywhere',
    },
    {
      id: 'c4-mada-disc-3-reveal',
      type: 'STORY',
      conceptId: 'endemism-isolation',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler le mécanisme de l\'endémisme.',
      screens: [
        {
          text: 'Il y a ~60 millions d\'années, Madagascar s\'est détachée du continent. Les lémuriens ont dérivé sur des radeaux de végétation.',
          imagePrompt: 'Lémuriens dérivant sur radeau',
          imageUrl: WATER_IMAGE,
          kind: 'reveal',
          boldTokens: ['détachée'],
        },
        {
          text: 'Isolés, ils ont évolué en ~100 espèces uniques. C\'est l\'endémisme : adaptation locale extrême.',
          imagePrompt: 'Galerie de lémuriens variés',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['endémisme'],
        },
      ],
    },
    {
      id: 'c4-mada-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'endemism-isolation',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Identifier l\'endémisme.',
      question: "Qu'est-ce qu'une espèce endémique ?",
      options: [
        { text: 'Une espèce qui vit dans un seul lieu au monde', isCorrect: true, feedback: 'Exact.' },
        { text: 'Une espèce malade', isCorrect: false, feedback: 'Confusion avec « épidémique ».' },
        { text: 'Une espèce migratrice', isCorrect: false, feedback: 'Inverse. Endémique = ne bouge pas géographiquement.' },
      ],
      hint: 'Pense aux lémuriens.',
    },
    {
      id: 'c4-mada-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'biodiversity-island',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir « îles = peu de biodiversité ».',
      question: 'Vrai ou faux ?',
      card: { title: "Les îles ont peu de biodiversité parce qu'elles sont petites.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Souvent inverse : biodiversité unique au monde.',
      incorrectFeedback: 'Faux. Madagascar, Galápagos, Nouvelle-Zélande = championnes d\'endémisme.',
      explanation: 'Isolement = laboratoire.',
      misconceptionId: 'islands-poor-biodiversity',
    },
    {
      id: 'c4-mada-disc-6-build',
      type: 'STORY',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Étendre à d\'autres espèces emblématiques.',
      screens: [
        {
          text: 'Pas que les lémuriens : caméléons, baobabs, tortues, fossas... Madagascar est un musée vivant unique.',
          imagePrompt: 'Baobabs et caméléons',
          imageUrl: FIELD_IMAGE,
          kind: 'build-up',
          boldTokens: ['musée'],
        },
      ],
    },
    {
      id: 'c4-mada-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'endemism-isolation',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Reconstituer l\'arrivée des lémuriens.',
      instruction: 'Ordonne l\'histoire des lémuriens :',
      axis: 'horizontal',
      axisRationale: 'Chronologie évolutive.',
      slotCount: 3,
      items: [
        { id: 'cma-1', text: '🌍 Détachement de Madagascar' },
        { id: 'cma-2', text: '🛟 Dérive sur radeaux' },
        { id: 'cma-3', text: '🧬 Évolution en 100 espèces' },
      ],
      correctFeedback: 'Parfait. Histoire évolutive complète.',
      incorrectFeedback: 'Indice : île d\'abord, dérive ensuite, espèces à la fin.',
    },
    {
      id: 'c4-mada-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'endemism-isolation',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint isolement.',
      question: 'Vrai ou faux ?',
      card: { title: 'L\'isolement géographique favorise la naissance de nouvelles espèces.', subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Pas d\'échange génétique = évolution divergente.',
      incorrectFeedback: 'Si. Spéciation allopatrique.',
      explanation: 'Isolement = moteur de spéciation.',
    },
    {
      id: 'c4-mada-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint Madagascar pourcentage.',
      question: 'Vrai ou faux ?',
      card: { title: '~90 % des espèces de Madagascar sont endémiques.', subtitle: 'Sprint 2' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Record mondial.',
      incorrectFeedback: 'Si. Documenté IUCN.',
      explanation: '~90 % unique au monde.',
    },
    {
      id: 'c4-mada-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'endemism-isolation',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: 'Vulnérabilité des espèces endémiques.',
      question: 'Pourquoi une espèce endémique est-elle plus fragile ?',
      options: [
        { text: 'Si son habitat unique disparaît, elle ne peut pas se reloger ailleurs', isCorrect: true, feedback: 'Exact. Fragilité spécifique.' },
        { text: 'Elle est mal adaptée', isCorrect: false, feedback: 'Inverse. Très adaptée à son milieu unique.' },
        { text: 'Aucune raison', isCorrect: false, feedback: 'Il y en a une.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c4-mada-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'biodiversity-island',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les îles à fort endémisme.',
      instruction: 'Du moins au plus endémique :',
      axis: 'horizontal',
      axisRationale: 'Gradient.',
      slotCount: 3,
      items: [
        { id: 'cmb-1', text: '🏝️ Une île jeune' },
        { id: 'cmb-2', text: '🌴 Galápagos (~60 % endémique)' },
        { id: 'cmb-3', text: '🐒 Madagascar (~90 %)' },
        { id: 'cmb-distract', text: '🏙️ Manhattan', isDistractor: true },
      ],
      correctFeedback: 'Excellent. Manhattan n\'est pas un sanctuaire d\'endémisme.',
      incorrectFeedback: 'Indice : un seul item n\'est pas naturel.',
    },
    {
      id: 'c4-mada-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'endemism-isolation',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser : isolement = laboratoire.',
      question: 'Pourquoi les îles isolées sont-elles précieuses ?',
      options: [
        { text: 'Elles abritent des espèces uniques au monde, irremplaçables', isCorrect: true, feedback: 'Exact.' },
        { text: 'Elles sont jolies', isCorrect: false, feedback: 'Esthétique seul ne suffit pas.' },
        { text: 'Elles sont vides', isCorrect: false, feedback: 'Inverse. Très riches.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c4-mada-pool-sw-darwin-finches',
      type: 'SWIPE',
      conceptId: 'endemism-isolation',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Galápagos.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les pinsons des Galápagos ont développé des becs différents selon les îles.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Cas Darwin.',
      incorrectFeedback: 'Si. Adaptation locale.',
      explanation: 'Spéciation par isolement.',
      interleavesConceptIds: ['evolution-natural-selection'],
    },
    {
      id: 'c4-mada-pool-sw-deforest-mada',
      type: 'SWIPE',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Déforestation Madagascar.',
      question: 'Vrai ou faux ?',
      card: { title: 'La déforestation à Madagascar menace ses lémuriens d\'extinction.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. ~95 % des lémuriens menacés.',
      incorrectFeedback: 'Si. UICN classe critiquement.',
      explanation: 'Habitat = unique = irremplaçable.',
    },
    {
      id: 'c4-mada-pool-sw-baobab',
      type: 'SWIPE',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Baobabs.',
      question: 'Vrai ou faux ?',
      card: { title: '6 des 8 espèces de baobabs sont endémiques de Madagascar.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Symbole de Madagascar.',
    },
    {
      id: 'c4-mada-pool-sw-island-fragile',
      type: 'SWIPE',
      conceptId: 'biodiversity-island',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Fragilité.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les espèces insulaires sont plus vulnérables aux espèces invasives.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Pas d\'évolution face à de nouveaux prédateurs.',
      incorrectFeedback: 'Si.',
      explanation: 'Île + invasive = catastrophe.',
    },
    {
      id: 'c4-mada-pool-q-endemism-def',
      type: 'QUIZ',
      conceptId: 'endemism-isolation',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Définir endémique.',
      question: 'Une espèce endémique de Corse...',
      options: [
        { text: 'Vit uniquement en Corse', isCorrect: true, feedback: 'Exact.' },
        { text: 'Vit partout sauf en Corse', isCorrect: false, feedback: 'Inverse.' },
        { text: 'Est en voie d\'extinction', isCorrect: false, feedback: 'Pas la définition.' },
      ],
    },
    {
      id: 'c4-mada-pool-q-meta-isolation',
      type: 'QUIZ',
      conceptId: 'endemism-isolation',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Pourquoi isolement = endémisme.',
      question: 'Pourquoi l\'isolement géographique génère-t-il des espèces uniques ?',
      options: [
        { text: 'Pas d\'échange génétique = évolution divergente locale', isCorrect: true, feedback: 'Exact.' },
        { text: 'Les espèces se transforment plus vite', isCorrect: false, feedback: 'Pas plus vite, juste séparément.' },
        { text: 'Aucune raison', isCorrect: false, feedback: 'Mécanisme connu.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c4-mada-pool-q-protection',
      type: 'QUIZ',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hotspot.',
      question: 'Pourquoi Madagascar est-elle classée hotspot de biodiversité ?',
      options: [
        { text: 'Très haute concentration d\'espèces endémiques + menace forte', isCorrect: true, feedback: 'Exact. Critère Conservation International.' },
        { text: 'Beaucoup d\'humains', isCorrect: false, feedback: 'Pas le critère.' },
        { text: 'Beaucoup d\'eau', isCorrect: false, feedback: 'Pas le critère.' },
      ],
    },
    {
      id: 'c4-mada-pool-d-evolution',
      type: 'DRAG_DROP',
      conceptId: 'endemism-isolation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Reconstituer la spéciation.',
      instruction: 'Ordonne le mécanisme :',
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 3,
      items: [
        { id: 'cmpe-1', text: '🌍 Isolement' },
        { id: 'cmpe-2', text: '🧬 Mutations divergentes' },
        { id: 'cmpe-3', text: '🦎 Nouvelle espèce' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : isoler, diverger, devenir distinct.',
    },
    {
      id: 'c4-mada-pool-d-islands',
      type: 'DRAG_DROP',
      conceptId: 'biodiversity-island',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les sanctuaires.',
      instruction: 'Du plus jeune au plus ancien sanctuaire endémique :',
      axis: 'horizontal',
      axisRationale: 'Gradient temporel.',
      slotCount: 3,
      items: [
        { id: 'cmis-1', text: '🌋 Galápagos (~5 Ma)' },
        { id: 'cmis-2', text: '🦘 Australie (~50 Ma)' },
        { id: 'cmis-3', text: '🐒 Madagascar (~88 Ma)' },
      ],
      correctFeedback: 'Excellent.',
      incorrectFeedback: 'Indice : Madagascar = la plus ancienne.',
    },
    {
      id: 'c4-mada-pool-sw-invasive',
      type: 'SWIPE',
      conceptId: 'biodiversity-island',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Espèces invasives.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les espèces invasives sont une menace majeure pour les écosystèmes insulaires.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. ~70 % des extinctions insulaires causées par invasives.',
      incorrectFeedback: 'Si. Données IUCN.',
      explanation: 'Espèces locales pas adaptées aux nouvelles menaces.',
    },
    {
      id: 'c4-mada-pool-sw-coevolve-island',
      type: 'SWIPE',
      conceptId: 'endemism-isolation',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Coévolution insulaire.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les espèces insulaires coévoluent souvent en symbioses uniques.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Réseaux écologiques uniques.',
      incorrectFeedback: 'Si. Coévolution + isolement = relations rares.',
      explanation: 'Cocodemar / fleur de baobab.',
      interleavesConceptIds: ['symbiosis-types'],
    },
    {
      id: 'c4-mada-pool-q-aye-aye',
      type: 'QUIZ',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Animal emblématique.',
      question: 'Quel est le « pic-vert » de Madagascar (frappe le bois pour trouver des larves) ?',
      options: [
        { text: 'L\'aye-aye, un lémurien aux longs doigts', isCorrect: true, feedback: 'Exact. Niche écologique unique.' },
        { text: 'Un vrai pic-vert', isCorrect: false, feedback: 'Pas de pics-verts à Madagascar.' },
        { text: 'Un caméléon', isCorrect: false, feedback: 'Caméléons mangent autrement.' },
      ],
    },
  ],

  authoredLegendary: [
    {
      id: 'c4-mada-leg-1-hook',
      type: 'STORY',
      conceptId: 'endemism-isolation',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le boss.',
      screens: [
        {
          text: '14 questions pour valider l\'endémisme et la fragilité des îles.',
          imagePrompt: 'Madagascar avec lémuriens',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['endémisme'],
        },
      ],
    },
    {
      id: 'c4-mada-leg-2-q',
      type: 'QUIZ',
      conceptId: 'endemism-isolation',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Définition endémique.',
      question: 'Qu\'est-ce qu\'une espèce endémique ?',
      options: [
        { text: 'Vit uniquement dans un lieu précis', isCorrect: true, feedback: 'Exact.' },
        { text: 'Vit partout', isCorrect: false, feedback: 'Inverse.' },
        { text: 'Est malade', isCorrect: false, feedback: 'Confusion sémantique.' },
      ],
    },
    {
      id: 'c4-mada-leg-3-q',
      type: 'QUIZ',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Lémuriens uniques.',
      question: 'Où vivent les lémuriens dans la nature ?',
      options: [
        { text: 'Uniquement à Madagascar', isCorrect: true, feedback: 'Exact.' },
        { text: 'Partout en Afrique', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'lemurs-everywhere' },
        { text: 'En Asie', isCorrect: false, feedback: 'Faux.' },
      ],
    },
    {
      id: 'c4-mada-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'endemism-isolation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Mécanisme de spéciation.',
      instruction: 'Ordonne la spéciation :',
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 4,
      items: [
        { id: 'cmlg-1', text: '🌍 Population unique' },
        { id: 'cmlg-2', text: '🚧 Isolement' },
        { id: 'cmlg-3', text: '🧬 Évolution divergente' },
        { id: 'cmlg-4', text: '🦎 Espèces distinctes' },
        { id: 'cmlg-distract', text: '☄️ Météorite cosmique', isDistractor: true },
      ],
      correctFeedback: 'Excellent. La météorite n\'a rien à voir.',
      incorrectFeedback: 'Indice : un item est faux.',
    },
    {
      id: 'c4-mada-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'biodiversity-island',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Îles riches.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les îles isolées peuvent être très riches en espèces uniques.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Madagascar, Galápagos, NZ.',
      misconceptionId: 'islands-poor-biodiversity',
    },
    {
      id: 'c4-mada-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Pourcentage endémisme.',
      question: 'Vrai ou faux ?',
      card: { title: '~90 % des espèces de Madagascar sont uniques au monde.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Record mondial.',
    },
    {
      id: 'c4-mada-leg-7-q',
      type: 'QUIZ',
      conceptId: 'endemism-isolation',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Définition juste.',
      question: 'Comment décrire le mieux l\'endémisme ?',
      options: [
        { text: 'Espèces qui vivent uniquement dans un lieu donné, par adaptation locale', isCorrect: true, feedback: 'Exact.' },
        { text: 'Espèces malades', isCorrect: false, feedback: 'Confusion.' },
        { text: 'Espèces voyageuses', isCorrect: false, feedback: 'Inverse.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c4-mada-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'endemism-isolation',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Lien évolution + isolement.',
      instruction: 'Reconstituer le mécanisme :',
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 4,
      items: [
        { id: 'cmli-1', text: '🚧 Isolement' },
        { id: 'cmli-2', text: '🎲 Mutations aléatoires' },
        { id: 'cmli-3', text: '🏆 Sélection locale' },
        { id: 'cmli-4', text: '🦎 Endémisme' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : isoler → muter → sélectionner → endémique.',
      interleavesConceptIds: ['evolution-natural-selection'],
    },
    {
      id: 'c4-mada-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'biodiversity-island',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint fragilité.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les espèces endémiques sont plus fragiles que les espèces très répandues.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Habitat unique = vulnérabilité.',
      incorrectFeedback: 'Si.',
      explanation: 'Pas de plan B.',
    },
    {
      id: 'c4-mada-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint déforestation.',
      question: 'Vrai ou faux ?',
      card: { title: 'La déforestation à Madagascar menace 95 % des lémuriens.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. UICN.',
      incorrectFeedback: 'Si.',
      explanation: 'Critique.',
    },
    {
      id: 'c4-mada-leg-11-q',
      type: 'QUIZ',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthétiser.',
      question: 'Pourquoi protéger Madagascar est-il prioritaire ?',
      options: [
        { text: 'Sa biodiversité unique est irremplaçable une fois perdue', isCorrect: true, feedback: 'Exact.' },
        { text: 'Parce qu\'elle est jolie', isCorrect: false, feedback: 'Esthétique seul ne suffit pas.' },
        { text: 'Parce qu\'elle est grande', isCorrect: false, feedback: 'Pas le critère.' },
      ],
    },
    {
      id: 'c4-mada-leg-12-reveal',
      type: 'STORY',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective.',
      screens: [
        {
          text: 'Madagascar est un livre ouvert sur 88 millions d\'années d\'évolution. Le perdre, c\'est brûler la bibliothèque.',
          imagePrompt: 'Bibliothèque verte avec lémuriens',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['bibliothèque'],
        },
      ],
    },
    {
      id: 'c4-mada-leg-13-q',
      type: 'QUIZ',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Action.',
      question: 'Comment soutenir la biodiversité endémique ?',
      options: [
        { text: 'Soutenir des programmes de conservation locale', isCorrect: true, feedback: 'Exact.' },
        { text: 'Acheter des animaux exotiques', isCorrect: false, feedback: 'Souvent illégal et destructeur.' },
        { text: 'Visiter sans guide', isCorrect: false, feedback: 'Tourisme non régulé peut nuire.' },
      ],
    },
    {
      id: 'c4-mada-leg-14-closure',
      type: 'STORY',
      conceptId: 'biodiversity-madagascar',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer Coraux.',
      screens: [
        {
          text: 'Tu connais une île sanctuaire. Place à un sanctuaire sous-marin : les récifs coralliens.',
          imagePrompt: 'Récif corallien coloré',
          imageUrl: WATER_IMAGE,
          kind: 'closure',
          boldTokens: ['récifs'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'c4-mada-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir l\'endémisme.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'c4-mada-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser l\'endémisme.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'c4-mada-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler l\'endémisme.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 3 },
    },
    {
      id: 'c4-mada-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 40, label: '40 Graines' },
    },
  ],
}
