import type { AcademyUnitDefinition } from '../../../schema'

const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const SPROUT_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'

export const seasonsUnit: AcademyUnitDefinition = {
  id: 'unit-4-3',
  slug: 'le-bal-des-saisons',
  chapterId: 'chapter-4',
  schemaVersion: 2,
  title: 'Le Bal des Saisons',
  shortTitle: 'Saisons',
  pathLabel: 'Cycles annuels',
  subtitle: 'Comment forêts et animaux se synchronisent au rythme de la Terre.',
  concept: 'Saisons, hibernation, photopériode',
  conceptIds: ['seasons-adaptation', 'plant-strategy', 'metabolism'],
  kind: 'flora',
  iconKey: 'leaf-falling',
  masteryGoal: 'Comprendre les adaptations saisonnières comme stratégies vitales.',
  order: 3,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: 'Voir les saisons comme orchestre du vivant tempéré.',
  mascot: 'abeille-transparente',
  rewardAmount: 45,

  authoredDiscovery: [
    {
      id: 'c4-sea-disc-1-hook',
      type: 'STORY',
      conceptId: 'seasons-adaptation',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : les feuilles tombent à cause... de la lumière.',
      screens: [
        {
          text: "Les feuilles tombent en automne. La cause principale n'est pas le froid. C'est la baisse de luminosité.",
          imagePrompt: 'Forêt automnale',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['luminosité'],
        },
      ],
    },
    {
      id: 'c4-sea-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'seasons-adaptation',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester la misconception « feuilles tombent à cause du froid ».',
      question: 'Vrai ou faux ?',
      card: { title: "Les feuilles tombent à cause du froid de l'hiver.", subtitle: 'Intuition' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bien vu. Le déclencheur principal est la baisse de luminosité (photopériode).',
      incorrectFeedback: 'Faux. Vérifié : arbres en serre chauffée perdent leurs feuilles aussi.',
      explanation: 'Photopériode = signal principal.',
      misconceptionId: 'leaves-fall-because-cold',
    },
    {
      id: 'c4-sea-disc-3-reveal',
      type: 'STORY',
      conceptId: 'plant-strategy',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler la stratégie de la chute des feuilles.',
      screens: [
        {
          text: "Les feuilles consomment beaucoup d'eau. En hiver, l'eau gèle. L'arbre choisit donc de les abandonner avant.",
          imagePrompt: 'Arbre se déshabillant à l\'automne',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['abandonner'],
        },
        {
          text: "Avant de tomber, l'arbre récupère les nutriments des feuilles. Le rouge et l'orange = pigments cachés sous le vert.",
          imagePrompt: 'Couleurs automnales en gros plan',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['récupère'],
        },
      ],
    },
    {
      id: 'c4-sea-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: ['generation', 'misconception'],
      learningObjective: 'Identifier le déclencheur.',
      question: "Qu'est-ce qui déclenche la chute des feuilles ?",
      options: [
        { text: 'La baisse de luminosité (photopériode)', isCorrect: true, feedback: 'Exact.' },
        { text: 'Le froid', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'leaves-fall-because-cold' },
        { text: 'Le vent', isCorrect: false, feedback: 'Effet, pas cause.' },
      ],
      hint: 'Pense à ce qui change avant le froid.',
    },
    {
      id: 'c4-sea-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'metabolism',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir « hibernation = sommeil ».',
      question: 'Vrai ou faux ?',
      card: { title: "L'hibernation, c'est juste un long sommeil.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. C\'est un état physiologique distinct : métabolisme divisé par 10+.',
      incorrectFeedback: 'Faux. Pas du tout du sommeil normal.',
      explanation: 'Température corps ↘, rythme cardiaque ↘, respiration ↘.',
      misconceptionId: 'hibernation-is-sleep',
    },
    {
      id: 'c4-sea-disc-6-build',
      type: 'STORY',
      conceptId: 'seasons-adaptation',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Stratégies hivernales variées.',
      screens: [
        {
          text: 'Stratégies hivernales : hiberner (marmotte), migrer (cigogne), persister (chêne sans feuilles), résister (sapin).',
          imagePrompt: 'Quatre stratégies illustrées',
          imageUrl: FIELD_IMAGE,
          kind: 'build-up',
          boldTokens: ['stratégies'],
        },
      ],
    },
    {
      id: 'c4-sea-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Reconstituer le cycle annuel.',
      instruction: 'Ordonne le cycle annuel d\'un chêne :',
      axis: 'horizontal',
      axisRationale: 'Chronologie annuelle.',
      slotCount: 4,
      items: [
        { id: 'cse-1', text: '🌱 Printemps : bourgeons' },
        { id: 'cse-2', text: '☀️ Été : feuilles vertes' },
        { id: 'cse-3', text: '🍂 Automne : feuilles tombent' },
        { id: 'cse-4', text: '🌲 Hiver : repos' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : du réveil au repos.',
    },
    {
      id: 'c4-sea-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'seasons-adaptation',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint migration.',
      question: 'Vrai ou faux ?',
      card: { title: "La migration des oiseaux est une réponse aux changements saisonniers.", subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Stratégie de fuite vers ressources.',
    },
    {
      id: 'c4-sea-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'metabolism',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Sprint hibernation profonde.',
      question: 'Vrai ou faux ?',
      card: { title: "Pendant l'hibernation, le métabolisme d'un animal chute drastiquement.", subtitle: 'Sprint 2' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Divisé par 10+.',
      incorrectFeedback: 'Si.',
      explanation: 'Hibernation ≠ sommeil.',
      misconceptionId: 'hibernation-is-sleep',
    },
    {
      id: 'c4-sea-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'seasons-adaptation',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Pourquoi feuilles tombent.',
      question: "Pourquoi les arbres feuillus perdent-ils leurs feuilles avant l'hiver ?",
      options: [
        { text: 'Pour économiser l\'eau quand le sol gèle', isCorrect: true, feedback: 'Exact. Stratégie d\'économie hydrique.' },
        { text: 'Parce qu\'ils ont froid', isCorrect: false, feedback: 'Pas le mécanisme.', misconceptionId: 'leaves-fall-because-cold' },
        { text: 'Pour faire joli', isCorrect: false, feedback: 'Esthétique humaine, pas la fonction.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c4-sea-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les stratégies hivernales.',
      instruction: 'Stratégies hivernales :',
      axis: 'horizontal',
      axisRationale: 'Mapping.',
      slotCount: 4,
      items: [
        { id: 'csb-1', text: '🐻 Marmotte (hiberne)' },
        { id: 'csb-2', text: '🦅 Cigogne (migre)' },
        { id: 'csb-3', text: '🌳 Chêne (perd feuilles)' },
        { id: 'csb-4', text: '🌲 Sapin (résiste)' },
        { id: 'csb-distract', text: '🪨 Roche (rien)', isDistractor: true },
      ],
      correctFeedback: 'Excellent. La roche n\'a pas de stratégie biologique.',
      incorrectFeedback: 'Indice : un seul item n\'est pas vivant.',
    },
    {
      id: 'c4-sea-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser : saisons = orchestre.',
      question: 'Comment qualifier le rôle des saisons dans les écosystèmes tempérés ?',
      options: [
        { text: 'Un orchestre qui synchronise tout le vivant', isCorrect: true, feedback: 'Exact.' },
        { text: 'Une variation décorative', isCorrect: false, feedback: 'Pas qu\'esthétique.' },
        { text: 'Sans importance écologique', isCorrect: false, feedback: 'Faux.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c4-sea-pool-sw-photoperiod',
      type: 'SWIPE',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Photopériode.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les arbres feuillus utilisent la durée du jour pour savoir quand perdre leurs feuilles.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si. Photopériode.',
      explanation: 'Pas le froid.',
      misconceptionId: 'leaves-fall-because-cold',
    },
    {
      id: 'c4-sea-pool-sw-hibernation',
      type: 'SWIPE',
      conceptId: 'metabolism',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Hibernation distinct.',
      question: 'Vrai ou faux ?',
      card: { title: "L'hibernation est physiologiquement très différente du sommeil.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Métabolisme divisé par 10+.',
      misconceptionId: 'hibernation-is-sleep',
    },
    {
      id: 'c4-sea-pool-sw-migration',
      type: 'SWIPE',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Migration distance.',
      question: 'Vrai ou faux ?',
      card: { title: "La sterne arctique migre 70 000 km par an entre les deux pôles.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Record absolu.',
      incorrectFeedback: 'Si.',
      explanation: 'Champion de la migration.',
    },
    {
      id: 'c4-sea-pool-sw-evergreen',
      type: 'SWIPE',
      conceptId: 'plant-strategy',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Conifères.',
      question: 'Vrai ou faux ?',
      card: { title: "Les sapins gardent leurs aiguilles toute l'année grâce à leur forme cireuse résistante.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Stratégie persistante.',
      incorrectFeedback: 'Si.',
      explanation: 'Aiguilles minimisent perte d\'eau.',
    },
    {
      id: 'c4-sea-pool-q-meta-fall',
      type: 'QUIZ',
      conceptId: 'plant-strategy',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Stratégie économique.',
      question: 'Pourquoi les arbres laissent-ils tomber leurs feuilles ?',
      options: [
        { text: 'Pour économiser l\'eau et l\'énergie en hiver', isCorrect: true, feedback: 'Exact.' },
        { text: 'Parce qu\'ils ont froid', isCorrect: false, feedback: 'Pas le mécanisme.', misconceptionId: 'leaves-fall-because-cold' },
        { text: 'Pour faire de la place aux fruits', isCorrect: false, feedback: 'Pas la raison principale.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c4-sea-pool-q-tropical',
      type: 'QUIZ',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Saisons tropicales.',
      question: 'Y a-t-il des saisons sous les tropiques ?',
      options: [
        { text: 'Oui, mais saisons sèche et humide', isCorrect: true, feedback: 'Exact.' },
        { text: 'Non, jamais', isCorrect: false, feedback: 'Faux.' },
        { text: 'Oui, comme en Europe', isCorrect: false, feedback: 'Différentes.' },
      ],
    },
    {
      id: 'c4-sea-pool-q-bear-myth',
      type: 'QUIZ',
      conceptId: 'metabolism',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Ours et hibernation.',
      question: 'L\'ours brun est-il un vrai hibernant ?',
      options: [
        { text: 'Pas vraiment : il dort plus profondément, mais sa température baisse peu', isCorrect: true, feedback: 'Exact. C\'est un dormeur, pas un vrai hibernant.' },
        { text: 'Oui, comme la marmotte', isCorrect: false, feedback: 'Faux. Différence physiologique nette.' },
        { text: 'Non, il reste actif', isCorrect: false, feedback: 'Pas si actif.' },
      ],
    },
    {
      id: 'c4-sea-pool-d-cycle',
      type: 'DRAG_DROP',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Cycle annuel forêt.',
      instruction: 'Ordonne le cycle :',
      axis: 'horizontal',
      axisRationale: 'Chronologie annuelle.',
      slotCount: 4,
      items: [
        { id: 'cssc-1', text: '🌱 Printemps' },
        { id: 'cssc-2', text: '☀️ Été' },
        { id: 'cssc-3', text: '🍂 Automne' },
        { id: 'cssc-4', text: '❄️ Hiver' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : ordre habituel.',
    },
    {
      id: 'c4-sea-pool-d-strategies',
      type: 'DRAG_DROP',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les stratégies par radicalité.',
      instruction: 'Du moins radical au plus radical :',
      axis: 'horizontal',
      axisRationale: 'Gradient.',
      slotCount: 3,
      items: [
        { id: 'csst-1', text: '🌲 Résister (sapin)' },
        { id: 'csst-2', text: '🌳 Perdre feuilles (chêne)' },
        { id: 'csst-3', text: '🐻 Hiberner (marmotte)' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : sapin = peu de changement, hibernation = transformation totale.',
    },
    {
      id: 'c4-sea-pool-sw-disrupt',
      type: 'SWIPE',
      conceptId: 'seasons-adaptation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Climat dérègle saisons.',
      question: 'Vrai ou faux ?',
      card: { title: 'Le réchauffement climatique perturbe les rythmes saisonniers du vivant.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Décalages observés.',
      incorrectFeedback: 'Si.',
      explanation: 'Bourgeons précoces, migration décalée.',
    },
    {
      id: 'c4-sea-pool-sw-leaf-color',
      type: 'SWIPE',
      conceptId: 'plant-strategy',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Couleurs automnales.',
      question: 'Vrai ou faux ?',
      card: { title: "Les pigments rouges des feuilles existent toute l'année, mais sont cachés par le vert.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Caroténoïdes et anthocyanes.',
      incorrectFeedback: 'Si. Le vert recule, le rouge apparaît.',
      explanation: 'Plus exactement : caroténoïdes étaient là, anthocyanes apparaissent.',
    },
    {
      id: 'c4-sea-pool-q-bird-trigger',
      type: 'QUIZ',
      conceptId: 'seasons-adaptation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Trigger migration.',
      question: 'Qu\'est-ce qui déclenche la migration des oiseaux ?',
      options: [
        { text: 'Photopériode + ressources alimentaires', isCorrect: true, feedback: 'Exact.' },
        { text: 'Le froid uniquement', isCorrect: false, feedback: 'Trop limité.' },
        { text: 'L\'instinct sans cause externe', isCorrect: false, feedback: 'Cause externe identifiée.' },
      ],
    },
  ],

  authoredLegendary: [
    {
      id: 'c4-sea-leg-1-hook',
      type: 'STORY',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le boss.',
      screens: [
        {
          text: '14 questions pour valider que les saisons orchestrent tout le vivant tempéré.',
          imagePrompt: 'Quatre saisons en mosaïque',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['orchestrent'],
        },
      ],
    },
    {
      id: 'c4-sea-leg-2-q',
      type: 'QUIZ',
      conceptId: 'seasons-adaptation',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Trigger feuilles.',
      question: 'Qu\'est-ce qui déclenche la chute des feuilles ?',
      options: [
        { text: 'Photopériode', isCorrect: true, feedback: 'Exact.' },
        { text: 'Le froid', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'leaves-fall-because-cold' },
        { text: 'Le vent', isCorrect: false, feedback: 'Effet, pas cause.' },
      ],
    },
    {
      id: 'c4-sea-leg-3-q',
      type: 'QUIZ',
      conceptId: 'metabolism',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Hibernation distinct.',
      question: 'Qu\'est-ce que l\'hibernation ?',
      options: [
        { text: 'État physiologique distinct (métabolisme ↘)', isCorrect: true, feedback: 'Exact.' },
        { text: 'Sommeil normal long', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'hibernation-is-sleep' },
        { text: 'Activité ralentie', isCorrect: false, feedback: 'Pas seulement.' },
      ],
    },
    {
      id: 'c4-sea-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'seasons-adaptation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Stratégies hivernales.',
      instruction: 'Place ces stratégies :',
      axis: 'horizontal',
      axisRationale: 'Mapping.',
      slotCount: 4,
      items: [
        { id: 'cslg-1', text: '🐻 Hibernation' },
        { id: 'cslg-2', text: '🦅 Migration' },
        { id: 'cslg-3', text: '🍂 Perte feuilles' },
        { id: 'cslg-4', text: '🌲 Persistance' },
        { id: 'cslg-distract', text: '🤖 Activation IA', isDistractor: true },
      ],
      correctFeedback: 'Excellent.',
      incorrectFeedback: 'Indice : un seul item n\'est pas une stratégie biologique.',
    },
    {
      id: 'c4-sea-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'plant-strategy',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Stratégie économique.',
      question: 'Vrai ou faux ?',
      card: { title: "Perdre ses feuilles est une stratégie d'économie d'eau.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Sol gelé = pas d\'eau accessible.',
    },
    {
      id: 'c4-sea-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Climat décale.',
      question: 'Vrai ou faux ?',
      card: { title: "Le réchauffement climatique décale le calendrier des espèces.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Bourgeons précoces, migration décalée.',
    },
    {
      id: 'c4-sea-leg-7-q',
      type: 'QUIZ',
      conceptId: 'seasons-adaptation',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Définition juste.',
      question: 'Comment décrire les saisons en écologie ?',
      options: [
        { text: 'Orchestre qui synchronise stratégies du vivant', isCorrect: true, feedback: 'Exact.' },
        { text: 'Décor purement humain', isCorrect: false, feedback: 'Faux.' },
        { text: 'Variation sans effet', isCorrect: false, feedback: 'Faux.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c4-sea-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'seasons-adaptation',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Saisons + chaîne alimentaire.',
      instruction: 'Ordonne :',
      axis: 'horizontal',
      axisRationale: 'Chronologie causale.',
      slotCount: 4,
      items: [
        { id: 'cslr-1', text: '☀️ Printemps : feuilles' },
        { id: 'cslr-2', text: '🐛 Chenilles abondantes' },
        { id: 'cslr-3', text: '🐦 Oiseaux nourrissent jeunes' },
        { id: 'cslr-4', text: '🦅 Rapaces se reproduisent' },
      ],
      correctFeedback: 'Parfait. Cascade printanière.',
      incorrectFeedback: 'Indice : feuilles d\'abord, rapaces en dernier.',
      interleavesConceptIds: ['food-chain-link'],
    },
    {
      id: 'c4-sea-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'metabolism',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint marmotte.',
      question: 'Vrai ou faux ?',
      card: { title: "Une marmotte en hibernation a un rythme cardiaque divisé par ~10.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Hibernation profonde.',
    },
    {
      id: 'c4-sea-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'plant-strategy',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint chêne.',
      question: 'Vrai ou faux ?',
      card: { title: "Le chêne récupère les nutriments de ses feuilles avant qu'elles tombent.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Pas de gaspillage.',
      incorrectFeedback: 'Si.',
      explanation: 'Économie de matière.',
    },
    {
      id: 'c4-sea-leg-11-q',
      type: 'QUIZ',
      conceptId: 'seasons-adaptation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthèse.',
      question: 'Pourquoi la « phénologie » (calendrier biologique) est-elle un sujet climatique ?',
      options: [
        { text: 'Le réchauffement décale les rythmes et désynchronise les espèces', isCorrect: true, feedback: 'Exact.' },
        { text: 'Aucun lien climatique', isCorrect: false, feedback: 'Faux.' },
        { text: 'Sujet purement décoratif', isCorrect: false, feedback: 'Faux.' },
      ],
    },
    {
      id: 'c4-sea-leg-12-reveal',
      type: 'STORY',
      conceptId: 'seasons-adaptation',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective.',
      screens: [
        {
          text: 'Les saisons orchestrent : feuilles, fleurs, insectes, oiseaux. Si l\'orchestre se désaccorde, tout l\'écosystème souffre.',
          imagePrompt: 'Forêt avec animaux à différentes saisons',
          imageUrl: SPROUT_IMAGE,
          kind: 'reveal',
          boldTokens: ['orchestre'],
        },
      ],
    },
    {
      id: 'c4-sea-leg-13-q',
      type: 'QUIZ',
      conceptId: 'seasons-adaptation',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Action.',
      question: 'Quelle action protège les rythmes saisonniers ?',
      options: [
        { text: 'Limiter le réchauffement et préserver des habitats variés', isCorrect: true, feedback: 'Exact.' },
        { text: 'Bétonner partout', isCorrect: false, feedback: 'Détruit les habitats.' },
        { text: 'Élever artificiellement la température', isCorrect: false, feedback: 'Aggraverait.' },
      ],
    },
    {
      id: 'c4-sea-leg-14-closure',
      type: 'STORY',
      conceptId: 'seasons-adaptation',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer Chap 5.',
      screens: [
        {
          text: 'Tu connais des sanctuaires uniques. Reste à comprendre les crises actuelles. Bienvenue à l\'Éveil des Gardiens.',
          imagePrompt: 'Garde-forestier avec carte',
          imageUrl: FOREST_IMAGE,
          kind: 'closure',
          boldTokens: ['Gardiens'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'c4-sea-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir les adaptations saisonnières.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'c4-sea-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser les saisons.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'c4-sea-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler les saisons.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 3 },
    },
    {
      id: 'c4-sea-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 45, label: '45 Graines' },
    },
  ],
}
