import type { AcademyUnitDefinition } from '../../../schema'

const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const REEF_IMAGE =
  'https://images.unsplash.com/photo-1546026423-cc4642628d2b?q=80&w=1000&auto=format&fit=crop'
const SPROUT_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'

export const carbonUnit: AcademyUnitDefinition = {
  id: 'unit-3-3',
  slug: 'le-coffre-fort-noir',
  chapterId: 'chapter-3',
  schemaVersion: 2,
  title: 'Le Coffre-Fort Noir',
  shortTitle: 'Carbone',
  pathLabel: 'Coffre noir',
  subtitle: 'Le carbone, brique du vivant et thermostat planétaire.',
  concept: 'Cycle du carbone, stockage, climat',
  conceptIds: ['carbon-cycle-storage', 'climate-greenhouse-gas', 'forest-services'],
  kind: 'flora',
  iconKey: 'tree',
  masteryGoal: 'Comprendre le cycle du carbone et son rôle climatique.',
  order: 3,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: 'Voir le carbone comme circulant entre vivant, sol, air et océan.',
  mascot: 'sylva',
  rewardAmount: 35,

  authoredDiscovery: [
    {
      id: 'c3-carb-disc-1-hook',
      type: 'STORY',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : un arbre est de l\'air solidifié.',
      screens: [
        {
          text: "Le bois d'un arbre, c'est ~50 % de carbone. Et ce carbone vient... du CO₂ de l'air. Un arbre = un coffre-fort à air solidifié.",
          imagePrompt: 'Tronc avec atomes de carbone',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['coffre-fort'],
        },
      ],
    },
    {
      id: 'c3-carb-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'climate-greenhouse-gas',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester la misconception « CO₂ = poison ».',
      question: 'Vrai ou faux ?',
      card: { title: 'Le CO₂ est un poison toxique pour la nature.', subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bien vu. Le CO₂ nourrit les plantes. Le problème est l\'EXCÈS, pas la toxicité.',
      incorrectFeedback: 'Faux. Sans CO₂, pas de photosynthèse.',
      explanation: 'Équilibre vs excès.',
      misconceptionId: 'co2-is-toxic',
    },
    {
      id: 'c3-carb-disc-3-reveal',
      type: 'STORY',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler le cycle.',
      screens: [
        {
          text: 'Le carbone circule : air → plante (photosynthèse) → animal → décomposeur → air. Quand l\'équilibre est brisé, le climat se dérègle.',
          imagePrompt: 'Cycle du carbone illustré',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['équilibre'],
        },
        {
          text: 'Brûler du pétrole ou du charbon = libérer en quelques décennies du carbone stocké pendant des millions d\'années.',
          imagePrompt: 'Centrale à charbon avec fumée',
          imageUrl: SPROUT_IMAGE,
          kind: 'reveal',
          boldTokens: ['millions'],
        },
      ],
    },
    {
      id: 'c3-carb-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['generation', 'misconception'],
      learningObjective: 'Identifier les puits de carbone.',
      question: "Quel est le plus grand puits de carbone naturel après les océans ?",
      options: [
        { text: 'Les forêts ET les sols vivants', isCorrect: true, feedback: 'Exact. Sols + forêts stockent énormément.' },
        { text: 'Les déserts', isCorrect: false, feedback: 'Très peu de stockage.' },
        { text: 'Les villes', isCorrect: false, feedback: 'Pas un puits, un émetteur.' },
      ],
      hint: 'Pense à ce qui pousse et qui stocke à long terme.',
    },
    {
      id: 'c3-carb-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir « planter des arbres résout tout ».',
      question: 'Vrai ou faux ?',
      card: { title: "Planter des arbres suffit à résoudre le problème climatique.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Aide, mais ne compense qu\'une fraction des émissions.',
      incorrectFeedback: 'Faux. Préserver les forêts existantes est même plus efficace que reboiser.',
      explanation: 'Bastin 2019 + critiques Lewis 2019.',
      misconceptionId: 'planting-trees-fixes-climate',
    },
    {
      id: 'c3-carb-disc-6-build',
      type: 'STORY',
      conceptId: 'climate-greenhouse-gas',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Effet de serre simple.',
      screens: [
        {
          text: "Le CO₂ et autres gaz à effet de serre piègent une partie de la chaleur solaire. À dose normale = température OK. En excès = réchauffement.",
          imagePrompt: 'Schéma effet de serre',
          imageUrl: SPROUT_IMAGE,
          kind: 'build-up',
          boldTokens: ['piègent'],
        },
      ],
    },
    {
      id: 'c3-carb-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Reconstituer le cycle naturel.',
      instruction: 'Ordonne le cycle du carbone naturel :',
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 4,
      items: [
        { id: 'cca-1', text: '💨 CO₂ atmosphérique' },
        { id: 'cca-2', text: '🌳 Plante (photosynthèse)' },
        { id: 'cca-3', text: '🐇 Animal' },
        { id: 'cca-4', text: '🍄 Décomposeur → CO₂' },
      ],
      correctFeedback: 'Parfait. Cycle complet.',
      incorrectFeedback: 'Indice : air → plante → animal → décomposeur → air.',
    },
    {
      id: 'c3-carb-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : photosynthèse stocke.',
      question: 'Vrai ou faux ?',
      card: { title: "Une plante qui pousse stocke du CO₂ atmosphérique.", subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Photosynthèse = stockage.',
      incorrectFeedback: 'Si. Vu au chap 1.',
      explanation: 'CO₂ + lumière → sucre + bois.',
    },
    {
      id: 'c3-carb-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Sprint : vieux arbres = champions.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les vieux arbres ne stockent plus de carbone.', subtitle: 'Sprint 2' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Plus un arbre vieillit, plus il stocke vite (Stephenson 2014).',
      incorrectFeedback: 'Non. Champion absolu : le vieux chêne.',
      explanation: 'Croissance absolue augmente avec l\'âge.',
      misconceptionId: 'old-trees-stop-absorbing',
    },
    {
      id: 'c3-carb-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: 'Identifier les meilleurs puits.',
      question: 'Quel milieu naturel stocke le plus de carbone par hectare ?',
      options: [
        { text: 'Les tourbières', isCorrect: true, feedback: 'Exact. Champion absolu, devant les forêts tropicales.' },
        { text: 'Les déserts', isCorrect: false, feedback: 'Très peu.' },
        { text: 'Les océans en surface', isCorrect: false, feedback: 'Important globalement, mais peu par hectare.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c3-carb-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les puits par densité.',
      instruction: 'Du moins au plus stockeur (par hectare) :',
      axis: 'horizontal',
      axisRationale: 'Gradient de densité de stockage.',
      slotCount: 4,
      items: [
        { id: 'ccb-1', text: '🏜️ Désert' },
        { id: 'ccb-2', text: '🌾 Champ cultivé' },
        { id: 'ccb-3', text: '🌳 Forêt tropicale' },
        { id: 'ccb-4', text: '🌿 Tourbière' },
        { id: 'ccb-distract', text: '🏙️ Ville', isDistractor: true },
      ],
      correctFeedback: 'Excellent. Une ville n\'est pas un puits.',
      incorrectFeedback: 'Indice : un seul item est un émetteur, pas un puits.',
    },
    {
      id: 'c3-carb-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser : équilibre.',
      question: 'Pourquoi le carbone est-il un enjeu climatique ?',
      options: [
        { text: 'Parce que son équilibre régule la température terrestre', isCorrect: true, feedback: 'Exact. Thermostat.' },
        { text: 'Parce qu\'il est toxique', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'co2-is-toxic' },
        { text: 'Parce qu\'il est inutile', isCorrect: false, feedback: 'Inverse. Brique du vivant.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c3-carb-pool-sw-fire',
      type: 'SWIPE',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Feux de forêt.',
      question: 'Vrai ou faux ?',
      card: { title: "Un feu de forêt libère en quelques jours du carbone stocké pendant des siècles.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si. Combustion = relâche immédiate.',
      explanation: 'Stockage long, déstockage rapide.',
    },
    {
      id: 'c3-carb-pool-sw-ocean-sink',
      type: 'SWIPE',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Océan puits majeur.',
      question: 'Vrai ou faux ?',
      card: { title: "L'océan absorbe ~25 % des émissions humaines de CO₂.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Énorme puits.',
      incorrectFeedback: 'Si. Environ un quart.',
      explanation: 'Acidification = effet secondaire.',
    },
    {
      id: 'c3-carb-pool-sw-co2-toxic',
      type: 'SWIPE',
      conceptId: 'climate-greenhouse-gas',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'CO₂ pas toxique.',
      question: 'Vrai ou faux ?',
      card: { title: 'Le CO₂ est nourriture pour les plantes.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si. Photosynthèse.',
      explanation: 'Problème = excès climatique.',
      misconceptionId: 'co2-is-toxic',
    },
    {
      id: 'c3-carb-pool-sw-old-tree',
      type: 'SWIPE',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Vieux arbres champions.',
      question: 'Vrai ou faux ?',
      card: { title: 'Un vieux chêne stocke plus vite qu\'un jeune.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Stephenson 2014.',
      incorrectFeedback: 'Si. Croissance absolue augmente avec l\'âge.',
      explanation: 'Préserver les vieux arbres = priorité climatique.',
      misconceptionId: 'old-trees-stop-absorbing',
    },
    {
      id: 'c3-carb-pool-q-greenhouse',
      type: 'QUIZ',
      conceptId: 'climate-greenhouse-gas',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Effet de serre.',
      question: 'Comment fonctionne l\'effet de serre ?',
      options: [
        { text: 'Le CO₂ piège une partie de la chaleur solaire renvoyée par la Terre', isCorrect: true, feedback: 'Exact.' },
        { text: 'Le CO₂ refroidit l\'atmosphère', isCorrect: false, feedback: 'Inverse.' },
        { text: 'Le CO₂ n\'a aucun effet climatique', isCorrect: false, feedback: 'Faux. Effet documenté depuis 1859.' },
      ],
    },
    {
      id: 'c3-carb-pool-q-meta-climate',
      type: 'QUIZ',
      conceptId: 'climate-greenhouse-gas',
      difficulty: 'hard',
      cognitiveTags: ['metacognition', 'misconception'],
      learningObjective: 'Cause humaine.',
      question: "Le réchauffement actuel est-il un cycle naturel ?",
      options: [
        { text: 'Non, son rythme est ~10× plus rapide. Cause humaine attestée à >99 %', isCorrect: true, feedback: 'Exact. GIEC AR6.' },
        { text: 'Oui, comme avant', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'climate-natural-only' },
        { text: 'On ne sait pas', isCorrect: false, feedback: 'Consensus scientifique très solide.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c3-carb-pool-q-mangrove',
      type: 'QUIZ',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Mangroves.',
      question: 'Pourquoi les mangroves sont-elles si importantes pour le climat ?',
      options: [
        { text: 'Elles stockent jusqu\'à 5× plus de carbone par hectare qu\'une forêt tropicale', isCorrect: true, feedback: 'Exact.' },
        { text: 'Elles produisent l\'oxygène', isCorrect: false, feedback: 'Pas leur fonction principale.' },
        { text: 'Elles servent de plage', isCorrect: false, feedback: 'Décoration sans rapport climatique.' },
      ],
    },
    {
      id: 'c3-carb-pool-d-cycle',
      type: 'DRAG_DROP',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Reconstituer le cycle.',
      instruction: 'Ordonne le cycle :',
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 3,
      items: [
        { id: 'ccc-1', text: '💨 CO₂' },
        { id: 'ccc-2', text: '🌳 Plante' },
        { id: 'ccc-3', text: '🍄 Décomposeur' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Air → plante → décomposeur → air.',
    },
    {
      id: 'c3-carb-pool-d-storage',
      type: 'DRAG_DROP',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les puits.',
      instruction: 'Du moins au plus stockeur :',
      axis: 'horizontal',
      axisRationale: 'Gradient.',
      slotCount: 4,
      items: [
        { id: 'ccs-1', text: '🏜️ Désert' },
        { id: 'ccs-2', text: '🌾 Champ' },
        { id: 'ccs-3', text: '🌳 Forêt tropicale' },
        { id: 'ccs-4', text: '🌿 Tourbière' },
      ],
      correctFeedback: 'Excellent.',
      incorrectFeedback: 'Tourbière = champion.',
    },
    {
      id: 'c3-carb-pool-sw-deforestation',
      type: 'SWIPE',
      conceptId: 'forest-services',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Déforestation = émission.',
      question: 'Vrai ou faux ?',
      card: { title: 'La déforestation cause des émissions massives de CO₂.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. ~10-15 % des émissions mondiales.',
      incorrectFeedback: 'Si. Cause majeure.',
      explanation: 'Préservation > reboisement.',
      interleavesConceptIds: ['ecosystem-flow'],
    },
    {
      id: 'c3-carb-pool-sw-soil-carbon',
      type: 'SWIPE',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Sols stockent.',
      question: 'Vrai ou faux ?',
      card: { title: "Les sols stockent ~3× plus de carbone que l'atmosphère.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si. Sols vivants = puits massif.',
      explanation: 'Initiative 4 pour 1000.',
      interleavesConceptIds: ['soil-living'],
    },
    {
      id: 'c3-carb-pool-q-fossil',
      type: 'QUIZ',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Fossiles.',
      question: 'Pourquoi brûler du pétrole et du charbon dérègle-t-il le climat ?',
      options: [
        { text: 'Ils libèrent en décennies du carbone stocké pendant des millions d\'années', isCorrect: true, feedback: 'Exact. Déséquilibre.' },
        { text: 'Ils créent du CO₂ nouveau', isCorrect: false, feedback: 'Pas nouveau, mais déstocké.' },
        { text: 'Aucun lien climatique', isCorrect: false, feedback: 'Lien massif.' },
      ],
      confidenceCheck: true,
    },
  ],

  authoredLegendary: [
    {
      id: 'c3-carb-leg-1-hook',
      type: 'STORY',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le boss.',
      screens: [
        {
          text: '14 questions pour valider le cycle du carbone et son rôle climatique.',
          imagePrompt: 'Forêt avec courbe de CO₂',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['climatique'],
        },
      ],
    },
    {
      id: 'c3-carb-leg-2-q',
      type: 'QUIZ',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Origine de la masse du bois.',
      question: 'D\'où vient la masse du bois d\'un arbre ?',
      options: [
        { text: 'Du CO₂ de l\'air', isCorrect: true, feedback: 'Exact.' },
        { text: 'Du sol', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'plants-eat-soil' },
        { text: 'De l\'eau', isCorrect: false, feedback: 'Eau passe, ne reste pas.' },
      ],
    },
    {
      id: 'c3-carb-leg-3-q',
      type: 'QUIZ',
      conceptId: 'climate-greenhouse-gas',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Cause climatique humaine.',
      question: 'Le réchauffement climatique actuel a quelle origine ?',
      options: [
        { text: 'Humaine, attestée à >99 %', isCorrect: true, feedback: 'Exact.' },
        { text: 'Naturelle uniquement', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'climate-natural-only' },
        { text: 'Inconnue', isCorrect: false, feedback: 'Consensus solide.' },
      ],
    },
    {
      id: 'c3-carb-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les puits.',
      instruction: 'Du moins au plus stockeur de carbone par ha :',
      axis: 'horizontal',
      axisRationale: 'Gradient.',
      slotCount: 5,
      items: [
        { id: 'ccle-1', text: '🏜️ Désert' },
        { id: 'ccle-2', text: '🌾 Champ' },
        { id: 'ccle-3', text: '🌳 Forêt tempérée' },
        { id: 'ccle-4', text: '🌴 Forêt tropicale' },
        { id: 'ccle-5', text: '🌿 Tourbière' },
        { id: 'ccle-distract', text: '🏙️ Ville', isDistractor: true },
      ],
      correctFeedback: 'Excellent. La ville est un émetteur.',
      incorrectFeedback: 'Indice : un seul item n\'est pas un puits.',
    },
    {
      id: 'c3-carb-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Préserver > planter.',
      question: 'Vrai ou faux ?',
      card: { title: 'Préserver une forêt ancienne est plus efficace climatiquement que reboiser.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Effet immédiat vs effet à 30+ ans.',
      incorrectFeedback: 'Si. Vérifié scientifiquement.',
      explanation: 'Préservation = priorité.',
      misconceptionId: 'planting-trees-fixes-climate',
    },
    {
      id: 'c3-carb-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Vieux arbres.',
      question: 'Vrai ou faux ?',
      card: { title: 'Plus un arbre vieillit, plus il stocke de carbone par an.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si. Stephenson 2014.',
      explanation: 'Croissance absolue augmente.',
      misconceptionId: 'old-trees-stop-absorbing',
    },
    {
      id: 'c3-carb-leg-7-q',
      type: 'QUIZ',
      conceptId: 'climate-greenhouse-gas',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Définition juste.',
      question: 'Comment décrire le rôle climatique du CO₂ ?',
      options: [
        { text: 'Il piège une partie de la chaleur solaire renvoyée. Trop = réchauffement.', isCorrect: true, feedback: 'Exact.' },
        { text: 'Il refroidit la planète', isCorrect: false, feedback: 'Inverse.' },
        { text: 'Il est sans effet', isCorrect: false, feedback: 'Faux.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c3-carb-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Cycle complet + entrelacement.',
      instruction: 'Ordonne le cycle complet :',
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 4,
      items: [
        { id: 'ccli-1', text: '💨 CO₂ atmosphérique' },
        { id: 'ccli-2', text: '🌳 Plante (photosynthèse)' },
        { id: 'ccli-3', text: '🐇 Animal' },
        { id: 'ccli-4', text: '🍄 Décomposeur' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Air → plante → animal → décomposeur.',
      interleavesConceptIds: ['photosynthesis-mechanism', 'decomposers-role'],
    },
    {
      id: 'c3-carb-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint océan.',
      question: 'Vrai ou faux ?',
      card: { title: 'L\'océan absorbe ~25 % des émissions humaines de CO₂.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Acidification.',
    },
    {
      id: 'c3-carb-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'forest-services',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'interleaved'],
      learningObjective: 'Sprint déforestation.',
      question: 'Vrai ou faux ?',
      card: { title: 'La déforestation contribue significativement aux émissions de CO₂ mondiales.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. ~10-15 %.',
      incorrectFeedback: 'Si.',
      explanation: 'Sans forêt, on émet et on perd un puits.',
      interleavesConceptIds: ['ecosystem-flow'],
    },
    {
      id: 'c3-carb-leg-11-q',
      type: 'QUIZ',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthétiser : équilibre.',
      question: "Pourquoi le carbone est-il un thermostat planétaire ?",
      options: [
        { text: 'Son équilibre dans l\'atmosphère règle la température', isCorrect: true, feedback: 'Exact.' },
        { text: 'Il refroidit toujours', isCorrect: false, feedback: 'Inverse.' },
        { text: 'Aucun rôle', isCorrect: false, feedback: 'Faux.' },
      ],
    },
    {
      id: 'c3-carb-leg-12-reveal',
      type: 'STORY',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective.',
      screens: [
        {
          text: 'Le carbone est partout : ton corps, le bois, l\'air, les océans. Son équilibre est ce qui rend la Terre habitable.',
          imagePrompt: 'Vue Terre avec atomes de carbone',
          imageUrl: REEF_IMAGE,
          kind: 'reveal',
          boldTokens: ['équilibre'],
        },
      ],
    },
    {
      id: 'c3-carb-leg-13-q',
      type: 'QUIZ',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Action.',
      question: 'Quelle action préserve le mieux les puits de carbone ?',
      options: [
        { text: 'Préserver forêts anciennes + sols vivants + zones humides', isCorrect: true, feedback: 'Exact.' },
        { text: 'Brûler du charbon', isCorrect: false, feedback: 'Émet.' },
        { text: 'Bétonner les zones humides', isCorrect: false, feedback: 'Détruit le puits.' },
      ],
    },
    {
      id: 'c3-carb-leg-14-closure',
      type: 'STORY',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer le Chap 4.',
      screens: [
        {
          text: 'Tu connais les grands cycles. Au Chap 4 : les sanctuaires sauvages, écosystèmes uniques et fragiles.',
          imagePrompt: 'Île tropicale avec biodiversité',
          imageUrl: REEF_IMAGE,
          kind: 'closure',
          boldTokens: ['sanctuaires'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'c3-carb-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir le cycle du carbone.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'c3-carb-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser le carbone.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'c3-carb-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler le carbone dans des cas pièges.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 3 },
    },
    {
      id: 'c3-carb-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise du carbone.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 35, label: '35 Graines' },
    },
  ],
}
