import type { AcademyUnitDefinition } from '../../../schema'

const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const SPROUT_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'
const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'

export const pollinationUnit: AcademyUnitDefinition = {
  id: 'unit-3-1',
  slug: 'les-coursiers-du-nectar',
  chapterId: 'chapter-3',
  schemaVersion: 2,
  title: 'Les Coursiers du Nectar',
  shortTitle: 'Pollinisation',
  pathLabel: 'Coursiers',
  subtitle: "Comment l'amour des fleurs nourrit la planète.",
  concept: 'Pollinisation, fleurs, insectes, reproduction',
  conceptIds: ['pollination-agents', 'biodiversity-services', 'pest-regulation'],
  kind: 'fauna',
  iconKey: 'flower',
  masteryGoal: "Comprendre la pollinisation comme service écosystémique vital.",
  order: 1,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: "Voir la pollinisation comme un mutualisme massif et fragile.",
  mascot: 'abeille-transparente',
  rewardAmount: 30,

  authoredDiscovery: [
    {
      id: 'c3-poll-disc-1-hook',
      type: 'STORY',
      conceptId: 'pollination-agents',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : sans abeilles, plus de chocolat.',
      screens: [
        {
          text: "Sans pollinisateurs, ~1/3 de notre alimentation disparaîtrait. Plus de fraises, plus de pommes, plus de café, plus de chocolat.",
          imagePrompt: 'Étalage de fruits colorés',
          imageUrl: FIELD_IMAGE,
          kind: 'hook',
          boldTokens: ['1/3'],
        },
      ],
    },
    {
      id: 'c3-poll-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'pollination-agents',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester l\'idée que seules les abeilles pollinisent.',
      question: 'Vrai ou faux ?',
      card: { title: 'Seules les abeilles pollinisent les fleurs.', subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bien vu. Papillons, mouches, coléoptères, oiseaux, chauves-souris, vent... tous pollinisent.',
      incorrectFeedback: 'Faux. Les pollinisateurs sont très divers.',
      explanation: 'Diversité des pollinisateurs = résilience.',
      misconceptionId: 'only-bees-pollinate',
    },
    {
      id: 'c3-poll-disc-3-reveal',
      type: 'STORY',
      conceptId: 'pollination-agents',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler le mutualisme fleur-pollinisateur.',
      screens: [
        {
          text: "La fleur offre du nectar (sucre). En échange, l'insecte transporte du pollen d'une fleur à l'autre. Mutualisme parfait.",
          imagePrompt: 'Abeille couverte de pollen sur fleur',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['mutualisme'],
        },
        {
          text: "Sans cet échange, la fleur ne se reproduit pas. L'insecte ne mange pas. Tout l'écosystème tient sur ce pacte.",
          imagePrompt: 'Champ de fleurs avec abeilles',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['pacte'],
        },
      ],
    },
    {
      id: 'c3-poll-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: ['generation', 'misconception'],
      learningObjective: 'Identifier la diversité des pollinisateurs.',
      question: 'Qui pollinise les fleurs dans la nature ?',
      options: [
        { text: 'Insectes, oiseaux, chauves-souris ET le vent', isCorrect: true, feedback: 'Exact. Diversité massive.' },
        { text: 'Seulement les abeilles', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'only-bees-pollinate' },
        { text: 'Aucun être vivant', isCorrect: false, feedback: 'Faux. Les pollinisateurs sont essentiels.' },
      ],
      hint: 'Pense au-delà des abeilles : qui d\'autre visite les fleurs ?',
    },
    {
      id: 'c3-poll-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'pest-regulation',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir l\'idée que les guêpes sont inutiles.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les guêpes ne servent à rien.', subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Elles régulent les insectes ravageurs et pollinisent secondairement.',
      incorrectFeedback: 'Faux. Sans elles, explosion de ravageurs.',
      explanation: 'Brock et al. 2021 : services écosystémiques des guêpes documentés.',
      misconceptionId: 'wasps-are-useless',
    },
    {
      id: 'c3-poll-disc-6-build',
      type: 'STORY',
      conceptId: 'biodiversity-services',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Introduire les services écosystémiques.',
      screens: [
        {
          text: "Les pollinisateurs nous offrent un 'service' évalué à plus de 200 milliards de $ par an. Et ils le font gratuitement.",
          imagePrompt: 'Champ avec abeille au travail',
          imageUrl: FIELD_IMAGE,
          kind: 'build-up',
          boldTokens: ['gratuitement'],
        },
      ],
    },
    {
      id: 'c3-poll-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Reconstituer le processus de pollinisation.',
      instruction: 'Ordonne les étapes :',
      axis: 'horizontal',
      axisRationale: 'Chronologie du processus.',
      slotCount: 3,
      items: [
        { id: 'cpo-1', text: '🐝 Abeille boit nectar' },
        { id: 'cpo-2', text: '🟡 Pollen colle à ses poils' },
        { id: 'cpo-3', text: '🌸 Féconde une autre fleur' },
      ],
      correctFeedback: 'Parfait. Mutualisme inconscient.',
      incorrectFeedback: 'Indice : nectar attire, pollen voyage.',
    },
    {
      id: 'c3-poll-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'pollination-agents',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : importance alimentaire.',
      question: 'Vrai ou faux ?',
      card: { title: "Sans pollinisateurs, on perdrait ~1/3 de notre alimentation.", subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Estimation FAO documentée.',
      incorrectFeedback: 'Si. Adieu fruits, légumes, café, chocolat.',
      explanation: 'Source FAO + IPBES.',
    },
    {
      id: 'c3-poll-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : pollinisateurs nocturnes.',
      question: 'Vrai ou faux ?',
      card: { title: "Certaines chauves-souris pollinisent des fleurs la nuit.", subtitle: 'Sprint 2' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Cactus, agave, banane sauvage : pollinisés par chauves-souris.',
      incorrectFeedback: 'Si. Pollinisateurs nocturnes existent.',
      explanation: 'Tequila → agave → chauve-souris.',
    },
    {
      id: 'c3-poll-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'pollination-agents',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: 'Identifier le pollinisateur principal en agriculture.',
      question: "Quel pollinisateur a le plus d'impact agricole mondial ?",
      options: [
        { text: 'L\'abeille domestique (Apis mellifera)', isCorrect: true, feedback: 'Exact. Pollinisation massive de cultures.' },
        { text: 'Le vent uniquement', isCorrect: false, feedback: 'Vrai pour céréales, mais limité.' },
        { text: 'Les souris', isCorrect: false, feedback: 'Aucune souris ne pollinise.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c3-poll-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les pollinisateurs par contribution.',
      instruction: 'Du plus commun au plus inattendu :',
      axis: 'horizontal',
      axisRationale: 'Gradient de fréquence.',
      slotCount: 4,
      items: [
        { id: 'cpb-1', text: '🐝 Abeille (n°1)' },
        { id: 'cpb-2', text: '🦋 Papillon' },
        { id: 'cpb-3', text: '🦇 Chauve-souris' },
        { id: 'cpb-4', text: '🦎 Lézard (rare)' },
        { id: 'cpb-distract', text: '🐺 Loup', isDistractor: true },
      ],
      correctFeedback: 'Excellent. Le loup ne pollinise pas.',
      incorrectFeedback: 'Indice : un seul ne pollinise pas du tout.',
    },
    {
      id: 'c3-poll-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'biodiversity-services',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser : protéger les pollinisateurs.',
      question: 'Pourquoi protéger les pollinisateurs ?',
      options: [
        { text: 'Parce qu\'ils sécurisent ~1/3 de notre alimentation', isCorrect: true, feedback: 'Exact. Service vital et gratuit.' },
        { text: 'Parce qu\'ils sont jolis', isCorrect: false, feedback: 'Esthétique seul ne suffit pas.' },
        { text: 'Parce qu\'ils sont nuisibles', isCorrect: false, feedback: 'Inverse.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c3-poll-pool-sw-decline',
      type: 'SWIPE',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Déclin des abeilles.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les pesticides néonicotinoïdes déciment les colonies d\'abeilles.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Effet documenté, conduisant à interdictions UE.',
      incorrectFeedback: 'Si. Cause majeure du déclin.',
      explanation: 'Néonicotinoïdes désorientent les abeilles.',
    },
    {
      id: 'c3-poll-pool-sw-wind',
      type: 'SWIPE',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Pollinisation par le vent.',
      question: 'Vrai ou faux ?',
      card: { title: 'Le vent peut polliniser certaines plantes.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Céréales, conifères, graminées.',
      incorrectFeedback: 'Si. Anémophilie = pollinisation éolienne.',
      explanation: 'Plantes à fleurs discrètes = souvent éoliennes.',
    },
    {
      id: 'c3-poll-pool-sw-coevolve',
      type: 'SWIPE',
      conceptId: 'pollination-agents',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Coévolution fleur-insecte.',
      question: 'Vrai ou faux ?',
      card: { title: "Certaines fleurs ont une forme parfaitement adaptée à leur pollinisateur unique.", subtitle: 'Coévolution' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Orchidée de Darwin / papillon à trompe géante.',
      incorrectFeedback: 'Si. Coévolution sur des millions d\'années.',
      explanation: 'Spécialisation fleur ↔ pollinisateur.',
      interleavesConceptIds: ['symbiosis-types'],
    },
    {
      id: 'c3-poll-pool-sw-diverse',
      type: 'SWIPE',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Diversité des pollinisateurs.',
      question: 'Vrai ou faux ?',
      card: { title: "La pollinisation repose uniquement sur l'abeille domestique.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Abeilles sauvages, mouches, papillons aussi cruciaux.',
      incorrectFeedback: 'Faux. Diversité = résilience.',
      explanation: 'Réduire à l\'abeille domestique = vulnérabilité.',
      misconceptionId: 'only-bees-pollinate',
    },
    {
      id: 'c3-poll-pool-q-ipbes',
      type: 'QUIZ',
      conceptId: 'biodiversity-services',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Valeur économique de la pollinisation.',
      question: 'Quelle est la valeur économique mondiale annuelle de la pollinisation ?',
      options: [
        { text: 'Environ 200 milliards de $', isCorrect: true, feedback: 'Exact. IPBES 2016.' },
        { text: 'Quelques millions', isCorrect: false, feedback: 'Très sous-estimé.' },
        { text: 'Aucune valeur économique', isCorrect: false, feedback: 'Faux. Service indispensable.' },
      ],
    },
    {
      id: 'c3-poll-pool-q-loss-impact',
      type: 'QUIZ',
      conceptId: 'biodiversity-services',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Conséquence d\'une disparition.',
      question: "Si tous les pollinisateurs disparaissaient demain, quel serait l'effet ?",
      options: [
        { text: 'Effondrement de ~1/3 des cultures alimentaires mondiales', isCorrect: true, feedback: 'Exact.' },
        { text: 'Aucun effet visible', isCorrect: false, feedback: 'Faux. Effet immédiat et massif.' },
        { text: 'Plus de fleurs partout', isCorrect: false, feedback: 'Inverse. Sans pollinisation, pas de reproduction.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c3-poll-pool-q-types',
      type: 'QUIZ',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Catégoriser les pollinisateurs.',
      question: 'Qui n\'est PAS un pollinisateur ?',
      options: [
        { text: 'Le requin', isCorrect: true, feedback: 'Exact. Pas de fleurs sous l\'eau profonde.' },
        { text: "L'abeille", isCorrect: false, feedback: 'Pollinisateur n°1.' },
        { text: 'Le papillon', isCorrect: false, feedback: 'Pollinisateur classique.' },
      ],
    },
    {
      id: 'c3-poll-pool-d-process',
      type: 'DRAG_DROP',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Reconstituer le processus.',
      instruction: 'Ordonne les étapes de la pollinisation :',
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 3,
      items: [
        { id: 'cppr-1', text: '🌸 Fleur produit nectar' },
        { id: 'cppr-2', text: '🐝 Visiteur transporte pollen' },
        { id: 'cppr-3', text: '🍓 Fruit se forme' },
      ],
      correctFeedback: 'Parfait. Du nectar au fruit.',
      incorrectFeedback: 'Indice : nectar attire, pollen voyage, fruit naît.',
    },
    {
      id: 'c3-poll-pool-d-pollinators',
      type: 'DRAG_DROP',
      conceptId: 'pollination-agents',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser par fréquence.',
      instruction: 'Du plus fréquent au plus rare :',
      axis: 'horizontal',
      axisRationale: 'Gradient de fréquence.',
      slotCount: 4,
      items: [
        { id: 'cpop-1', text: '🐝 Abeilles' },
        { id: 'cpop-2', text: '🦋 Papillons' },
        { id: 'cpop-3', text: '🦇 Chauves-souris' },
        { id: 'cpop-4', text: '🦎 Lézards' },
      ],
      correctFeedback: 'Excellent. Abeilles dominent, lézards rarissimes.',
      incorrectFeedback: 'Indice : abeilles partout, lézards exceptions.',
    },
    {
      id: 'c3-poll-pool-sw-monoculture',
      type: 'SWIPE',
      conceptId: 'biodiversity-services',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Monoculture et pollinisateurs.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les monocultures réduisent la diversité des pollinisateurs.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Une seule fleur = une seule période = appauvrissement.',
      incorrectFeedback: 'Si. Cas documenté.',
      explanation: 'Diversité florale = diversité d\'insectes.',
    },
    {
      id: 'c3-poll-pool-sw-buzz',
      type: 'SWIPE',
      conceptId: 'pollination-agents',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Pollinisation par vibration.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les bourdons font vibrer les fleurs pour libérer le pollen.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. C\'est la « buzz pollination » (tomate, myrtille).',
      incorrectFeedback: 'Si. Technique unique aux bourdons.',
      explanation: 'Sans bourdons, pas de tomates en serre.',
    },
    {
      id: 'c3-poll-pool-q-bee-decline-cause',
      type: 'QUIZ',
      conceptId: 'pollination-agents',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Causes du déclin.',
      question: 'Quelles sont les principales causes du déclin des abeilles ?',
      options: [
        { text: 'Pesticides + perte d\'habitat + maladies + monoculture', isCorrect: true, feedback: 'Exact. Combinaison de facteurs.' },
        { text: 'Uniquement les pesticides', isCorrect: false, feedback: 'Important mais pas seul.' },
        { text: 'Les ondes téléphoniques', isCorrect: false, feedback: 'Hypothèse non confirmée scientifiquement.' },
      ],
    },
  ],

  authoredLegendary: [
    {
      id: 'c3-poll-leg-1-hook',
      type: 'STORY',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le boss.',
      screens: [
        {
          text: '14 questions pour valider la pollinisation comme service écosystémique vital.',
          imagePrompt: 'Champ de fleurs avec multitude d\'insectes',
          imageUrl: FIELD_IMAGE,
          kind: 'hook',
          boldTokens: ['vital'],
        },
      ],
    },
    {
      id: 'c3-poll-leg-2-q',
      type: 'QUIZ',
      conceptId: 'pollination-agents',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Diversité des pollinisateurs.',
      question: 'Quels êtres pollinisent ?',
      options: [
        { text: 'Insectes, oiseaux, chauves-souris, vent', isCorrect: true, feedback: 'Exact.' },
        { text: 'Seulement les abeilles', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'only-bees-pollinate' },
        { text: 'Seulement le vent', isCorrect: false, feedback: 'Insuffisant.' },
      ],
    },
    {
      id: 'c3-poll-leg-3-q',
      type: 'QUIZ',
      conceptId: 'biodiversity-services',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Importance économique.',
      question: 'Combien de notre alimentation dépend des pollinisateurs ?',
      options: [
        { text: '~1/3', isCorrect: true, feedback: 'Exact.' },
        { text: '0%', isCorrect: false, feedback: 'Énorme erreur.' },
        { text: '100%', isCorrect: false, feedback: 'Trop. Céréales pollinisées par le vent.' },
      ],
    },
    {
      id: 'c3-poll-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'pollination-agents',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Reconstituer le mutualisme complet.',
      instruction: 'Ordonne le cycle complet :',
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 5,
      items: [
        { id: 'cpl4-1', text: '🌸 Fleur s\'ouvre' },
        { id: 'cpl4-2', text: '🐝 Insecte attiré' },
        { id: 'cpl4-3', text: '🟡 Pollen colle' },
        { id: 'cpl4-4', text: '🌸 Autre fleur fécondée' },
        { id: 'cpl4-5', text: '🍓 Fruit produit' },
        { id: 'cpl4-distract', text: '☢️ Pesticide', isDistractor: true },
      ],
      correctFeedback: 'Excellent. Le pesticide ne fait pas partie du cycle naturel.',
      incorrectFeedback: 'Indice : un item est anti-cycle.',
    },
    {
      id: 'c3-poll-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'pest-regulation',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Sprint guêpes utiles.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les guêpes contribuent à la régulation des ravageurs.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Prédatrices de chenilles et mouches.',
      incorrectFeedback: 'Si. Sans elles, plus de ravageurs.',
      explanation: 'Brock 2021.',
      misconceptionId: 'wasps-are-useless',
    },
    {
      id: 'c3-poll-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Sprint pesticides.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les pesticides néonicotinoïdes affectent les abeilles.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Désorientation, baisse de fécondité.',
      incorrectFeedback: 'Si. Effet documenté.',
      explanation: 'Interdiction UE 2018-2020.',
    },
    {
      id: 'c3-poll-leg-7-q',
      type: 'QUIZ',
      conceptId: 'pollination-agents',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Choisir la formulation juste.',
      question: 'Comment décrire la pollinisation ?',
      options: [
        { text: 'Mutualisme entre fleurs et pollinisateurs (nectar contre transport de pollen)', isCorrect: true, feedback: 'Exact.' },
        { text: 'Service unilatéral des abeilles', isCorrect: false, feedback: 'Mutualisme = bilatéral.' },
        { text: 'Commensalisme', isCorrect: false, feedback: 'Faux. Les deux gagnent.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c3-poll-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'pollination-agents',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Symbiose + pollinisation.',
      instruction: 'Place ces relations :',
      axis: 'horizontal',
      axisRationale: 'Gradient de bénéfice mutuel.',
      slotCount: 3,
      items: [
        { id: 'cple-1', text: '🐝 Abeille + 🌸 fleur (mutualisme)' },
        { id: 'cple-2', text: '🦅 Aigle + branche (commensalisme)' },
        { id: 'cple-3', text: '🦟 Moustique + humain (parasitisme)' },
      ],
      correctFeedback: 'Parfait. Trois types de symbiose.',
      incorrectFeedback: 'Indice : qui gagne, qui ne perd rien, qui perd.',
      interleavesConceptIds: ['symbiosis-types'],
    },
    {
      id: 'c3-poll-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'pollination-agents',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint diversité.',
      question: 'Vrai ou faux ?',
      card: { title: 'La diversité des pollinisateurs renforce la résilience des cultures.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Si une espèce baisse, les autres compensent.',
      incorrectFeedback: 'Si. Diversité = assurance.',
      explanation: 'Redondance fonctionnelle.',
    },
    {
      id: 'c3-poll-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'biodiversity-services',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint impact.',
      question: 'Vrai ou faux ?',
      card: { title: 'Sans pollinisateurs, ~1/3 de notre alimentation s\'effondrerait.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Documenté.',
      incorrectFeedback: 'Si. Source FAO/IPBES.',
      explanation: 'Vital.',
    },
    {
      id: 'c3-poll-leg-11-q',
      type: 'QUIZ',
      conceptId: 'biodiversity-services',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthétiser : services écosystémiques.',
      question: 'Qu\'appelle-t-on un « service écosystémique » ?',
      options: [
        { text: 'Un bénéfice gratuit que la nature rend à l\'humanité', isCorrect: true, feedback: 'Exact. Pollinisation = exemple-clé.' },
        { text: 'Un service payant', isCorrect: false, feedback: 'Inverse. Gratuit.' },
        { text: 'Une invention humaine', isCorrect: false, feedback: 'Naturel, pas inventé.' },
      ],
    },
    {
      id: 'c3-poll-leg-12-reveal',
      type: 'STORY',
      conceptId: 'biodiversity-services',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective.',
      screens: [
        {
          text: 'Chaque fruit que tu manges a probablement été touché par un insecte. Sa survie est aussi la tienne.',
          imagePrompt: 'Pomme avec abeille en arrière-plan',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['touché'],
        },
      ],
    },
    {
      id: 'c3-poll-leg-13-q',
      type: 'QUIZ',
      conceptId: 'biodiversity-services',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Action concrète.',
      question: 'Quelle action protège les pollinisateurs ?',
      options: [
        { text: 'Fleurs sauvages + zéro pesticide + diversité de plantes', isCorrect: true, feedback: 'Exact. Triple action efficace.' },
        { text: 'Bétonner les jardins', isCorrect: false, feedback: 'Tue tout pollinisateur.' },
        { text: 'Stériliser le sol', isCorrect: false, feedback: 'Détruit les habitats.', misconceptionId: 'dead-soil-is-clean' },
      ],
    },
    {
      id: 'c3-poll-leg-14-closure',
      type: 'STORY',
      conceptId: 'biodiversity-services',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer la transition vers Cycle de l\'Eau.',
      screens: [
        {
          text: "Tu connais l'économie florale. Place à un autre cycle vital : l'éternel voyage de l'eau, vu en plus profond.",
          imagePrompt: "Goutte d'eau qui devient pluie",
          imageUrl: SPROUT_IMAGE,
          kind: 'closure',
          boldTokens: ['voyage'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'c3-poll-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir le mutualisme fleur-pollinisateur.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'c3-poll-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser la pollinisation.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'c3-poll-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler la pollinisation dans des cas pièges.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 3 },
    },
    {
      id: 'c3-poll-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise de la pollinisation.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 30, label: '30 Graines' },
    },
  ],
}
