import type { AcademyUnitDefinition } from '../../../schema'

const WATER_IMAGE =
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1000&auto=format&fit=crop'
const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'

export const waterCycleDeepUnit: AcademyUnitDefinition = {
  id: 'unit-3-2',
  slug: 'leternel-voyage-bleu',
  chapterId: 'chapter-3',
  schemaVersion: 2,
  title: "L'Éternel Voyage Bleu",
  shortTitle: 'Cycle eau',
  pathLabel: 'Voyage bleu',
  subtitle: "Plonge dans la circulation infinie de l'eau planétaire.",
  concept: 'Cycle de l\'eau planétaire, glaciers, nappes',
  conceptIds: ['water-cycle-evaporation', 'forest-water-cycle', 'water-cycle-infiltration'],
  kind: 'flora',
  iconKey: 'water',
  masteryGoal: "Comprendre le cycle de l'eau à l'échelle planétaire et ses enjeux climatiques.",
  order: 2,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: "Voir l'eau comme un transporteur planétaire avec des réservoirs lents (glaciers, nappes) et rapides (rivières, atmosphère).",
  mascot: 'ondine',
  rewardAmount: 30,

  authoredDiscovery: [
    {
      id: 'c3-wat-disc-1-hook',
      type: 'STORY',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : la même eau depuis 4 milliards d\'années.',
      screens: [
        {
          text: "L'eau ne se crée jamais. Elle voyage. Une goutte de pluie aujourd'hui était peut-être glacier au Groenland il y a 10 000 ans.",
          imagePrompt: 'Goutte avec scènes en surimpression',
          imageUrl: WATER_IMAGE,
          kind: 'hook',
          boldTokens: ['voyage'],
        },
      ],
    },
    {
      id: 'c3-wat-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['pre-test'],
      learningObjective: 'Tester l\'idée que l\'eau circule rapide partout.',
      question: 'Vrai ou faux ?',
      card: { title: "Toute l'eau de la Terre se renouvelle en quelques jours.", subtitle: 'Intuition' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bien vu. Atmosphère = quelques jours, mais nappes profondes = des milliers d\'années.',
      incorrectFeedback: 'Faux. Réservoirs lents existent.',
      explanation: 'Eaux fossiles = millénaires.',
    },
    {
      id: 'c3-wat-disc-3-reveal',
      type: 'STORY',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler les réservoirs lents et rapides.',
      screens: [
        {
          text: 'Réservoirs RAPIDES : atmosphère (~9 jours), rivières (~2 semaines). Réservoirs LENTS : glaciers (~9000 ans), nappes profondes (~10000 ans).',
          imagePrompt: 'Schéma des réservoirs d\'eau',
          imageUrl: WATER_IMAGE,
          kind: 'reveal',
          boldTokens: ['réservoirs'],
        },
        {
          text: "L'eau circule entre tous, mais à des vitesses très différentes. C'est pourquoi vider une nappe est presque irréversible.",
          imagePrompt: 'Cycle de l\'eau avec différentes vitesses',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['irréversible'],
        },
      ],
    },
    {
      id: 'c3-wat-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Identifier le moteur du cycle.',
      question: "Quel est le moteur du cycle de l'eau planétaire ?",
      options: [
        { text: 'La chaleur du Soleil', isCorrect: true, feedback: 'Exact. Sans Soleil, pas d\'évaporation.' },
        { text: 'La gravité de la Lune', isCorrect: false, feedback: 'Marées seulement, pas le cycle.' },
        { text: 'Les volcans', isCorrect: false, feedback: 'Marginaux dans le cycle.' },
      ],
      hint: 'Vu au chap 1.',
    },
    {
      id: 'c3-wat-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'forest-water-cycle',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir l\'idée que la pluie vient juste de l\'océan.',
      question: 'Vrai ou faux ?',
      card: { title: "Les forêts génèrent leurs propres pluies par transpiration.", subtitle: 'Climat' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Amazonie produit ~50 % de sa pluie.',
      incorrectFeedback: 'Si. Évapotranspiration documentée.',
      explanation: 'Salati et al. 1979.',
      misconceptionId: 'rain-comes-from-clouds-only',
    },
    {
      id: 'c3-wat-disc-6-build',
      type: 'STORY',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Introduire les nappes phréatiques.',
      screens: [
        {
          text: "Sous tes pieds : des réservoirs souterrains (nappes phréatiques) qui alimentent rivières, sources, et notre eau potable.",
          imagePrompt: 'Coupe géologique montrant nappe',
          imageUrl: FIELD_IMAGE,
          kind: 'build-up',
          boldTokens: ['nappes'],
        },
      ],
    },
    {
      id: 'c3-wat-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: "Reconstituer le cycle complet de l'eau.",
      instruction: 'Ordonne le voyage d\'une goutte :',
      axis: 'horizontal',
      axisRationale: 'Chronologie du cycle.',
      slotCount: 4,
      items: [
        { id: 'cwd-1', text: '🌊 Évaporation océan' },
        { id: 'cwd-2', text: '☁️ Nuage' },
        { id: 'cwd-3', text: '🌧️ Pluie' },
        { id: 'cwd-4', text: '🏞️ Retour à la mer' },
      ],
      correctFeedback: 'Parfait. Cycle complet acquis.',
      incorrectFeedback: 'Indice : océan-ciel-terre-océan.',
    },
    {
      id: 'c3-wat-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : eau jamais détruite.',
      question: 'Vrai ou faux ?',
      card: { title: "L'eau de la Terre ne se crée ni ne se détruit, elle voyage.", subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Conservation de la matière.',
      incorrectFeedback: 'Si. La même eau circule depuis 4 Ga.',
      explanation: 'Conservation appliquée à l\'eau.',
    },
    {
      id: 'c3-wat-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : nappes lentes.',
      question: 'Vrai ou faux ?',
      card: { title: 'Une nappe phréatique vidée se reconstitue en quelques heures.', subtitle: 'Sprint 2' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Des décennies à des millénaires.',
      incorrectFeedback: 'Non. Très lent.',
      explanation: 'Eaux fossiles = irréversibles humainement.',
    },
    {
      id: 'c3-wat-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: ['metacognition', 'misconception'],
      learningObjective: "Identifier l'enjeu des glaciers.",
      question: 'Pourquoi la fonte des glaciers inquiète ?',
      options: [
        { text: "Parce qu'ils stockent l'eau douce qui alimente milliards de personnes", isCorrect: true, feedback: 'Exact. Glaciers = château d\'eau de l\'Asie, des Andes, etc.' },
        { text: 'Parce que l\'eau fondue est polluée', isCorrect: false, feedback: 'Faux. Le problème est la perte du stock.' },
        { text: 'Parce que les ours polaires aiment la glace', isCorrect: false, feedback: 'Conséquence secondaire.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c3-wat-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les vitesses de cycle.',
      instruction: 'Du plus rapide au plus lent :',
      axis: 'horizontal',
      axisRationale: 'Gradient de vitesse.',
      slotCount: 4,
      items: [
        { id: 'cwb-1', text: '☁️ Atmosphère (~9j)' },
        { id: 'cwb-2', text: '🏞️ Rivière (~2 sem)' },
        { id: 'cwb-3', text: '❄️ Glacier (~9000 ans)' },
        { id: 'cwb-4', text: '⛏️ Nappe profonde (~10000 ans)' },
      ],
      correctFeedback: 'Excellent. Vitesses très contrastées.',
      incorrectFeedback: 'Atmosphère = rapide, nappe = très lente.',
    },
    {
      id: 'c3-wat-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser : eau planétaire.',
      question: "Quelle vision du cycle de l'eau est la plus juste ?",
      options: [
        { text: 'Un voyage permanent entre réservoirs aux vitesses très différentes', isCorrect: true, feedback: 'Exact.' },
        { text: 'Un cycle uniforme partout', isCorrect: false, feedback: 'Trop simple.' },
        { text: "L'eau qui se crée à chaque pluie", isCorrect: false, feedback: 'Faux. Aucune création.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c3-wat-pool-sw-evapotranspiration',
      type: 'SWIPE',
      conceptId: 'forest-water-cycle',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Évapotranspiration.',
      question: 'Vrai ou faux ?',
      card: { title: "Un grand chêne peut relâcher jusqu'à 400 litres de vapeur par jour.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Évapotranspiration foliaire.',
      incorrectFeedback: 'Si. Mécanisme massif.',
      explanation: 'Forêt = pompe à eau aérienne.',
    },
    {
      id: 'c3-wat-pool-sw-deforest',
      type: 'SWIPE',
      conceptId: 'forest-water-cycle',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Déforestation et climat local.',
      question: 'Vrai ou faux ?',
      card: { title: 'La déforestation assèche le climat local.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Sans transpiration, moins de pluies.',
      incorrectFeedback: 'Si. Effet documenté en Amazonie, Bornéo.',
      explanation: 'Salati, Lawrence et al.',
      misconceptionId: 'rain-comes-from-clouds-only',
    },
    {
      id: 'c3-wat-pool-sw-glaciers',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Glaciers réservoirs.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les glaciers fournissent de l\'eau potable à des milliards de personnes.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. ~2 milliards de personnes (Asie, Andes).',
      incorrectFeedback: 'Si. Châteaux d\'eau.',
      explanation: 'GIEC AR6.',
    },
    {
      id: 'c3-wat-pool-sw-aquifers',
      type: 'SWIPE',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Eaux fossiles.',
      question: 'Vrai ou faux ?',
      card: { title: 'Certaines nappes contiennent de l\'eau vieille de 10 000 ans.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Eaux fossiles.',
      incorrectFeedback: 'Si. Datation par isotopes.',
      explanation: 'Si on les pompe, on ne les renouvelle pas.',
    },
    {
      id: 'c3-wat-pool-q-amazon',
      type: 'QUIZ',
      conceptId: 'forest-water-cycle',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Pompe à eau Amazonie.',
      question: 'Pourquoi l\'Amazonie influence-t-elle les pluies en Argentine ?',
      options: [
        { text: 'Elle relâche d\'énormes quantités de vapeur transportées par les vents', isCorrect: true, feedback: 'Exact. « Rivières volantes ».' },
        { text: 'Elle envoie des fleuves liquides en surface', isCorrect: false, feedback: 'Pas par surface, par atmosphère.' },
        { text: 'Aucun lien', isCorrect: false, feedback: 'Faux. Lien documenté.' },
      ],
    },
    {
      id: 'c3-wat-pool-q-meta-cycle',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Définir le cycle.',
      question: 'Comment décrire le cycle de l\'eau ?',
      options: [
        { text: 'Voyage permanent entre réservoirs aux vitesses différentes', isCorrect: true, feedback: 'Exact.' },
        { text: 'Création continue d\'eau nouvelle', isCorrect: false, feedback: 'Faux.' },
        { text: 'Évaporation seule', isCorrect: false, feedback: 'Trop limité.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c3-wat-pool-q-dist',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Distillation naturelle.',
      question: 'Pourquoi la pluie est-elle douce alors qu\'elle vient des océans salés ?',
      options: [
        { text: 'L\'évaporation laisse le sel derrière', isCorrect: true, feedback: 'Exact. Distillation naturelle.' },
        { text: 'Le ciel filtre le sel', isCorrect: false, feedback: 'Pas de filtre.' },
        { text: 'Tout vient des nappes', isCorrect: false, feedback: 'Pas le mécanisme.' },
      ],
    },
    {
      id: 'c3-wat-pool-d-states',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'États de l\'eau.',
      instruction: 'Du chaud au froid :',
      axis: 'horizontal',
      axisRationale: 'Gradient thermique.',
      slotCount: 3,
      items: [
        { id: 'cwst-1', text: '💨 Vapeur' },
        { id: 'cwst-2', text: '💧 Liquide' },
        { id: 'cwst-3', text: '❄️ Glace' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Vapeur chaud, glace froid.',
    },
    {
      id: 'c3-wat-pool-d-reservoirs',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les vitesses.',
      instruction: 'Du renouvellement le plus rapide au plus lent :',
      axis: 'horizontal',
      axisRationale: 'Gradient de vitesse.',
      slotCount: 4,
      items: [
        { id: 'cwres-1', text: '☁️ Atmosphère' },
        { id: 'cwres-2', text: '🏞️ Rivière' },
        { id: 'cwres-3', text: '❄️ Glacier' },
        { id: 'cwres-4', text: '⛏️ Nappe profonde' },
      ],
      correctFeedback: 'Excellent.',
      incorrectFeedback: 'Atmosphère = rapide, nappe = très lente.',
    },
    {
      id: 'c3-wat-pool-sw-melt',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Fonte = niveau marin.',
      question: 'Vrai ou faux ?',
      card: { title: "La fonte des glaciers continentaux fait monter le niveau des océans.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Glace continentale → mer.',
      incorrectFeedback: 'Si. Documenté GIEC.',
      explanation: 'Glace de mer = effet neutre. Glace continentale = effet net.',
    },
    {
      id: 'c3-wat-pool-sw-soil-water',
      type: 'SWIPE',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'medium',
      cognitiveTags: ['interleaved', 'misconception'],
      learningObjective: 'Sol vivant + eau.',
      question: 'Vrai ou faux ?',
      card: { title: 'Un sol vivant est meilleur qu\'un sol bétonné pour absorber l\'eau de pluie.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. ~20× plus.',
      incorrectFeedback: 'Si. Vu au chap 1.',
      explanation: 'Sol vivant = éponge.',
      misconceptionId: 'concrete-helps-drainage',
      interleavesConceptIds: ['soil-living'],
    },
    {
      id: 'c3-wat-pool-q-pure',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Distillation.',
      question: "Comment la nature 'fabrique' de l'eau pure en permanence ?",
      options: [
        { text: 'Évaporation : seule l\'eau passe en vapeur, le sel reste', isCorrect: true, feedback: 'Exact.' },
        { text: 'Filtration par les nuages', isCorrect: false, feedback: 'Pas de filtre.' },
        { text: 'Transformation chimique', isCorrect: false, feedback: 'Pas de chimie.' },
      ],
    },
  ],

  authoredLegendary: [
    {
      id: 'c3-wat-leg-1-hook',
      type: 'STORY',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le boss.',
      screens: [
        {
          text: '14 questions pour valider le cycle planétaire de l\'eau et ses enjeux.',
          imagePrompt: 'Globe avec cycle de l\'eau',
          imageUrl: WATER_IMAGE,
          kind: 'hook',
          boldTokens: ['planétaire'],
        },
      ],
    },
    {
      id: 'c3-wat-leg-2-q',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Moteur du cycle.',
      question: 'Quel est le moteur du cycle ?',
      options: [
        { text: 'La chaleur du Soleil', isCorrect: true, feedback: 'Exact.' },
        { text: 'La gravité lunaire', isCorrect: false, feedback: 'Marées seulement.' },
        { text: 'Les volcans', isCorrect: false, feedback: 'Marginaux.' },
      ],
    },
    {
      id: 'c3-wat-leg-3-q',
      type: 'QUIZ',
      conceptId: 'forest-water-cycle',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Forêts et pluies.',
      question: 'Les forêts génèrent-elles leurs propres pluies ?',
      options: [
        { text: 'Oui, par évapotranspiration', isCorrect: true, feedback: 'Exact.' },
        { text: 'Non, jamais', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'rain-comes-from-clouds-only' },
        { text: 'Seulement la nuit', isCorrect: false, feedback: 'Surtout le jour.' },
      ],
    },
    {
      id: 'c3-wat-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Cycle complet.',
      instruction: 'Cycle complet de l\'eau :',
      axis: 'horizontal',
      axisRationale: 'Chronologie.',
      slotCount: 5,
      items: [
        { id: 'cwl4-1', text: '☀️ Évaporation' },
        { id: 'cwl4-2', text: '☁️ Condensation' },
        { id: 'cwl4-3', text: '🌧️ Précipitation' },
        { id: 'cwl4-4', text: '🌱 Infiltration' },
        { id: 'cwl4-5', text: '🏞️ Retour océan' },
        { id: 'cwl4-distract', text: '🪨 Fossilisation', isDistractor: true },
      ],
      correctFeedback: 'Excellent.',
      incorrectFeedback: 'Indice : un item est faux.',
    },
    {
      id: 'c3-wat-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'medium',
      cognitiveTags: ['interleaved', 'misconception'],
      learningObjective: 'Sol vs béton.',
      question: 'Vrai ou faux ?',
      card: { title: 'Un sol vivant absorbe la pluie, le béton la rejette.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si. Vu au chap 1.',
      explanation: 'Ville-éponge.',
      misconceptionId: 'concrete-helps-drainage',
      interleavesConceptIds: ['soil-living'],
    },
    {
      id: 'c3-wat-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Eaux fossiles.',
      question: 'Vrai ou faux ?',
      card: { title: 'Vider une nappe phréatique profonde est presque irréversible.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Renouvellement millénaire.',
      incorrectFeedback: 'Si. Eaux fossiles.',
      explanation: 'Pas de retour rapide.',
    },
    {
      id: 'c3-wat-leg-7-q',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Choisir la formulation juste.',
      question: 'Comment décrire le cycle de l\'eau ?',
      options: [
        { text: 'Voyage entre réservoirs aux vitesses contrastées', isCorrect: true, feedback: 'Exact.' },
        { text: 'Eau qui se crée et disparaît', isCorrect: false, feedback: 'Faux.' },
        { text: 'Un cycle uniforme', isCorrect: false, feedback: 'Trop simple.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c3-wat-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Soleil + eau.',
      instruction: 'Lien Soleil → eau :',
      axis: 'horizontal',
      axisRationale: 'Causalité.',
      slotCount: 4,
      items: [
        { id: 'cwli-1', text: '☀️ Soleil chauffe' },
        { id: 'cwli-2', text: '💨 Évaporation' },
        { id: 'cwli-3', text: '☁️ Nuages' },
        { id: 'cwli-4', text: '🌧️ Pluies' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : Soleil démarre tout.',
      interleavesConceptIds: ['sun-energy-source'],
    },
    {
      id: 'c3-wat-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint cycle infini.',
      question: 'Vrai ou faux ?',
      card: { title: 'L\'eau de la Terre voyage en boucle depuis 4 milliards d\'années.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Conservation de la matière.',
    },
    {
      id: 'c3-wat-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint distillation.',
      question: 'Vrai ou faux ?',
      card: { title: 'L\'eau de pluie est douce, même au-dessus des océans salés.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Distillation naturelle.',
    },
    {
      id: 'c3-wat-leg-11-q',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthèse climatique.',
      question: 'Pourquoi la fonte des glaciers est-elle un signal d\'alarme climatique ?',
      options: [
        { text: 'Réservoirs millénaires d\'eau douce qui disparaissent en décennies', isCorrect: true, feedback: 'Exact.' },
        { text: 'Aucun problème particulier', isCorrect: false, feedback: 'Faux.' },
        { text: 'Cela rafraîchit les océans', isCorrect: false, feedback: 'Effet secondaire seulement.' },
      ],
    },
    {
      id: 'c3-wat-leg-12-reveal',
      type: 'STORY',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective.',
      screens: [
        {
          text: 'Tu vois maintenant l\'eau partout : ciel, sol, glaciers, racines. Le cycle planétaire est ton allié et notre fragilité.',
          imagePrompt: 'Goutte qui contient un cycle entier',
          imageUrl: WATER_IMAGE,
          kind: 'reveal',
          boldTokens: ['allié'],
        },
      ],
    },
    {
      id: 'c3-wat-leg-13-q',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Action.',
      question: 'Quelle action protège le cycle de l\'eau ?',
      options: [
        { text: 'Préserver forêts + sols vivants + limiter pompage des nappes', isCorrect: true, feedback: 'Exact. Triple action.' },
        { text: 'Bétonner les villes', isCorrect: false, feedback: 'Inverse.', misconceptionId: 'concrete-helps-drainage' },
        { text: 'Pomper plus d\'eau', isCorrect: false, feedback: 'Épuise les ressources.' },
      ],
    },
    {
      id: 'c3-wat-leg-14-closure',
      type: 'STORY',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer le carbone.',
      screens: [
        {
          text: "Eau et pollinisateurs : deux cycles vitaux. Place au plus invisible mais le plus brûlant : le carbone.",
          imagePrompt: 'Forêt avec atomes de carbone',
          imageUrl: FOREST_IMAGE,
          kind: 'closure',
          boldTokens: ['carbone'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'c3-wat-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir le cycle planétaire de l\'eau.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'c3-wat-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser le cycle planétaire.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'c3-wat-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler le cycle dans des cas pièges.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 3 },
    },
    {
      id: 'c3-wat-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise du cycle planétaire.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 30, label: '30 Graines' },
    },
  ],
}
