import type { AcademyUnitDefinition } from '../../../schema'

const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const REEF_IMAGE =
  'https://images.unsplash.com/photo-1546026423-cc4642628d2b?q=80&w=1000&auto=format&fit=crop'

export const extinctionsUnit: AcademyUnitDefinition = {
  id: 'unit-5-1',
  slug: 'le-crepuscule-des-geants',
  chapterId: 'chapter-5',
  schemaVersion: 2,
  title: 'Le Crépuscule des Géants',
  shortTitle: 'Extinctions',
  pathLabel: 'Crépuscule',
  subtitle: "Comprendre les crises actuelles de la biodiversité.",
  concept: 'Extinctions, anthropocène, déclin',
  conceptIds: ['extinction-causes', 'biodiversity-fragility', 'climate-action'],
  kind: 'fauna',
  iconKey: 'hourglass',
  masteryGoal: 'Comprendre la 6e extinction comme phénomène anthropique mesurable.',
  order: 1,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: 'Voir l\'extinction de masse actuelle comme cause humaine documentée.',
  mascot: 'ondine',
  rewardAmount: 50,

  authoredDiscovery: [
    {
      id: 'c5-ext-disc-1-hook',
      type: 'STORY',
      conceptId: 'extinction-causes',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : on est dans une 6e extinction.',
      screens: [
        {
          text: "Sur Terre, il y a déjà eu 5 extinctions massives. Aujourd'hui, on assiste à la 6e. La cause cette fois : nous.",
          imagePrompt: 'Animaux disparus en silhouette',
          imageUrl: FIELD_IMAGE,
          kind: 'hook',
          boldTokens: ['nous'],
        },
      ],
    },
    {
      id: 'c5-ext-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester le « cycle naturel ».',
      question: 'Vrai ou faux ?',
      card: { title: "Le réchauffement climatique actuel est juste un cycle naturel.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bien vu. Le rythme actuel est ~10× plus rapide que les cycles naturels.',
      incorrectFeedback: 'Faux. Cause humaine attestée à >99 %.',
      explanation: 'GIEC AR6.',
      misconceptionId: 'climate-natural-only',
    },
    {
      id: 'c5-ext-disc-3-reveal',
      type: 'STORY',
      conceptId: 'extinction-causes',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler les causes principales.',
      screens: [
        {
          text: "Les 5 grandes causes de la 6e extinction (acronyme HIPPO) : Habitat détruit, Invasives, Pollution, Population, Overexploitation.",
          imagePrompt: 'Schéma HIPPO',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['HIPPO'],
        },
        {
          text: "Le rythme actuel : ~1000 fois plus d'extinctions que la normale géologique. C'est l'anthropocène.",
          imagePrompt: 'Graphique courbe d\'extinctions',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['1000'],
        },
      ],
    },
    {
      id: 'c5-ext-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: ['generation', 'misconception'],
      learningObjective: 'Identifier la cause majeure.',
      question: 'Quelle est la cause principale du déclin actuel des espèces ?',
      options: [
        { text: 'La destruction des habitats par l\'humain', isCorrect: true, feedback: 'Exact. Numéro 1 du HIPPO.' },
        { text: 'Les éruptions volcaniques', isCorrect: false, feedback: 'Marginales aujourd\'hui.' },
        { text: 'Une malchance cosmique', isCorrect: false, feedback: 'Aucune météorite récente.', misconceptionId: 'climate-natural-only' },
      ],
      hint: 'Pense à ce qu\'on construit / défriche.',
    },
    {
      id: 'c5-ext-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'biodiversity-fragility',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir « mes actions ne changent rien ».',
      question: 'Vrai ou faux ?',
      card: { title: "Mes actions individuelles n'ont aucun impact sur le déclin du vivant.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Les comportements collectifs émergent d\'actions individuelles.',
      incorrectFeedback: 'Faux. Effet agrégé mesurable.',
      explanation: 'Réduction viande, transports, bio = effet net documenté.',
      misconceptionId: 'local-actions-no-impact',
    },
    {
      id: 'c5-ext-disc-6-build',
      type: 'STORY',
      conceptId: 'extinction-causes',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Étendre aux insectes.',
      screens: [
        {
          text: 'Pas que les grands animaux : ~75 % des insectes volants ont disparu en Allemagne en 30 ans (Hallmann 2017). Une catastrophe silencieuse.',
          imagePrompt: 'Pare-brise sans insectes vs autrefois',
          imageUrl: FIELD_IMAGE,
          kind: 'build-up',
          boldTokens: ['silencieuse'],
        },
      ],
    },
    {
      id: 'c5-ext-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Reconstituer HIPPO.',
      instruction: 'Ordonne les causes par importance (HIPPO) :',
      axis: 'horizontal',
      axisRationale: 'Mapping HIPPO.',
      slotCount: 5,
      items: [
        { id: 'cex-1', text: '🏗️ Habitat détruit' },
        { id: 'cex-2', text: '🐀 Espèces Invasives' },
        { id: 'cex-3', text: '☣️ Pollution' },
        { id: 'cex-4', text: '👥 Population humaine' },
        { id: 'cex-5', text: '🎣 Overexploitation' },
      ],
      correctFeedback: 'Excellent. HIPPO maîtrisé.',
      incorrectFeedback: 'Indice : H-I-P-P-O.',
    },
    {
      id: 'c5-ext-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'extinction-causes',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint rythme.',
      question: 'Vrai ou faux ?',
      card: { title: "Le rythme actuel d'extinction est environ 1000× plus rapide que la normale.", subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. IPBES 2019.',
      incorrectFeedback: 'Si.',
      explanation: 'Anthropocène.',
    },
    {
      id: 'c5-ext-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'biodiversity-fragility',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Sprint actions individuelles.',
      question: 'Vrai ou faux ?',
      card: { title: "L'agrégation de petits gestes individuels peut créer un changement mesurable.", subtitle: 'Sprint 2' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Effet collectif.',
      incorrectFeedback: 'Si.',
      explanation: 'Comportements émergents.',
      misconceptionId: 'local-actions-no-impact',
    },
    {
      id: 'c5-ext-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: 'Cause humaine attestée.',
      question: 'Quelle est la part de la cause humaine dans le réchauffement actuel ?',
      options: [
        { text: 'Attestée à >99 % par le consensus scientifique', isCorrect: true, feedback: 'Exact. GIEC.' },
        { text: 'Probable mais incertaine', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'climate-natural-only' },
        { text: 'Aucune, c\'est naturel', isCorrect: false, feedback: 'Faux.', misconceptionId: 'climate-natural-only' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c5-ext-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Hiérarchiser causes vs effets.',
      instruction: 'Sépare causes et effets :',
      axis: 'horizontal',
      axisRationale: 'Mapping causal.',
      slotCount: 4,
      items: [
        { id: 'ceb-1', text: '🏗️ Cause : habitat détruit' },
        { id: 'ceb-2', text: '☣️ Cause : pollution' },
        { id: 'ceb-3', text: '📉 Effet : déclin espèces' },
        { id: 'ceb-4', text: '🌡️ Effet : climat dérègle' },
      ],
      correctFeedback: 'Parfait. Causes / effets distincts.',
      incorrectFeedback: 'Indice : actions humaines puis conséquences.',
      interleavesConceptIds: ['ecosystem-flow'],
    },
    {
      id: 'c5-ext-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser : crise documentée.',
      question: 'Que sais-tu de la crise actuelle de la biodiversité ?',
      options: [
        { text: '6e extinction de masse, cause humaine, rythme ~1000× plus rapide', isCorrect: true, feedback: 'Exact.' },
        { text: 'Cycle naturel sans gravité', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'climate-natural-only' },
        { text: 'Inévitable, on ne peut rien faire', isCorrect: false, feedback: 'Faux. On peut agir.', misconceptionId: 'local-actions-no-impact' },
      ],
    },
  ],

  pool: [
    {
      id: 'c5-ext-pool-sw-rate',
      type: 'SWIPE',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Rythme.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les humains ont causé l\'extinction de plus d\'espèces que toutes les éruptions volcaniques modernes.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si. IPBES.',
      explanation: 'Anthropocène = humain dominant.',
    },
    {
      id: 'c5-ext-pool-sw-insects',
      type: 'SWIPE',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Déclin insectes.',
      question: 'Vrai ou faux ?',
      card: { title: '~75 % des insectes volants ont disparu en Allemagne en 30 ans.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Hallmann 2017.',
      incorrectFeedback: 'Si.',
      explanation: 'Catastrophe silencieuse.',
    },
    {
      id: 'c5-ext-pool-sw-keystone-loss',
      type: 'SWIPE',
      conceptId: 'biodiversity-fragility',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Espèces-clés perdues.',
      question: 'Vrai ou faux ?',
      card: { title: "Perdre une espèce-clé peut faire s\'effondrer tout l'écosystème.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Cascade.',
      interleavesConceptIds: ['trophic-cascade'],
    },
    {
      id: 'c5-ext-pool-sw-climate',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Climat = cause majeure.',
      question: 'Vrai ou faux ?',
      card: { title: 'Le climat est l\'une des causes croissantes du déclin du vivant.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'GIEC + IPBES.',
      misconceptionId: 'climate-natural-only',
    },
    {
      id: 'c5-ext-pool-q-five-mass',
      type: 'QUIZ',
      conceptId: 'extinction-causes',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: '5 extinctions précédentes.',
      question: 'Combien d\'extinctions de masse a-t-il déjà eu sur Terre avant celle-ci ?',
      options: [
        { text: '5', isCorrect: true, feedback: 'Exact.' },
        { text: '0', isCorrect: false, feedback: 'Faux.' },
        { text: '20', isCorrect: false, feedback: 'Faux.' },
      ],
    },
    {
      id: 'c5-ext-pool-q-meta',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Définition juste.',
      question: 'Comment décrire la 6e extinction ?',
      options: [
        { text: 'Crise anthropique, rythme ~1000× plus rapide que la normale', isCorrect: true, feedback: 'Exact.' },
        { text: 'Cycle naturel inéluctable', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'climate-natural-only' },
        { text: 'Sujet exagéré', isCorrect: false, feedback: 'Faux.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c5-ext-pool-q-hippo',
      type: 'QUIZ',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'HIPPO.',
      question: 'Que signifie l\'acronyme HIPPO en biodiversité ?',
      options: [
        { text: 'Habitat, Invasives, Pollution, Population, Overexploitation', isCorrect: true, feedback: 'Exact.' },
        { text: 'Hippopotame géant', isCorrect: false, feedback: 'Aucun rapport.' },
        { text: 'Aucun sens', isCorrect: false, feedback: 'Faux.' },
      ],
    },
    {
      id: 'c5-ext-pool-d-causes',
      type: 'DRAG_DROP',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser HIPPO.',
      instruction: 'HIPPO :',
      axis: 'horizontal',
      axisRationale: 'Mapping.',
      slotCount: 5,
      items: [
        { id: 'cep-1', text: 'H : Habitat' },
        { id: 'cep-2', text: 'I : Invasives' },
        { id: 'cep-3', text: 'P : Pollution' },
        { id: 'cep-4', text: 'P : Population' },
        { id: 'cep-5', text: 'O : Overexploitation' },
      ],
      correctFeedback: 'Excellent.',
      incorrectFeedback: 'Indice : H-I-P-P-O.',
    },
    {
      id: 'c5-ext-pool-d-rate',
      type: 'DRAG_DROP',
      conceptId: 'extinction-causes',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser époques.',
      instruction: 'Du moins au plus rapide :',
      axis: 'horizontal',
      axisRationale: 'Gradient.',
      slotCount: 3,
      items: [
        { id: 'cer-1', text: '🦖 Extinction K-T (66 Ma)' },
        { id: 'cer-2', text: '🌍 Rythme naturel actuel' },
        { id: 'cer-3', text: '👤 Anthropocène' },
      ],
      correctFeedback: 'Excellent. Anthropocène = ~1000× plus rapide.',
      incorrectFeedback: 'Indice : aujourd\'hui = champion.',
    },
    {
      id: 'c5-ext-pool-sw-amphibian',
      type: 'SWIPE',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Amphibiens menacés.',
      question: 'Vrai ou faux ?',
      card: { title: '~40 % des amphibiens sont menacés d\'extinction.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Groupe le plus menacé.',
      incorrectFeedback: 'Si. UICN.',
      explanation: 'Sentinelles.',
    },
    {
      id: 'c5-ext-pool-sw-pollinator-collapse',
      type: 'SWIPE',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Effondrement pollinisateurs.',
      question: 'Vrai ou faux ?',
      card: { title: 'L\'effondrement des pollinisateurs menace ~1/3 de notre alimentation.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Vu au chap 3.',
      interleavesConceptIds: ['pollination-agents'],
    },
    {
      id: 'c5-ext-pool-q-time',
      type: 'QUIZ',
      conceptId: 'biodiversity-fragility',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Échelle de temps.',
      question: 'Combien de temps faut-il pour qu\'une extinction de masse récupère, naturellement ?',
      options: [
        { text: 'Plusieurs millions d\'années', isCorrect: true, feedback: 'Exact. Récupération biotique très lente.' },
        { text: 'Quelques décennies', isCorrect: false, feedback: 'Trop rapide.' },
        { text: 'Quelques siècles', isCorrect: false, feedback: 'Trop rapide.' },
      ],
    },
  ],

  authoredLegendary: [
    {
      id: 'c5-ext-leg-1-hook',
      type: 'STORY',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le boss.',
      screens: [
        {
          text: '14 questions pour valider la compréhension de la 6e extinction et de ses causes.',
          imagePrompt: 'Sablier avec animaux disparus',
          imageUrl: FIELD_IMAGE,
          kind: 'hook',
          boldTokens: ['extinction'],
        },
      ],
    },
    {
      id: 'c5-ext-leg-2-q',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Cause humaine.',
      question: 'Le réchauffement actuel est-il causé par l\'humain ?',
      options: [
        { text: 'Oui, attestation >99 %', isCorrect: true, feedback: 'Exact.' },
        { text: 'Cycle naturel', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'climate-natural-only' },
        { text: 'Inconnu', isCorrect: false, feedback: 'Consensus solide.' },
      ],
    },
    {
      id: 'c5-ext-leg-3-q',
      type: 'QUIZ',
      conceptId: 'extinction-causes',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Cause majeure.',
      question: 'Quelle est la cause numéro 1 du déclin actuel ?',
      options: [
        { text: 'Destruction des habitats', isCorrect: true, feedback: 'Exact. H de HIPPO.' },
        { text: 'Volcans', isCorrect: false, feedback: 'Faux.' },
        { text: 'Soleil', isCorrect: false, feedback: 'Faux.' },
      ],
    },
    {
      id: 'c5-ext-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'extinction-causes',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'HIPPO complet.',
      instruction: 'Reconstitue HIPPO :',
      axis: 'horizontal',
      axisRationale: 'Mapping.',
      slotCount: 5,
      items: [
        { id: 'celg-1', text: 'H : Habitat' },
        { id: 'celg-2', text: 'I : Invasives' },
        { id: 'celg-3', text: 'P : Pollution' },
        { id: 'celg-4', text: 'P : Population' },
        { id: 'celg-5', text: 'O : Overexploitation' },
        { id: 'celg-distract', text: '✨ Magie noire', isDistractor: true },
      ],
      correctFeedback: 'Excellent.',
      incorrectFeedback: 'Indice : un item est faux.',
    },
    {
      id: 'c5-ext-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'biodiversity-fragility',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Sprint actions.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les actions individuelles, agrégées, ont un impact mesurable.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Effet collectif.',
      misconceptionId: 'local-actions-no-impact',
    },
    {
      id: 'c5-ext-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Sprint rythme.',
      question: 'Vrai ou faux ?',
      card: { title: 'Le rythme actuel d\'extinction dépasse largement la normale géologique.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. ~1000×.',
      incorrectFeedback: 'Si.',
      explanation: 'IPBES.',
    },
    {
      id: 'c5-ext-leg-7-q',
      type: 'QUIZ',
      conceptId: 'extinction-causes',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Définition juste.',
      question: 'Comment décrire la 6e extinction ?',
      options: [
        { text: 'Crise anthropique mesurable, ~1000× plus rapide que la normale', isCorrect: true, feedback: 'Exact.' },
        { text: 'Cycle naturel inéluctable', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'climate-natural-only' },
        { text: 'Hypothèse incertaine', isCorrect: false, feedback: 'Faux.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c5-ext-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'extinction-causes',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Lien chaîne + extinction.',
      instruction: 'Conséquences en cascade :',
      axis: 'horizontal',
      axisRationale: 'Causalité.',
      slotCount: 4,
      items: [
        { id: 'celr-1', text: '🐺 Loup éliminé' },
        { id: 'celr-2', text: '🦌 Cerfs explosent' },
        { id: 'celr-3', text: '🌳 Berges érodées' },
        { id: 'celr-4', text: '🏞️ Rivière dégradée' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : chap 2 sur les prédateurs.',
      interleavesConceptIds: ['trophic-cascade'],
    },
    {
      id: 'c5-ext-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'extinction-causes',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint insectes.',
      question: 'Vrai ou faux ?',
      card: { title: '~75 % des insectes volants ont disparu en Allemagne (Hallmann 2017).', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Cas documenté.',
    },
    {
      id: 'c5-ext-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint cause humaine.',
      question: 'Vrai ou faux ?',
      card: { title: 'La cause humaine du réchauffement est attestée à plus de 99 %.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si. GIEC.',
      explanation: 'Consensus.',
    },
    {
      id: 'c5-ext-leg-11-q',
      type: 'QUIZ',
      conceptId: 'biodiversity-fragility',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthèse.',
      question: 'Pourquoi la perte de biodiversité est-elle un enjeu majeur ?',
      options: [
        { text: 'Elle fragilise tous les services écosystémiques + irréversibilité', isCorrect: true, feedback: 'Exact.' },
        { text: 'Aucun enjeu', isCorrect: false, feedback: 'Faux.' },
        { text: 'Esthétique uniquement', isCorrect: false, feedback: 'Faux.' },
      ],
    },
    {
      id: 'c5-ext-leg-12-reveal',
      type: 'STORY',
      conceptId: 'extinction-causes',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective.',
      screens: [
        {
          text: 'La 6e extinction est documentée. Mais l\'humain en est aussi le seul à pouvoir la freiner. C\'est l\'objet du chapitre suivant.',
          imagePrompt: 'Personne face à un sablier qu\'elle peut tourner',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['freiner'],
        },
      ],
    },
    {
      id: 'c5-ext-leg-13-q',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Action.',
      question: 'Quelle action soutient la lutte contre la 6e extinction ?',
      options: [
        { text: 'Réduire HIPPO : préserver habitats, limiter pollution + pression', isCorrect: true, feedback: 'Exact.' },
        { text: 'Bétonner pour ranger', isCorrect: false, feedback: 'Aggrave.' },
        { text: 'Ne rien faire', isCorrect: false, feedback: 'Faux.', misconceptionId: 'local-actions-no-impact' },
      ],
    },
    {
      id: 'c5-ext-leg-14-closure',
      type: 'STORY',
      conceptId: 'climate-action',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer Solutions.',
      screens: [
        {
          text: 'Tu vois la crise. Place aux solutions concrètes : conservation, restauration, innovation.',
          imagePrompt: 'Personne plantant un arbre',
          imageUrl: REEF_IMAGE,
          kind: 'closure',
          boldTokens: ['solutions'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'c5-ext-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir la 6e extinction.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'c5-ext-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser la crise.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'c5-ext-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler les concepts.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 3 },
    },
    {
      id: 'c5-ext-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 50, label: '50 Graines' },
    },
  ],
}
