import type { AcademyUnitDefinition } from '../../../schema'

const SPROUT_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'
const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'

export const permacultureUnit: AcademyUnitDefinition = {
  id: 'unit-5-3',
  slug: 'cultiver-lavenir',
  chapterId: 'chapter-5',
  schemaVersion: 2,
  title: "Cultiver l'Avenir",
  shortTitle: 'Permaculture',
  pathLabel: 'Avenir',
  subtitle: "Cultiver en imitant les écosystèmes naturels.",
  concept: 'Permaculture, agroécologie, résilience',
  conceptIds: ['agriculture-impact', 'food-footprint', 'systemic-change'],
  kind: 'project',
  iconKey: 'seedling',
  masteryGoal: 'Comprendre la permaculture comme imitation systémique de la nature.',
  order: 3,
  durationMinutes: 4,
  estimatedMinutes: '4-5 min',
  learningGoal: 'Voir la permaculture et l\'agroécologie comme synthèse pratique.',
  mascot: 'sylva',
  rewardAmount: 100,

  authoredDiscovery: [
    {
      id: 'c5-perm-disc-1-hook',
      type: 'STORY',
      conceptId: 'agriculture-impact',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : cultiver SANS détruire.',
      screens: [
        {
          text: "L'agriculture industrielle épuise les sols. Mais des fermes permacoles produisent autant, en régénérant le vivant. Comment ?",
          imagePrompt: 'Ferme permacole vs champ industriel',
          imageUrl: FIELD_IMAGE,
          kind: 'hook',
          boldTokens: ['régénérant'],
        },
      ],
    },
    {
      id: 'c5-perm-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'agriculture-impact',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester « bio = pas de pesticides ».',
      question: 'Vrai ou faux ?',
      card: { title: "Bio signifie zéro pesticide.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bien vu. Le bio autorise certains pesticides naturels (cuivre, soufre).',
      incorrectFeedback: 'Faux. Bio ≠ sans pesticide.',
      explanation: 'INRAE 2021.',
      misconceptionId: 'bio-means-no-pesticides',
    },
    {
      id: 'c5-perm-disc-3-reveal',
      type: 'STORY',
      conceptId: 'agriculture-impact',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler les principes permacoles.',
      screens: [
        {
          text: 'Permaculture : observer la nature, imiter ses cycles, intégrer les systèmes (pas de déchets, juste des ressources).',
          imagePrompt: 'Cycle permacole',
          imageUrl: SPROUT_IMAGE,
          kind: 'reveal',
          boldTokens: ['imiter'],
        },
        {
          text: 'Pas un dogme : un cadre de design. 3 éthiques : prendre soin de la Terre, des humains, partager équitablement.',
          imagePrompt: 'Trois éthiques',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['design'],
        },
      ],
    },
    {
      id: 'c5-perm-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'agriculture-impact',
      difficulty: 'medium',
      cognitiveTags: ['generation', 'misconception'],
      learningObjective: 'Identifier l\'approche.',
      question: "Qu'est-ce que la permaculture ?",
      options: [
        { text: 'Un cadre de design qui imite les écosystèmes naturels', isCorrect: true, feedback: 'Exact.' },
        { text: 'Une marque de pesticide bio', isCorrect: false, feedback: 'Aucun rapport.' },
        { text: 'Une religion écolo', isCorrect: false, feedback: 'Pas un dogme.' },
      ],
      hint: 'Pense à « permanent » + « culture ».',
    },
    {
      id: 'c5-perm-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'food-footprint',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir « local toujours mieux ».',
      question: 'Vrai ou faux ?',
      card: { title: "Manger local est TOUJOURS plus écologique.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Tomate sous serre chauffée hors-saison émet plus qu\'une importée.',
      incorrectFeedback: 'Faux. Local + saison = mieux. Local hors-saison sous serre = parfois pire.',
      explanation: 'ADEME.',
      misconceptionId: 'local-always-better',
    },
    {
      id: 'c5-perm-disc-6-build',
      type: 'STORY',
      conceptId: 'agriculture-impact',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Étendre à l\'agroécologie.',
      screens: [
        {
          text: 'Au-delà du jardin : agroécologie à grande échelle. Reconnecter agriculture et écosystèmes pour une production durable.',
          imagePrompt: 'Champ avec haies, mares, polycultures',
          imageUrl: SPROUT_IMAGE,
          kind: 'build-up',
          boldTokens: ['reconnecter'],
        },
      ],
    },
    {
      id: 'c5-perm-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'agriculture-impact',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Reconstituer le design permacole.',
      instruction: 'Ordonne les principes permacoles :',
      axis: 'horizontal',
      axisRationale: 'Chronologie design.',
      slotCount: 3,
      items: [
        { id: 'cpe-1', text: '👀 Observer' },
        { id: 'cpe-2', text: '🛠️ Concevoir' },
        { id: 'cpe-3', text: '🌱 Cultiver' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : observer puis concevoir.',
    },
    {
      id: 'c5-perm-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'agriculture-impact',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint mimétisme.',
      question: 'Vrai ou faux ?',
      card: { title: 'La permaculture imite les cycles naturels.', subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Imitation systémique.',
    },
    {
      id: 'c5-perm-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'food-footprint',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint protéines végétales.',
      question: 'Vrai ou faux ?',
      card: { title: "Lentilles, pois chiches et tofu fournissent autant de protéines que la viande pour 100 g.", subtitle: 'Sprint 2' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Avec empreinte 10-50× plus faible.',
      misconceptionId: 'meat-is-only-protein',
    },
    {
      id: 'c5-perm-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'agriculture-impact',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: 'Bio plus complexe que prévu.',
      question: 'Un produit bio est-il toujours plus écologique ?',
      options: [
        { text: 'Pas toujours : dépend du produit, transport et saison', isCorrect: true, feedback: 'Exact. Clark & Tilman 2017.' },
        { text: 'Oui, automatiquement', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'organic-always-better' },
        { text: 'Non, jamais', isCorrect: false, feedback: 'Faux.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c5-perm-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'agriculture-impact',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Synthétiser les pratiques.',
      instruction: 'Trie ces pratiques :',
      axis: 'horizontal',
      axisRationale: 'Mapping.',
      slotCount: 4,
      items: [
        { id: 'cpb-1', text: '🌳 Haies brise-vent' },
        { id: 'cpb-2', text: '🌾 Polyculture' },
        { id: 'cpb-3', text: '🐝 Plantes mellifères' },
        { id: 'cpb-4', text: '💧 Compost' },
        { id: 'cpb-distract', text: '☢️ Pesticide chimique total', isDistractor: true },
      ],
      correctFeedback: 'Excellent. Le pesticide chimique total est anti-permacole.',
      incorrectFeedback: 'Indice : un seul item est anti-vivant.',
      interleavesConceptIds: ['soil-living', 'pollination-agents'],
    },
    {
      id: 'c5-perm-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'systemic-change',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser : approche systémique.',
      question: 'Que représente la permaculture en pratique ?',
      options: [
        { text: 'Une approche systémique d\'agriculture régénérative', isCorrect: true, feedback: 'Exact.' },
        { text: 'Un dogme rigide', isCorrect: false, feedback: 'Faux.' },
        { text: 'Inutile', isCorrect: false, feedback: 'Faux.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c5-perm-pool-sw-organic-complex',
      type: 'SWIPE',
      conceptId: 'food-footprint',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Bio = nuancé.',
      question: 'Vrai ou faux ?',
      card: { title: 'Le bio peut demander plus de surface qu\'une culture conventionnelle.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Trade-off réel.',
      incorrectFeedback: 'Si.',
      explanation: 'Pas un mythe, mais c\'est nuancé.',
      misconceptionId: 'organic-always-better',
    },
    {
      id: 'c5-perm-pool-sw-no-till',
      type: 'SWIPE',
      conceptId: 'agriculture-impact',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Sans labour.',
      question: 'Vrai ou faux ?',
      card: { title: 'Ne pas labourer le sol préserve sa structure et sa vie.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. No-till.',
      incorrectFeedback: 'Si.',
      explanation: 'Pratique régénérative.',
    },
    {
      id: 'c5-perm-pool-sw-hedges',
      type: 'SWIPE',
      conceptId: 'agriculture-impact',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Haies bénéfiques.',
      question: 'Vrai ou faux ?',
      card: { title: 'Planter des haies dans les champs augmente la biodiversité ET les rendements.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Auxiliaires + protection.',
    },
    {
      id: 'c5-perm-pool-sw-meat',
      type: 'SWIPE',
      conceptId: 'food-footprint',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Protéines végétales.',
      question: 'Vrai ou faux ?',
      card: { title: 'On peut couvrir ses besoins en protéines sans manger de viande.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Lentilles, tofu, etc.',
      misconceptionId: 'meat-is-only-protein',
    },
    {
      id: 'c5-perm-pool-q-greenhouse',
      type: 'QUIZ',
      conceptId: 'food-footprint',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Tomate locale.',
      question: 'Une tomate locale en hiver sous serre chauffée a quel impact ?',
      options: [
        { text: 'Souvent plus élevé qu\'une tomate importée de saison', isCorrect: true, feedback: 'Exact. ADEME.' },
        { text: 'Toujours moins', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'local-always-better' },
        { text: 'Aucun', isCorrect: false, feedback: 'Faux.' },
      ],
    },
    {
      id: 'c5-perm-pool-q-meta',
      type: 'QUIZ',
      conceptId: 'agriculture-impact',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Définition juste.',
      question: 'Comment décrire la permaculture ?',
      options: [
        { text: 'Cadre de design qui imite les écosystèmes', isCorrect: true, feedback: 'Exact.' },
        { text: 'Marque de produit', isCorrect: false, feedback: 'Faux.' },
        { text: 'Religion', isCorrect: false, feedback: 'Faux.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c5-perm-pool-q-ethics',
      type: 'QUIZ',
      conceptId: 'agriculture-impact',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: '3 éthiques.',
      question: 'Quelles sont les 3 éthiques de la permaculture ?',
      options: [
        { text: 'Soin de la Terre + soin des humains + partage équitable', isCorrect: true, feedback: 'Exact.' },
        { text: 'Argent, pouvoir, gloire', isCorrect: false, feedback: 'Aucun rapport.' },
        { text: 'Productivité maximale', isCorrect: false, feedback: 'Pas le centre.' },
      ],
    },
    {
      id: 'c5-perm-pool-d-zones',
      type: 'DRAG_DROP',
      conceptId: 'agriculture-impact',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Zoning permacole.',
      instruction: 'Du plus près de la maison au plus sauvage :',
      axis: 'horizontal',
      axisRationale: 'Gradient d\'intensité.',
      slotCount: 3,
      items: [
        { id: 'cpz-1', text: '🏠 Zone 1 (potager)' },
        { id: 'cpz-2', text: '🌾 Zone 2 (verger)' },
        { id: 'cpz-3', text: '🌲 Zone 5 (sauvage)' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : intense → sauvage.',
    },
    {
      id: 'c5-perm-pool-d-strategies',
      type: 'DRAG_DROP',
      conceptId: 'agriculture-impact',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Hiérarchiser pratiques.',
      instruction: 'Du moins au plus régénératif :',
      axis: 'horizontal',
      axisRationale: 'Gradient.',
      slotCount: 4,
      items: [
        { id: 'cps-1', text: '🌽 Monoculture intensive' },
        { id: 'cps-2', text: '🌱 Bio standard' },
        { id: 'cps-3', text: '🌳 Agroforesterie' },
        { id: 'cps-4', text: '🌍 Permaculture' },
      ],
      correctFeedback: 'Excellent.',
      incorrectFeedback: 'Indice : monoculture en bas, permaculture en haut.',
      interleavesConceptIds: ['soil-living'],
    },
    {
      id: 'c5-perm-pool-sw-water',
      type: 'SWIPE',
      conceptId: 'agriculture-impact',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Gestion eau.',
      question: 'Vrai ou faux ?',
      card: { title: "Les baissières et mares retiennent l'eau et nourrissent le sol.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Keyline design.',
      incorrectFeedback: 'Si.',
      explanation: 'Réservoir local.',
      interleavesConceptIds: ['water-cycle-infiltration'],
    },
    {
      id: 'c5-perm-pool-sw-tropical',
      type: 'SWIPE',
      conceptId: 'agriculture-impact',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Agroforesterie tropicale.',
      question: 'Vrai ou faux ?',
      card: { title: 'Sous les tropiques, l\'agroforesterie peut produire autant que les monocultures.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Étages de production.',
      incorrectFeedback: 'Si.',
      explanation: 'Diversité = stabilité.',
    },
    {
      id: 'c5-perm-pool-q-resilience',
      type: 'QUIZ',
      conceptId: 'systemic-change',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Résilience.',
      question: 'Pourquoi la diversité agricole est-elle un atout ?',
      options: [
        { text: 'Elle rend les fermes plus résilientes face aux maladies et aléas climatiques', isCorrect: true, feedback: 'Exact.' },
        { text: 'Aucun avantage', isCorrect: false, feedback: 'Faux.' },
        { text: 'Esthétique seulement', isCorrect: false, feedback: 'Faux.' },
      ],
    },
  ],

  authoredLegendary: [
    {
      id: 'c5-perm-leg-1-hook',
      type: 'STORY',
      conceptId: 'agriculture-impact',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer la couronne finale.',
      screens: [
        {
          text: 'Boss final de l\'Académie. 14 questions pour valider une vision systémique de l\'avenir.',
          imagePrompt: 'Couronne avec graine',
          imageUrl: SPROUT_IMAGE,
          kind: 'hook',
          boldTokens: ['final'],
        },
      ],
    },
    {
      id: 'c5-perm-leg-2-q',
      type: 'QUIZ',
      conceptId: 'agriculture-impact',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Définition permaculture.',
      question: 'Qu\'est-ce que la permaculture ?',
      options: [
        { text: 'Cadre de design qui imite la nature', isCorrect: true, feedback: 'Exact.' },
        { text: 'Marque commerciale', isCorrect: false, feedback: 'Faux.' },
        { text: 'Religion', isCorrect: false, feedback: 'Faux.' },
      ],
    },
    {
      id: 'c5-perm-leg-3-q',
      type: 'QUIZ',
      conceptId: 'food-footprint',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Bio nuancé.',
      question: 'Le bio est-il automatiquement plus écologique ?',
      options: [
        { text: 'Pas toujours, dépend du contexte', isCorrect: true, feedback: 'Exact.' },
        { text: 'Toujours', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'organic-always-better' },
        { text: 'Jamais', isCorrect: false, feedback: 'Faux.' },
      ],
    },
    {
      id: 'c5-perm-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'agriculture-impact',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Synthèse de toutes les pratiques.',
      instruction: 'Place ces actions :',
      axis: 'horizontal',
      axisRationale: 'Mapping action-bénéfice.',
      slotCount: 4,
      items: [
        { id: 'cplg-1', text: '🌳 Haies (biodiversité)' },
        { id: 'cplg-2', text: '🌾 Polyculture (sols)' },
        { id: 'cplg-3', text: '🐝 Mellifères (pollinisateurs)' },
        { id: 'cplg-4', text: '💧 Mare (eau + faune)' },
        { id: 'cplg-distract', text: '☣️ Glyphosate', isDistractor: true },
      ],
      correctFeedback: 'Excellent.',
      incorrectFeedback: 'Indice : un item est destructeur.',
      interleavesConceptIds: ['soil-living', 'pollination-agents', 'water-cycle-infiltration'],
    },
    {
      id: 'c5-perm-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'food-footprint',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Local + saison.',
      question: 'Vrai ou faux ?',
      card: { title: "Local + de saison = combinaison souvent plus écologique.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Pas local seul.',
      incorrectFeedback: 'Si.',
      explanation: 'ADEME.',
      misconceptionId: 'local-always-better',
    },
    {
      id: 'c5-perm-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'food-footprint',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Protéines.',
      question: 'Vrai ou faux ?',
      card: { title: 'Légumineuses + céréales fournissent toutes les protéines nécessaires.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Combinaison classique.',
      misconceptionId: 'meat-is-only-protein',
    },
    {
      id: 'c5-perm-leg-7-q',
      type: 'QUIZ',
      conceptId: 'systemic-change',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Approche systémique.',
      question: 'Que signifie « systémique » en environnement ?',
      options: [
        { text: 'Aborder le problème dans toutes ses dimensions interconnectées', isCorrect: true, feedback: 'Exact.' },
        { text: 'Une seule action ciblée', isCorrect: false, feedback: 'Insuffisant seul.' },
        { text: 'Aucune action', isCorrect: false, feedback: 'Faux.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c5-perm-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'systemic-change',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Synthèse complète Académie.',
      instruction: 'Place ces niveaux d\'action :',
      axis: 'vertical',
      axisRationale: 'Pyramide d\'impact.',
      slotCount: 4,
      items: [
        { id: 'cplr-1', text: '👤 Individuel (alimentation)' },
        { id: 'cplr-2', text: '🏘️ Local (potager, asso)' },
        { id: 'cplr-3', text: '🏛️ Politique (vote)' },
        { id: 'cplr-4', text: '🌍 Systémique (cadre global)' },
      ],
      correctFeedback: 'Excellent.',
      incorrectFeedback: 'Indice : individuel en bas, système en haut.',
      interleavesConceptIds: ['climate-action'],
    },
    {
      id: 'c5-perm-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'agriculture-impact',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint imitation.',
      question: 'Vrai ou faux ?',
      card: { title: 'Imiter la nature est plus durable que la combattre.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Principe de base.',
    },
    {
      id: 'c5-perm-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'agriculture-impact',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint diversité.',
      question: 'Vrai ou faux ?',
      card: { title: 'La diversité agricole renforce la résilience face au climat.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Assurance écologique.',
    },
    {
      id: 'c5-perm-leg-11-q',
      type: 'QUIZ',
      conceptId: 'systemic-change',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthèse finale.',
      question: 'Quel mot résume le mieux la permaculture ?',
      options: [
        { text: 'Régénération', isCorrect: true, feedback: 'Exact. Pas juste « durable », mais « régénérateur ».' },
        { text: 'Productivité', isCorrect: false, feedback: 'Trop limité.' },
        { text: 'Décroissance', isCorrect: false, feedback: 'Pas le mot principal.' },
      ],
    },
    {
      id: 'c5-perm-leg-12-reveal',
      type: 'STORY',
      conceptId: 'agriculture-impact',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective finale.',
      screens: [
        {
          text: 'Tu as parcouru les 5 chapitres. Tu sais lire un écosystème, identifier ses fragilités et choisir tes leviers d\'action.',
          imagePrompt: 'Personne avec couronne devant un paysage régénéré',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['leviers'],
        },
      ],
    },
    {
      id: 'c5-perm-leg-13-q',
      type: 'QUIZ',
      conceptId: 'systemic-change',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Action finale.',
      question: 'Quelle posture finale est la plus juste ?',
      options: [
        { text: 'Comprendre + agir à plusieurs échelles + persévérer', isCorrect: true, feedback: 'Exact. Bravo, tu as terminé l\'Académie.' },
        { text: 'Tout abandonner', isCorrect: false, feedback: 'Faux.', misconceptionId: 'local-actions-no-impact' },
        { text: 'Tout savoir sans agir', isCorrect: false, feedback: 'Insuffisant.' },
      ],
    },
    {
      id: 'c5-perm-leg-14-closure',
      type: 'STORY',
      conceptId: 'systemic-change',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Conclure l\'Académie.',
      screens: [
        {
          text: "Tu es un Gardien éveillé. Le vivant a besoin de toi. Maintenant tu peux choisir tes batailles. Bonne chance.",
          imagePrompt: 'Personne face à un paysage divers et vivant',
          imageUrl: FIELD_IMAGE,
          kind: 'closure',
          boldTokens: ['Gardien'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'c5-perm-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '4 min',
      learningGoal: 'Découvrir la permaculture.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'c5-perm-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '4 min',
      learningGoal: 'Réviser la permaculture.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.5, interleaveFromPreviousUnits: 3 },
    },
    {
      id: 'c5-perm-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '4 min',
      learningGoal: 'Manipuler la permaculture.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.6, metacognitionRatio: 0.3, hardRatio: 0.7, interleaveFromPreviousUnits: 4 },
    },
    {
      id: 'c5-perm-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '5 min',
      learningGoal: 'Boss final : maîtriser l\'avenir cultivable.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 100, label: '100 Graines' },
    },
  ],
}
