import type { AcademyUnitDefinition } from '../../../schema'

const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const SPROUT_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'

export const solutionsUnit: AcademyUnitDefinition = {
  id: 'unit-5-2',
  slug: 'larsenal-de-lespoir',
  chapterId: 'chapter-5',
  schemaVersion: 2,
  title: "L'Arsenal de l'Espoir",
  shortTitle: 'Solutions',
  pathLabel: 'Arsenal',
  subtitle: 'Conservation, restauration, innovation : les outils qui marchent.',
  concept: 'Solutions, conservation, restauration',
  conceptIds: ['climate-action', 'systemic-change', 'forest-services'],
  kind: 'project',
  iconKey: 'shield',
  masteryGoal: "Comprendre les leviers d'action concrets pour le vivant.",
  order: 2,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: 'Identifier les solutions efficaces et leurs limites.',
  mascot: 'abeille-transparente',
  rewardAmount: 50,

  authoredDiscovery: [
    {
      id: 'c5-sol-disc-1-hook',
      type: 'STORY',
      conceptId: 'climate-action',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : les solutions existent.',
      screens: [
        {
          text: "On parle souvent du déclin. Mais des dizaines d'écosystèmes ont été restaurés ces 30 dernières années. La science sait comment.",
          imagePrompt: 'Forêt restaurée vs déforestée',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['restaurés'],
        },
      ],
    },
    {
      id: 'c5-sol-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'forest-services',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester « planter résout tout ».',
      question: 'Vrai ou faux ?',
      card: { title: "Planter des milliards d'arbres suffit à régler la crise climatique.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bien vu. Aide, mais ne compense qu\'une fraction des émissions.',
      incorrectFeedback: 'Faux. Préserver les forêts existantes est plus efficace que reboiser.',
      explanation: 'Bastin 2019 + critiques.',
      misconceptionId: 'planting-trees-fixes-climate',
    },
    {
      id: 'c5-sol-disc-3-reveal',
      type: 'STORY',
      conceptId: 'climate-action',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler les 3 leviers.',
      screens: [
        {
          text: '3 leviers majeurs : (1) Préserver l\'existant. (2) Restaurer ce qui peut l\'être. (3) Innover (énergies, agriculture, économie).',
          imagePrompt: 'Trois leviers symboliques',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['leviers'],
        },
        {
          text: "Aucun seul ne suffit. Les trois en parallèle, oui. C'est l'arsenal de l'espoir scientifique.",
          imagePrompt: 'Trois actions menées en parallèle',
          imageUrl: SPROUT_IMAGE,
          kind: 'reveal',
          boldTokens: ['parallèle'],
        },
      ],
    },
    {
      id: 'c5-sol-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Identifier le levier prioritaire.',
      question: 'Quel levier offre le meilleur rapport effort/impact climatique ?',
      options: [
        { text: 'Préserver les forêts anciennes existantes', isCorrect: true, feedback: 'Exact. Effet immédiat, gratuit.' },
        { text: 'Reboiser uniquement', isCorrect: false, feedback: 'Aide mais effet à 30+ ans.', misconceptionId: 'planting-trees-fixes-climate' },
        { text: 'Bétonner pour ranger', isCorrect: false, feedback: 'Aggrave.' },
      ],
      hint: 'Pense effet immédiat vs futur.',
    },
    {
      id: 'c5-sol-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'systemic-change',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir « actions individuelles inutiles ».',
      question: 'Vrai ou faux ?',
      card: { title: 'Mes actions individuelles ne changent rien à l\'échelle planétaire.', subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Effet collectif documenté.',
      incorrectFeedback: 'Faux. Comportements émergents.',
      explanation: 'Réduction viande, transports, etc.',
      misconceptionId: 'local-actions-no-impact',
    },
    {
      id: 'c5-sol-disc-6-build',
      type: 'STORY',
      conceptId: 'climate-action',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Étendre aux solutions systémiques.',
      screens: [
        {
          text: 'Mais les solutions ne sont pas qu\'individuelles : régulations, énergies renouvelables, gestion de l\'eau, agriculture régénérative.',
          imagePrompt: 'Mosaïque de solutions',
          imageUrl: FIELD_IMAGE,
          kind: 'build-up',
          boldTokens: ['systémiques'],
        },
      ],
    },
    {
      id: 'c5-sol-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Hiérarchiser les leviers.',
      instruction: "Du plus immédiat au plus long terme :",
      axis: 'horizontal',
      axisRationale: 'Gradient temporel.',
      slotCount: 3,
      items: [
        { id: 'cso-1', text: '🛡️ Préserver l\'existant' },
        { id: 'cso-2', text: '🌱 Restaurer' },
        { id: 'cso-3', text: '🔬 Innover' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : préserver maintenant, innover sur durée.',
    },
    {
      id: 'c5-sol-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint préservation.',
      question: 'Vrai ou faux ?',
      card: { title: 'Préserver une forêt ancienne est plus efficace que la reboiser après destruction.', subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Préservation > reboisement.',
    },
    {
      id: 'c5-sol-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint Yellowstone.',
      question: 'Vrai ou faux ?',
      card: { title: "La réintroduction du loup à Yellowstone a restauré tout un écosystème.", subtitle: 'Sprint 2' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Cas emblématique.',
      incorrectFeedback: 'Si. Cascade trophique inverse.',
      explanation: 'Vu chap 2.',
    },
    {
      id: 'c5-sol-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: 'Identifier le mix optimal.',
      question: 'Quel mix d\'actions est le plus efficace ?',
      options: [
        { text: 'Préserver + restaurer + innover en parallèle', isCorrect: true, feedback: 'Exact. Trois leviers ensemble.' },
        { text: 'Planter uniquement', isCorrect: false, feedback: 'Insuffisant.', misconceptionId: 'planting-trees-fixes-climate' },
        { text: 'Ne rien faire', isCorrect: false, feedback: 'Faux.', misconceptionId: 'local-actions-no-impact' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c5-sol-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Catégoriser les actions.',
      instruction: 'Trie ces actions :',
      axis: 'horizontal',
      axisRationale: 'Mapping.',
      slotCount: 4,
      items: [
        { id: 'csb-1', text: '🛡️ Aire protégée' },
        { id: 'csb-2', text: '🌳 Reboisement' },
        { id: 'csb-3', text: '☀️ Énergie solaire' },
        { id: 'csb-4', text: '🌾 Agroécologie' },
        { id: 'csb-distract', text: '🚗 Voiture diesel', isDistractor: true },
      ],
      correctFeedback: 'Excellent. Le diesel n\'est pas une solution.',
      incorrectFeedback: 'Indice : un seul item n\'est pas une solution.',
    },
    {
      id: 'c5-sol-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser : agir mieux.',
      question: 'Comment agir efficacement pour le vivant ?',
      options: [
        { text: 'Mix individuel + collectif + systémique', isCorrect: true, feedback: 'Exact.' },
        { text: 'Tout individuel', isCorrect: false, feedback: 'Insuffisant seul.' },
        { text: 'Tout collectif', isCorrect: false, feedback: 'Aussi insuffisant seul.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c5-sol-pool-sw-marine',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Aires marines protégées.',
      question: 'Vrai ou faux ?',
      card: { title: "Les réserves marines protégées peuvent restaurer des stocks de poissons.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Effet « débordement ».',
    },
    {
      id: 'c5-sol-pool-sw-renew',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Énergies renouvelables.',
      question: 'Vrai ou faux ?',
      card: { title: 'Le coût des énergies solaire et éolienne a chuté de plus de 80 % en 10 ans.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. AIE.',
      incorrectFeedback: 'Si. Démocratisation rapide.',
      explanation: 'Loi de Wright.',
    },
    {
      id: 'c5-sol-pool-sw-recovery',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Récupération possible.',
      question: 'Vrai ou faux ?',
      card: { title: 'Des espèces ont déjà été sauvées de l\'extinction grâce à la conservation.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Bison américain, condor, oryx.',
      incorrectFeedback: 'Si.',
      explanation: 'Action ciblée = effet réel.',
    },
    {
      id: 'c5-sol-pool-sw-restore-cost',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Préserver moins cher que restaurer.',
      question: 'Vrai ou faux ?',
      card: { title: 'Préserver coûte moins cher que restaurer.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Souvent 10× moins cher.',
      incorrectFeedback: 'Si.',
      explanation: 'Restaurer = lent et coûteux.',
      misconceptionId: 'planting-trees-fixes-climate',
    },
    {
      id: 'c5-sol-pool-q-leverage',
      type: 'QUIZ',
      conceptId: 'systemic-change',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Levier majeur.',
      question: 'Quel levier individuel a le plus gros impact carbone par personne ?',
      options: [
        { text: 'Avoir un enfant de moins', isCorrect: true, feedback: 'Exact. ~58 t CO₂/an évitées (Wynes & Nicholas 2017).' },
        { text: 'Recycler', isCorrect: false, feedback: 'Effet bien plus faible.' },
        { text: 'Éteindre la lumière', isCorrect: false, feedback: 'Marginal.' },
      ],
    },
    {
      id: 'c5-sol-pool-q-meta',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Choisir l\'approche juste.',
      question: 'Quelle approche est la plus efficace ?',
      options: [
        { text: 'Combiner préserver + restaurer + innover', isCorrect: true, feedback: 'Exact.' },
        { text: 'Tout miser sur le reboisement', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'planting-trees-fixes-climate' },
        { text: 'Ne rien changer', isCorrect: false, feedback: 'Faux.', misconceptionId: 'local-actions-no-impact' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c5-sol-pool-q-conservation',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Conservation efficace.',
      question: 'Quelle stratégie de conservation est la plus efficace ?',
      options: [
        { text: 'Aires protégées + corridors + lutte contre invasives', isCorrect: true, feedback: 'Exact.' },
        { text: 'Une seule réserve isolée', isCorrect: false, feedback: 'Souvent trop petite seule.' },
        { text: 'Aucune protection', isCorrect: false, feedback: 'Faux.' },
      ],
    },
    {
      id: 'c5-sol-pool-d-mix',
      type: 'DRAG_DROP',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Mix de solutions.',
      instruction: 'Place ces solutions :',
      axis: 'horizontal',
      axisRationale: 'Mapping.',
      slotCount: 3,
      items: [
        { id: 'cso2-1', text: '🛡️ Préserver' },
        { id: 'cso2-2', text: '🌱 Restaurer' },
        { id: 'cso2-3', text: '🔬 Innover' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : 3 leviers en parallèle.',
    },
    {
      id: 'c5-sol-pool-d-impact',
      type: 'DRAG_DROP',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser actions.',
      instruction: 'Du plus haut au plus bas impact carbone :',
      axis: 'vertical',
      axisRationale: 'Pyramide d\'impact.',
      slotCount: 4,
      items: [
        { id: 'csi-1', text: '✈️ Vol long-courrier' },
        { id: 'csi-2', text: '🚗 Voiture quotidienne' },
        { id: 'csi-3', text: '🥩 Régime carné' },
        { id: 'csi-4', text: '♻️ Recyclage' },
      ],
      correctFeedback: 'Excellent. Vol >>> recyclage.',
      incorrectFeedback: 'Indice : transports puis alimentation puis tri.',
    },
    {
      id: 'c5-sol-pool-sw-pollinator-friendly',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Action pour pollinisateurs.',
      question: 'Vrai ou faux ?',
      card: { title: 'Planter des fleurs sauvages dans son jardin aide les pollinisateurs.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Diversité florale = nourriture.',
      incorrectFeedback: 'Si.',
      explanation: 'Effet local + agrégé.',
      interleavesConceptIds: ['pollination-agents'],
    },
    {
      id: 'c5-sol-pool-sw-meat',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Régime alimentaire.',
      question: 'Vrai ou faux ?',
      card: { title: "Réduire la viande dans son alimentation est une des actions les plus efficaces pour le climat.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Poore & Nemecek 2018.',
      incorrectFeedback: 'Si.',
      explanation: 'Empreinte 10-50× plus élevée pour viande.',
    },
    {
      id: 'c5-sol-pool-q-vote',
      type: 'QUIZ',
      conceptId: 'systemic-change',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Action systémique.',
      question: 'Quelle action a le plus d\'effet systémique ?',
      options: [
        { text: 'Voter pour des politiques climatiques + s\'organiser collectivement', isCorrect: true, feedback: 'Exact.' },
        { text: 'Recycler son verre', isCorrect: false, feedback: 'Marginal seul.' },
        { text: 'Boire moins de café', isCorrect: false, feedback: 'Marginal.' },
      ],
    },
  ],

  authoredLegendary: [
    {
      id: 'c5-sol-leg-1-hook',
      type: 'STORY',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le boss.',
      screens: [
        {
          text: '14 questions pour valider que tu connais les leviers d\'action efficaces.',
          imagePrompt: 'Personne avec arsenal symbolique',
          imageUrl: FIELD_IMAGE,
          kind: 'hook',
          boldTokens: ['arsenal'],
        },
      ],
    },
    {
      id: 'c5-sol-leg-2-q',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Préserver vs reboiser.',
      question: 'Quelle action a le meilleur ratio effort/impact climatique immédiat ?',
      options: [
        { text: 'Préserver les forêts existantes', isCorrect: true, feedback: 'Exact.' },
        { text: 'Reboiser uniquement', isCorrect: false, feedback: 'Effet à 30+ ans.', misconceptionId: 'planting-trees-fixes-climate' },
        { text: 'Bétonner', isCorrect: false, feedback: 'Aggrave.' },
      ],
    },
    {
      id: 'c5-sol-leg-3-q',
      type: 'QUIZ',
      conceptId: 'systemic-change',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Actions individuelles.',
      question: 'Mes actions individuelles ont-elles un impact ?',
      options: [
        { text: 'Oui, agrégées et combinées avec actions systémiques', isCorrect: true, feedback: 'Exact.' },
        { text: 'Non, jamais', isCorrect: false, feedback: 'Misconception.', misconceptionId: 'local-actions-no-impact' },
        { text: 'Seulement individuel suffit', isCorrect: false, feedback: 'Trop limité.' },
      ],
    },
    {
      id: 'c5-sol-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser actions.',
      instruction: 'Du plus haut au plus bas impact :',
      axis: 'vertical',
      axisRationale: 'Pyramide d\'impact.',
      slotCount: 5,
      items: [
        { id: 'cslg-1', text: '✈️ Vol long-courrier' },
        { id: 'cslg-2', text: '🥩 Régime carné' },
        { id: 'cslg-3', text: '🚗 Voiture' },
        { id: 'cslg-4', text: '♻️ Recyclage' },
        { id: 'cslg-5', text: '💡 Ampoules LED' },
        { id: 'cslg-distract', text: '🛡️ Plaisanterie', isDistractor: true },
      ],
      correctFeedback: 'Excellent.',
      incorrectFeedback: 'Indice : un item est faux.',
    },
    {
      id: 'c5-sol-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Sprint reboisement.',
      question: 'Vrai ou faux ?',
      card: { title: 'Préserver est plus efficace que reboiser.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Effet immédiat.',
      misconceptionId: 'planting-trees-fixes-climate',
    },
    {
      id: 'c5-sol-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Sprint succès.',
      question: 'Vrai ou faux ?',
      card: { title: 'Des programmes de conservation ont déjà sauvé des espèces (bison, condor, oryx).', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Cas réels.',
    },
    {
      id: 'c5-sol-leg-7-q',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Définition juste.',
      question: 'Comment décrire « l\'arsenal de l\'espoir » ?',
      options: [
        { text: 'Mix de préservation, restauration et innovation', isCorrect: true, feedback: 'Exact.' },
        { text: 'Solution unique miracle', isCorrect: false, feedback: 'Faux.' },
        { text: 'Inutile', isCorrect: false, feedback: 'Faux.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c5-sol-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Lien chap précédents + solutions.',
      instruction: 'Trie ces actions selon leur cible :',
      axis: 'horizontal',
      axisRationale: 'Mapping cause-cible.',
      slotCount: 4,
      items: [
        { id: 'cslr-1', text: '🌳 Préservation forêts (carbone)' },
        { id: 'cslr-2', text: '🐝 Fleurs sauvages (pollinisateurs)' },
        { id: 'cslr-3', text: '🪸 Crèmes solaires safe (récifs)' },
        { id: 'cslr-4', text: '🌱 Compost (sol vivant)' },
      ],
      correctFeedback: 'Parfait.',
      incorrectFeedback: 'Indice : action → bénéficiaire.',
      interleavesConceptIds: ['carbon-cycle-storage', 'pollination-agents', 'coral-biology', 'soil-living'],
    },
    {
      id: 'c5-sol-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'systemic-change',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint vote.',
      question: 'Vrai ou faux ?',
      card: { title: "Voter pour des politiques climatiques amplifie l'impact individuel.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si.',
      explanation: 'Action démultiplicatrice.',
    },
    {
      id: 'c5-sol-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint renouvelable.',
      question: 'Vrai ou faux ?',
      card: { title: "Le coût des énergies solaire/éolienne a chuté de plus de 80 % en une décennie.", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai.',
      incorrectFeedback: 'Si. AIE.',
      explanation: 'Démocratisation.',
    },
    {
      id: 'c5-sol-leg-11-q',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthèse.',
      question: 'Pourquoi mixer individuel + systémique ?',
      options: [
        { text: 'L\'un soutient l\'autre : agrégat individuel + cadre collectif', isCorrect: true, feedback: 'Exact.' },
        { text: 'Inutile', isCorrect: false, feedback: 'Faux.' },
        { text: 'Sufficient l\'un seul', isCorrect: false, feedback: 'Insuffisant.' },
      ],
    },
    {
      id: 'c5-sol-leg-12-reveal',
      type: 'STORY',
      conceptId: 'climate-action',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective.',
      screens: [
        {
          text: 'Tu connais les leviers : préserver, restaurer, innover. À toi de choisir tes batailles. Aucun choix n\'est neutre.',
          imagePrompt: 'Carrefour avec 3 chemins',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['choisir'],
        },
      ],
    },
    {
      id: 'c5-sol-leg-13-q',
      type: 'QUIZ',
      conceptId: 'climate-action',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Action concrète.',
      question: 'Quelle action concrète est la plus efficace ?',
      options: [
        { text: 'Combiner alimentation moins carnée + transports + vote climatique', isCorrect: true, feedback: 'Exact.' },
        { text: 'Recycler le verre seulement', isCorrect: false, feedback: 'Marginal.' },
        { text: 'Ne rien faire', isCorrect: false, feedback: 'Faux.', misconceptionId: 'local-actions-no-impact' },
      ],
    },
    {
      id: 'c5-sol-leg-14-closure',
      type: 'STORY',
      conceptId: 'climate-action',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer Permaculture.',
      screens: [
        {
          text: 'Tu connais l\'arsenal. Place à une approche systémique de l\'agriculture : la permaculture.',
          imagePrompt: 'Jardin permacole',
          imageUrl: SPROUT_IMAGE,
          kind: 'closure',
          boldTokens: ['permaculture'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'c5-sol-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir les leviers d\'action.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'c5-sol-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser les leviers.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'c5-sol-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler les solutions.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 3 },
    },
    {
      id: 'c5-sol-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 50, label: '50 Graines' },
    },
  ],
}
