export const BASE_UI_COMPONENTS = [
  'Accordion',
  'AlertDialog',
  'Autocomplete',
  'Avatar',
  'Button',
  'Checkbox',
  'CheckboxGroup',
  'Collapsible',
  'Combobox',
  'ContextMenu',
  'Dialog',
  'Field',
  'Fieldset',
  'Form',
  'Input',
  'Menu',
  'Menubar',
  'Meter',
  'NavigationMenu',
  'NumberField',
  'Popover',
  'PreviewCard',
  'Progress',
  'Radio',
  'ScrollArea',
  'Select',
  'Separator',
  'Slider',
  'Switch',
  'Tabs',
  'Toast',
  'Toggle',
  'ToggleGroup',
  'Toolbar',
  'Tooltip',
] as const

export type BaseUiComponentName = (typeof BASE_UI_COMPONENTS)[number]

export const BASE_UI_PRODUCTION_COMPONENTS = [
  'Accordion',
  'AlertDialog',
  'Avatar',
  'Button',
  'Checkbox',
  'CheckboxGroup',
  'Collapsible',
  'Combobox',
  'Dialog',
  'Field',
  'Fieldset',
  'Form',
  'Input',
  'Menu',
  'Menubar',
  'Meter',
  'NavigationMenu',
  'NumberField',
  'Popover',
  'Progress',
  'Radio',
  'ScrollArea',
  'Select',
  'Separator',
  'Slider',
  'Switch',
  'Tabs',
  'Toast',
  'Toggle',
  'ToggleGroup',
  'Toolbar',
  'Tooltip',
] as const

export type BaseUiProductionComponentName = (typeof BASE_UI_PRODUCTION_COMPONENTS)[number]
