import type { AcademyUnitDefinition } from '../../../schema'

const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const SPROUT_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'

export const lifeFactoryUnit: AcademyUnitDefinition = {
  id: 'chapter-1-life-factory',
  slug: 'la-fabrique-du-vivant',
  chapterId: 'chapter-1',
  schemaVersion: 2,
  title: 'La Fabrique du Vivant',
  shortTitle: 'Fabrique',
  pathLabel: 'Synthèse',
  subtitle: 'Assemble les forces invisibles en un système vivant cohérent.',
  concept: 'Énergie, matière, croissance, recyclage',
  conceptIds: ['ecosystem-flow', 'matter-cycle', 'food-chain-link'],
  kind: 'foundation',
  iconKey: 'atom',
  masteryGoal: "Construire mentalement un écosystème complet à partir de ses 4 piliers.",
  order: 6,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: 'Comprendre comment énergie et matière circulent dans un écosystème.',
  mascot: 'ondine',
  rewardAmount: 15,

  authoredDiscovery: [
    {
      id: 'c1-fabr-disc-1-hook',
      type: 'STORY',
      conceptId: 'ecosystem-flow',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser la grande question : qu\'est-ce qu\'un écosystème ?',
      screens: [
        {
          text: "Tu as les briques (Soleil, eau, sol, photosynthèse). Mais une brique seule ne fait pas une maison. Comment tout cela tient-il ensemble ?",
          imagePrompt: 'Forêt vue d\'en haut avec les 4 forces visibles',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['ensemble'],
        },
      ],
    },
    {
      id: 'c1-fabr-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'ecosystem-flow',
      difficulty: 'easy',
      cognitiveTags: ['pre-test'],
      learningObjective: 'Tester l\'idée d\'écosystème comme réseau.',
      question: 'Vrai ou faux ?',
      card: { title: "Un écosystème est juste une collection d\'animaux qui vivent au même endroit.", subtitle: 'Intuition' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bien vu. C\'est bien plus qu\'une collection : c\'est un réseau d\'échanges.',
      incorrectFeedback: 'Trop simple. Un écosystème inclut aussi les flux d\'énergie et de matière, pas que les espèces.',
      explanation: 'Écosystème = vivants + non-vivants + flux entre eux.',
    },
    {
      id: 'c1-fabr-disc-3-reveal',
      type: 'STORY',
      conceptId: 'ecosystem-flow',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: "Révéler l'écosystème comme flux d'énergie et de matière.",
      screens: [
        {
          text: "Un écosystème, c'est de l'énergie qui traverse (Soleil → producteurs → consommateurs) ET de la matière qui circule en boucle.",
          imagePrompt: 'Schéma d\'un écosystème avec flèches d\'énergie et de matière',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['traverse'],
        },
        {
          text: "L'énergie va à sens unique (et se dissipe). La matière, elle, est recyclée par les décomposeurs : elle revient toujours à la base.",
          imagePrompt: 'Cycle de la matière avec décomposeurs',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['recyclée'],
        },
      ],
    },
    {
      id: 'c1-fabr-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'ecosystem-flow',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Différencier flux d\'énergie et flux de matière.',
      question: "Quelle différence entre énergie et matière dans un écosystème ?",
      options: [
        { text: "L'énergie traverse à sens unique, la matière circule en boucle", isCorrect: true, feedback: 'Exact. C\'est la double règle fondamentale des écosystèmes.' },
        { text: "Elles font la même chose", isCorrect: false, feedback: 'Non. L\'énergie se dissipe, la matière se recycle.' },
        { text: "L'énergie disparaît, la matière reste", isCorrect: false, feedback: 'Aucune des deux ne disparaît : l\'énergie se dissipe en chaleur.' },
      ],
      hint: "L'une va d'un point à un autre. L'autre fait des allers-retours.",
    },
    {
      id: 'c1-fabr-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'matter-cycle',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir l\'idée que la matière disparaît.',
      question: 'Vrai ou faux ?',
      card: { title: "Quand quelque chose meurt et pourrit, sa matière disparaît vraiment.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Loi de conservation : la matière change de forme, elle ne disparaît pas.',
      incorrectFeedback: 'Faux. Les décomposeurs la transforment en nutriments. Tout est recyclé.',
      explanation: 'Lavoisier appliqué à l\'écologie.',
      misconceptionId: 'matter-disappears',
    },
    {
      id: 'c1-fabr-disc-6-build',
      type: 'STORY',
      conceptId: 'food-chain-link',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Introduire les 3 grands rôles : producteurs, consommateurs, décomposeurs.',
      screens: [
        {
          text: "Trois grands rôles : les producteurs (plantes, algues), les consommateurs (animaux), les décomposeurs (champignons, bactéries).",
          imagePrompt: 'Triade producteurs-consommateurs-décomposeurs illustrée',
          imageUrl: SPROUT_IMAGE,
          kind: 'build-up',
          boldTokens: ['rôles'],
        },
      ],
    },
    {
      id: 'c1-fabr-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Reconstituer le cycle vivant complet.',
      instruction: 'Ordonne le cycle complet :',
      axis: 'horizontal',
      axisRationale: 'Chronologie du cycle écologique.',
      slotCount: 4,
      items: [
        { id: 'lf-1', text: '🌱 Producteur' },
        { id: 'lf-2', text: '🐇 Consommateur' },
        { id: 'lf-3', text: '🍄 Décomposeur' },
        { id: 'lf-4', text: '🪨 Nutriments dans sol' },
      ],
      correctFeedback: 'Parfait. La boucle est fermée : tout retourne au sol pour repartir.',
      incorrectFeedback: 'Indice : producteur d\'abord, décomposeur juste avant le retour au sol.',
    },
    {
      id: 'c1-fabr-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'ecosystem-flow',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : énergie à sens unique.',
      question: 'Vrai ou faux ?',
      card: { title: "L'énergie circule à double sens : elle revient au Soleil.", subtitle: 'Sprint 1' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. L\'énergie va du Soleil aux organismes, puis se dissipe en chaleur. Elle ne revient pas.',
      incorrectFeedback: 'Non. À chaque étape, ~90 % de l\'énergie est perdue en chaleur.',
      explanation: 'Pyramide énergétique : ça monte, ça ne descend pas.',
    },
    {
      id: 'c1-fabr-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'matter-cycle',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : matière en boucle.',
      question: 'Vrai ou faux ?',
      card: { title: "La même molécule de carbone peut passer du sol à un arbre, à un animal, puis revenir au sol.", subtitle: 'Sprint 2' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. C\'est exactement ce qui rend les cycles biogéochimiques.',
      incorrectFeedback: 'Si. Les atomes voyagent en boucle entre les compartiments.',
      explanation: 'Cycle du carbone : sol → plante → animal → décomposeur → sol.',
    },
    {
      id: 'c1-fabr-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: 'Identifier l\'élément qui ferme la boucle.',
      question: 'Quel groupe ferme la boucle écosystémique ?',
      options: [
        { text: 'Les décomposeurs (champignons, bactéries, vers)', isCorrect: true, feedback: 'Exact. Sans eux, les nutriments resteraient bloqués dans le mort.' },
        { text: 'Les super-prédateurs', isCorrect: false, feedback: 'Ils sont en haut, ils ne ferment pas la boucle.' },
        { text: 'Les producteurs', isCorrect: false, feedback: 'Ils ouvrent la boucle, ils ne la ferment pas.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-fabr-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser une pyramide trophique complète.',
      instruction: 'Empile la pyramide écosystémique :',
      axis: 'vertical',
      axisRationale: "L'axe vertical figure la pyramide trophique : producteurs en bas, super-prédateurs au sommet.",
      slotCount: 5,
      items: [
        { id: 'lfb-1', text: '🌿 Producteur' },
        { id: 'lfb-2', text: '🐛 Herbivore' },
        { id: 'lfb-3', text: '🐦 Carnivore' },
        { id: 'lfb-4', text: '🦅 Super-prédateur' },
        { id: 'lfb-5', text: '🍄 Décomposeurs (partout)' },
        { id: 'lfb-distract', text: '☀️ Soleil', isDistractor: true },
      ],
      correctFeedback: "Excellent. Le Soleil est dehors : il alimente, mais ne fait pas partie de la pyramide.",
      incorrectFeedback: 'Indice : un seul item est externe à la pyramide vivante.',
    },
    {
      id: 'c1-fabr-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'ecosystem-flow',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser la définition d\'un écosystème.',
      question: 'Quelle définition correspond le mieux à un écosystème ?',
      options: [
        { text: 'Un réseau d\'organismes et de flux d\'énergie / matière interconnectés', isCorrect: true, feedback: 'Exact. Réseau + flux = écosystème.' },
        { text: 'Une simple liste d\'espèces qui vivent ensemble', isCorrect: false, feedback: 'Trop pauvre. Les flux sont essentiels.' },
        { text: 'Un endroit où il n\'y a que des plantes', isCorrect: false, feedback: 'Très restrictif. Tout vivant fait partie de l\'écosystème.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c1-fabr-pool-sw-energy-loss',
      type: 'SWIPE',
      conceptId: 'ecosystem-flow',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "Comprendre la perte d'énergie à chaque niveau.",
      question: 'Vrai ou faux ?',
      card: { title: 'À chaque niveau de la chaîne, ~90 % de l\'énergie est perdue en chaleur.', subtitle: 'Pyramide' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. C'est pourquoi il y a peu de super-prédateurs.",
      incorrectFeedback: 'Si. Règle des 10 %. Énergie disponible chute drastiquement.',
      explanation: 'Pyramide d\'Eltonien : 100 plantes nourrissent 10 herbivores qui nourrissent 1 carnivore.',
    },
    {
      id: 'c1-fabr-pool-sw-decomp-essential',
      type: 'SWIPE',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Importance des décomposeurs.',
      question: 'Vrai ou faux ?',
      card: { title: 'Sans décomposeurs, la planète serait submergée de matière morte.', subtitle: 'Recyclage' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Sans eux, les nutriments resteraient bloqués dans le mort.',
      incorrectFeedback: 'Si. Tout serait paralysé en quelques années.',
      explanation: 'Décomposeurs = recycleurs vitaux.',
    },
    {
      id: 'c1-fabr-pool-sw-pyramid',
      type: 'SWIPE',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Comprendre la rareté des super-prédateurs.',
      question: 'Vrai ou faux ?',
      card: { title: 'Il y a beaucoup moins de loups que de lapins dans une forêt.', subtitle: 'Pyramide' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Énergie limitée à chaque étage.',
      incorrectFeedback: 'Si. Pyramide trophique : moins on monte, moins il y en a.',
      explanation: 'Sommet = très peu, base = beaucoup.',
    },
    {
      id: 'c1-fabr-pool-sw-detritus',
      type: 'SWIPE',
      conceptId: 'matter-cycle',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Le détritivore mange du mort.',
      question: 'Vrai ou faux ?',
      card: { title: 'Un cloporte mange surtout des feuilles mortes, pas des feuilles vivantes.', subtitle: 'Décomposeurs' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Cloporte = détritivore.',
      incorrectFeedback: 'Si. Il participe au recyclage de la litière.',
      explanation: 'Détritivore = mange du mort, prépare le travail des bactéries.',
    },
    {
      id: 'c1-fabr-pool-q-stable',
      type: 'QUIZ',
      conceptId: 'ecosystem-flow',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: "Identifier ce qui rend un écosystème stable.",
      question: "Qu'est-ce qui rend un écosystème stable face aux perturbations ?",
      options: [
        { text: 'Sa biodiversité (variété d\'espèces et de rôles)', isCorrect: true, feedback: 'Exact. Plus de diversité = plus de réponses possibles aux changements.' },
        { text: 'Le fait qu\'il y ait peu d\'espèces', isCorrect: false, feedback: 'Inverse. La monoculture est très fragile.' },
        { text: 'L\'absence d\'humains', isCorrect: false, feedback: 'L\'humain peut faire partie d\'un écosystème stable.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-fabr-pool-q-keystone',
      type: 'QUIZ',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Identifier une espèce-clé.',
      question: "Qu'est-ce qu'une espèce-clé (keystone) ?",
      options: [
        { text: 'Une espèce dont la disparition cause un effet domino énorme', isCorrect: true, feedback: 'Exact. Loup à Yellowstone, étoile de mer Pisaster, etc.' },
        { text: 'L\'espèce la plus nombreuse', isCorrect: false, feedback: 'Pas forcément. Une espèce-clé peut être rare.' },
        { text: 'L\'espèce la plus grosse', isCorrect: false, feedback: 'La taille n\'est pas le critère.' },
      ],
    },
    {
      id: 'c1-fabr-pool-q-trophic-cascade',
      type: 'QUIZ',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Comprendre la cascade trophique.',
      question: "Que se passe-t-il quand on supprime un super-prédateur ?",
      options: [
        { text: 'Les herbivores explosent en nombre, et la végétation s\'effondre', isCorrect: true, feedback: 'Exact. Cascade trophique : effet en chaîne descendant.' },
        { text: 'Rien ne change', isCorrect: false, feedback: 'Faux. Effet documenté avec le loup à Yellowstone.', misconceptionId: 'predators-are-villains' },
        { text: 'L\'écosystème devient plus stable', isCorrect: false, feedback: 'Inverse. Un super-prédateur stabilise les populations.', misconceptionId: 'predators-are-villains' },
      ],
    },
    {
      id: 'c1-fabr-pool-q-net-energy',
      type: 'QUIZ',
      conceptId: 'ecosystem-flow',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Identifier la source de l\'énergie qui traverse.',
      question: "D'où vient l'énergie qui traverse n'importe quel écosystème terrestre ?",
      options: [
        { text: 'Du Soleil, via la photosynthèse', isCorrect: true, feedback: 'Exact. Tout part de là.' },
        { text: 'De la chaleur du sol', isCorrect: false, feedback: 'La chaleur du sol existe mais ne nourrit pas la chaîne.' },
        { text: 'De l\'énergie chimique des roches', isCorrect: false, feedback: 'Vrai pour les sources hydrothermales, mais pas pour les écosystèmes terrestres.' },
      ],
    },
    {
      id: 'c1-fabr-pool-d-energy-flow',
      type: 'DRAG_DROP',
      conceptId: 'ecosystem-flow',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Reconstituer le flux d\'énergie.',
      instruction: 'Ordonne le flux d\'énergie :',
      axis: 'horizontal',
      axisRationale: "Sens unique de l'énergie.",
      slotCount: 4,
      items: [
        { id: 'lfp-1', text: '☀️ Soleil' },
        { id: 'lfp-2', text: '🌿 Plante' },
        { id: 'lfp-3', text: '🐇 Lapin' },
        { id: 'lfp-4', text: '🦊 Renard' },
      ],
      correctFeedback: 'Parfait. Sens unique : Soleil → producteur → consommateurs.',
      incorrectFeedback: 'Indice : sens unique, jamais d\'inverse.',
    },
    {
      id: 'c1-fabr-pool-d-roles',
      type: 'DRAG_DROP',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les rôles écosystémiques.',
      instruction: 'Du producteur au décomposeur :',
      axis: 'horizontal',
      axisRationale: 'Chronologie du flux de matière.',
      slotCount: 3,
      items: [
        { id: 'lfr-1', text: '🌱 Producteur' },
        { id: 'lfr-2', text: '🐇 Consommateur' },
        { id: 'lfr-3', text: '🍄 Décomposeur' },
      ],
      correctFeedback: 'Parfait. Triade fondamentale.',
      incorrectFeedback: 'Indice : qui fabrique, qui mange, qui recycle.',
    },
    {
      id: 'c1-fabr-pool-sw-niche',
      type: 'SWIPE',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Comprendre la notion de niche écologique.',
      question: 'Vrai ou faux ?',
      card: { title: 'Deux espèces avec exactement la même niche peuvent coexister durablement.', subtitle: 'Niches' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Principe d\'exclusion compétitive (Gause).',
      incorrectFeedback: 'Non. La compétition élimine ou déplace l\'une des deux.',
      explanation: 'Coexistence = niches différentes.',
    },
    {
      id: 'c1-fabr-pool-sw-biodiv-stable',
      type: 'SWIPE',
      conceptId: 'ecosystem-flow',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Lien biodiversité-stabilité.',
      question: 'Vrai ou faux ?',
      card: { title: 'Plus un écosystème est divers, plus il est résilient face aux chocs.', subtitle: 'Stabilité' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Plus de redondance fonctionnelle = plus de stabilité.',
      incorrectFeedback: 'Si. C\'est un consensus scientifique fort.',
      explanation: 'Diversité = assurance écosystémique.',
    },
  ],

  authoredLegendary: [
    {
      id: 'c1-fabr-leg-1-hook',
      type: 'STORY',
      conceptId: 'ecosystem-flow',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le défi : maîtriser le concept d\'écosystème.',
      screens: [
        {
          text: '14 questions pour assembler ce que tu sais en une vision d\'écosystème complet.',
          imagePrompt: 'Forêt entière vue d\'en haut',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['assembler'],
        },
      ],
    },
    {
      id: 'c1-fabr-leg-2-q',
      type: 'QUIZ',
      conceptId: 'ecosystem-flow',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Différencier flux énergie vs matière.',
      question: 'Quelle est la grande différence entre énergie et matière dans un écosystème ?',
      options: [
        { text: 'L\'énergie traverse à sens unique, la matière circule en boucle', isCorrect: true, feedback: 'Exact.' },
        { text: 'Les deux disparaissent', isCorrect: false, feedback: 'Aucune ne disparaît.' },
        { text: 'Aucune différence', isCorrect: false, feedback: 'Différence majeure.' },
      ],
    },
    {
      id: 'c1-fabr-leg-3-q',
      type: 'QUIZ',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Identifier le rôle des prédateurs.',
      question: 'Que fait un super-prédateur dans un écosystème ?',
      options: [
        { text: 'Il régule les populations de proies et stabilise tout', isCorrect: true, feedback: 'Exact. Cas du loup à Yellowstone.' },
        { text: 'Il déstabilise tout', isCorrect: false, feedback: 'Inverse. Sa disparition déstabilise.', misconceptionId: 'predators-are-villains' },
        { text: 'Il ne sert à rien', isCorrect: false, feedback: 'Faux. Espèce-clé.', misconceptionId: 'predators-are-villains' },
      ],
    },
    {
      id: 'c1-fabr-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'ecosystem-flow',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser un écosystème complet.',
      instruction: 'Empile la pyramide écosystémique du sol au sommet :',
      axis: 'vertical',
      axisRationale: 'Pyramide trophique.',
      slotCount: 5,
      items: [
        { id: 'lfle-1', text: '🌿 Producteurs' },
        { id: 'lfle-2', text: '🐛 Herbivores' },
        { id: 'lfle-3', text: '🐦 Carnivores' },
        { id: 'lfle-4', text: '🦅 Super-prédateurs' },
        { id: 'lfle-5', text: '🍄 Décomposeurs (transversal)' },
        { id: 'lfle-distract', text: '🪨 Roches', isDistractor: true },
      ],
      correctFeedback: 'Excellent. Les roches sont du substrat, pas des vivants.',
      incorrectFeedback: 'Indice : un seul item n\'est pas vivant.',
    },
    {
      id: 'c1-fabr-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'matter-cycle',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Conservation de la matière.',
      question: 'Vrai ou faux ?',
      card: { title: 'La matière d\'un être vivant disparaît à sa mort.', subtitle: 'Conservation' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Elle est recyclée par les décomposeurs.',
      incorrectFeedback: 'Non. Loi de conservation : elle change de forme.',
      explanation: 'Cycle de la matière.',
      misconceptionId: 'matter-disappears',
    },
    {
      id: 'c1-fabr-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'ecosystem-flow',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Énergie pyramidale.',
      question: 'Vrai ou faux ?',
      card: { title: 'Il y a beaucoup plus de plantes que de carnivores dans une forêt.', subtitle: 'Pyramide' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Pyramide énergétique : ~10 % par étage.',
      incorrectFeedback: 'Si. La base est toujours énormément plus large.',
      explanation: 'Règle des 10 %.',
    },
    {
      id: 'c1-fabr-leg-7-q',
      type: 'QUIZ',
      conceptId: 'ecosystem-flow',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Choisir la définition juste.',
      question: 'Quelle définition d\'un écosystème est la plus correcte ?',
      options: [
        { text: 'Réseau d\'êtres vivants + non-vivants + flux d\'énergie/matière', isCorrect: true, feedback: 'Exact. Vivants + abiotique + flux.' },
        { text: 'Liste d\'espèces qui partagent un territoire', isCorrect: false, feedback: 'Trop limité. Manque les flux.' },
        { text: 'Les plantes d\'un endroit', isCorrect: false, feedback: 'Trop restrictif.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-fabr-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'ecosystem-flow',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Lier les 4 piliers à un écosystème.',
      instruction: 'Reconstitue ce qu\'il faut pour un écosystème viable :',
      axis: 'horizontal',
      axisRationale: 'Chaîne de dépendances.',
      slotCount: 4,
      items: [
        { id: 'lfli-1', text: '☀️ Énergie (Soleil)' },
        { id: 'lfli-2', text: '💧 Eau (cycle)' },
        { id: 'lfli-3', text: '🌱 Sol vivant' },
        { id: 'lfli-4', text: '🍃 Photosynthèse + chaîne' },
      ],
      correctFeedback: 'Parfait. Les 4 piliers, dans l\'ordre logique.',
      incorrectFeedback: 'Indice : énergie d\'abord, vivant à la fin.',
      interleavesConceptIds: ['sun-energy-source', 'water-cycle-evaporation', 'soil-living', 'photosynthesis-mechanism'],
    },
    {
      id: 'c1-fabr-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Sprint : prédateurs régulateurs.',
      question: 'Vrai ou faux ?',
      card: { title: 'Supprimer un prédateur fragilise tout l\'écosystème.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Cascade trophique documentée.',
      incorrectFeedback: 'Si. Les prédateurs régulent, leur disparition crée un déséquilibre en chaîne.',
      explanation: 'Yellowstone : retour du loup → restauration des rivières.',
      misconceptionId: 'predators-are-villains',
    },
    {
      id: 'c1-fabr-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'matter-cycle',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : décomposeurs vitaux.',
      question: 'Vrai ou faux ?',
      card: { title: 'Sans décomposeurs, les nutriments restent bloqués dans la matière morte.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Le cycle s\'arrêterait.',
      incorrectFeedback: 'Si. C\'est leur fonction écologique principale.',
      explanation: 'Sans décomposeurs, la planète serait une morgue géante.',
    },
    {
      id: 'c1-fabr-leg-11-q',
      type: 'QUIZ',
      conceptId: 'ecosystem-flow',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthétiser : ce qui maintient un écosystème.',
      question: 'Qu\'est-ce qui maintient un écosystème vivant ?',
      options: [
        { text: 'Un flux constant d\'énergie + recyclage de la matière + biodiversité', isCorrect: true, feedback: 'Exact. Triade : flux, cycle, diversité.' },
        { text: 'L\'absence totale d\'humains', isCorrect: false, feedback: 'L\'humain peut faire partie d\'un écosystème équilibré.' },
        { text: 'Un seul type d\'espèce dominante', isCorrect: false, feedback: 'Inverse. Monoculture = fragilité.' },
      ],
    },
    {
      id: 'c1-fabr-leg-12-reveal',
      type: 'STORY',
      conceptId: 'ecosystem-flow',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective : tu sais désormais lire un écosystème.',
      screens: [
        {
          text: 'Tu peux maintenant entrer dans n\'importe quelle forêt et voir : producteurs, consommateurs, décomposeurs, flux. Le vivant n\'est plus un mystère.',
          imagePrompt: 'Personne contemplant une forêt avec flèches d\'énergie visibles',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['lire'],
        },
      ],
    },
    {
      id: 'c1-fabr-leg-13-q',
      type: 'QUIZ',
      conceptId: 'ecosystem-flow',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Choisir un geste cohérent.',
      question: 'Quelle action soutient le mieux un écosystème ?',
      options: [
        { text: 'Préserver la biodiversité (variété d\'espèces et de rôles)', isCorrect: true, feedback: 'Exact. Diversité = stabilité.' },
        { text: 'Privilégier une seule espèce productive', isCorrect: false, feedback: 'Monoculture = fragilité.' },
        { text: 'Stériliser le milieu', isCorrect: false, feedback: 'Stérile = mort.', misconceptionId: 'dead-soil-is-clean' },
      ],
    },
    {
      id: 'c1-fabr-leg-14-closure',
      type: 'STORY',
      conceptId: 'ecosystem-flow',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer le boss final du chapitre.',
      screens: [
        {
          text: 'Tu sais lire un écosystème. Reste un dernier défi : en construire un toi-même, mentalement, et prouver que tout tient.',
          imagePrompt: 'Mosaïque d\'un écosystème construit pièce par pièce',
          imageUrl: SPROUT_IMAGE,
          kind: 'closure',
          boldTokens: ['construire'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'chapter-1-fabr-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir l\'écosystème comme réseau de flux.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'chapter-1-fabr-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser les notions d\'écosystème.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'chapter-1-fabr-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler les notions dans des cas pièges.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 3 },
    },
    {
      id: 'chapter-1-fabr-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise du concept d\'écosystème.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 15, label: '15 Graines' },
    },
  ],
}
