import type { AcademyUnitDefinition } from '../../../schema'

const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const SPROUT_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'

export const photosynthesisUnit: AcademyUnitDefinition = {
  id: 'chapter-1-plants-light',
  slug: 'les-plantes-mangent-la-lumiere',
  chapterId: 'chapter-1',
  schemaVersion: 2,
  title: 'Les Plantes Mangent la Lumière',
  shortTitle: 'Photosynthèse',
  pathLabel: 'Lumière verte',
  subtitle: 'Découvre comment une feuille fabrique du sucre avec le ciel.',
  concept: 'Photosynthèse, feuilles, sucre',
  conceptIds: ['photosynthesis-mechanism', 'oxygen-production', 'carbon-cycle-storage'],
  kind: 'flora',
  iconKey: 'leaf',
  masteryGoal: 'Expliquer la photosynthèse sans jargon inutile.',
  order: 4,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: "Comprendre la photosynthèse comme assemblage de gaz et d'eau via la lumière.",
  mascot: 'sylva',
  rewardAmount: 15,

  authoredDiscovery: [
    {
      id: 'c1-photo-disc-1-hook',
      type: 'STORY',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : la feuille fait du solide à partir de gaz.',
      screens: [
        {
          text: "Une feuille de chêne, c'est du sucre, du bois, de la cellulose. Solide. Elle a fabriqué tout ça à partir d'air et de lumière.",
          imagePrompt: 'Feuille verte translucide avec rayons de soleil',
          imageUrl: SPROUT_IMAGE,
          kind: 'hook',
          boldTokens: ['solide'],
        },
      ],
    },
    {
      id: 'c1-photo-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester la misconception « la plante mange la terre ».',
      question: 'Vrai ou faux ?',
      card: { title: "Une plante mange la terre par ses racines.", subtitle: 'Intuition' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bien vu. La plante boit (eau) et capte des minéraux, mais elle ne mange pas la terre.",
      incorrectFeedback: "Misconception classique. La plante prend eau et minéraux. Sa nourriture (énergie) vient de la lumière.",
      explanation: 'Si c\'était vrai, le sol disparaîtrait sous les forêts. Il ne disparaît pas.',
      misconceptionId: 'plants-eat-soil',
    },
    {
      id: 'c1-photo-disc-3-reveal',
      type: 'STORY',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler l\'équation simple : lumière + CO₂ + eau → sucre + O₂.',
      screens: [
        {
          text: 'La feuille est une mini-usine : elle prend la lumière (Soleil), le CO₂ (air), l\'eau (sol).',
          imagePrompt: 'Feuille en gros plan avec entrées lumière, CO₂, eau',
          imageUrl: SPROUT_IMAGE,
          kind: 'reveal',
          boldTokens: ['feuille'],
        },
        {
          text: 'Elle assemble tout ça en sucre solide. Et relâche de l\'oxygène en bonus. C\'est la photosynthèse.',
          imagePrompt: 'Feuille qui produit sucre et oxygène',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['sucre'],
        },
      ],
    },
    {
      id: 'c1-photo-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['generation', 'misconception'],
      learningObjective: 'Identifier les ingrédients de la photosynthèse.',
      question: 'De quoi a besoin une feuille pour faire son travail ?',
      options: [
        { text: 'Lumière, CO₂ et eau', isCorrect: true, feedback: 'Exact. Trois ingrédients, un peu de chimie verte. Le sucre sort, l\'O₂ aussi.' },
        { text: 'Terre seulement', isCorrect: false, feedback: 'Misconception. La terre fournit eau et minéraux, mais le carburant vient de la lumière.', misconceptionId: 'plants-eat-soil' },
        { text: 'Eau seulement', isCorrect: false, feedback: "Insuffisant. Sans lumière ni CO₂, rien ne se passe." },
      ],
      hint: 'Pense à 3 ingrédients : un du ciel, un de l\'air, un du sol.',
    },
    {
      id: 'c1-photo-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'oxygen-production',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démolir l\'idée « tout l\'O₂ vient des forêts ».',
      question: 'Vrai ou faux ?',
      card: { title: "Les forêts produisent tout l'oxygène que nous respirons.", subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. ~50 à 80 % de l\'O₂ vient du phytoplancton océanique.',
      incorrectFeedback: 'Faux. L\'océan produit la majorité, via les microalgues.',
      explanation: 'Photosynthèse aquatique = phytoplancton, microalgues. Énorme producteur invisible.',
      misconceptionId: 'oxygen-from-trees-only',
    },
    {
      id: 'c1-photo-disc-6-build',
      type: 'STORY',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Lier photosynthèse et stockage du carbone.',
      screens: [
        {
          text: 'Le carbone du CO₂ devient bois solide. Un arbre adulte est donc un grand bloc de carbone capturé.',
          imagePrompt: 'Coupe de tronc de chêne avec étiquette CO₂',
          imageUrl: FOREST_IMAGE,
          kind: 'build-up',
          boldTokens: ['bloc'],
        },
      ],
    },
    {
      id: 'c1-photo-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: "Reconstituer l'équation de la photosynthèse.",
      instruction: "Ordonne entrées → produits :",
      axis: 'horizontal',
      axisRationale: 'Sens de la réaction chimique.',
      slotCount: 3,
      items: [
        { id: 'pp-1', text: '☀️ Lumière + CO₂ + 💧 eau' },
        { id: 'pp-2', text: '🍃 Réaction dans la feuille' },
        { id: 'pp-3', text: '🍯 Sucre + 💨 O₂' },
      ],
      correctFeedback: 'Parfait. Entrées → réaction → produits. Tout est respecté.',
      incorrectFeedback: 'Le sens va de gauche à droite : ingrédients puis produits.',
    },
    {
      id: 'c1-photo-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Récupération rapide sur la lumière nécessaire.',
      question: 'Vrai ou faux ?',
      card: { title: "Sans lumière, une plante ne peut pas faire sa photosynthèse.", subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. Pas de lumière = pas d'énergie pour la réaction.",
      incorrectFeedback: 'Si. La lumière est l\'élément déclencheur.',
      explanation: 'Une plante survit dans le noir quelques jours mais finit par mourir.',
    },
    {
      id: 'c1-photo-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'oxygen-production',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Récupération rapide sur l\'O₂.',
      question: 'Vrai ou faux ?',
      card: { title: "Quand une feuille fait sa photosynthèse, elle relâche de l'oxygène.", subtitle: 'Sprint 2' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. L\'O₂ est le produit secondaire (et vital pour nous).',
      incorrectFeedback: 'Si. Sans cette photosynthèse, pas d\'O₂ atmosphérique.',
      explanation: 'L\'atmosphère respirable existe grâce à 3 milliards d\'années de photosynthèse.',
    },
    {
      id: 'c1-photo-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: "D'où vient la masse du bois ?",
      question: "Le bois d'un arbre vient surtout de quoi ?",
      options: [
        { text: 'Du CO₂ de l\'air', isCorrect: true, feedback: 'Exact. Le carbone du bois vient de l\'air, pas du sol. Surprenant mais vrai.' },
        { text: 'De la terre', isCorrect: false, feedback: 'Misconception. Si c\'était vrai, le sol fondrait sous les forêts.', misconceptionId: 'plants-eat-soil' },
        { text: 'De l\'eau', isCorrect: false, feedback: 'L\'eau est nécessaire mais pas la matière finale du bois.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-photo-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Distinguer les sources des ingrédients.',
      instruction: 'Associe chaque ingrédient à sa source :',
      axis: 'horizontal',
      axisRationale: 'Mapping ingrédient → origine.',
      slotCount: 3,
      items: [
        { id: 'pb-1', text: '☀️ Lumière (ciel)' },
        { id: 'pb-2', text: '💨 CO₂ (air)' },
        { id: 'pb-3', text: '💧 Eau (sol)' },
        { id: 'pb-distract', text: '🪨 Roche', isDistractor: true },
      ],
      correctFeedback: "Excellent. La roche n'est pas un ingrédient direct.",
      incorrectFeedback: 'La photosynthèse n\'utilise pas de roches.',
    },
    {
      id: 'c1-photo-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: "Synthétiser : la photosynthèse est la base alimentaire du vivant.",
      question: 'Pourquoi la photosynthèse est-elle un mécanisme central de la vie ?',
      options: [
        { text: 'Elle crée la nourriture (sucre) ET l\'oxygène', isCorrect: true, feedback: 'Exact. Double rôle vital. Sans elle, pas de chaîne alimentaire ni d\'air respirable.' },
        { text: 'Elle crée de la lumière', isCorrect: false, feedback: 'Inverse. Elle utilise la lumière, elle ne la crée pas.' },
        { text: 'Elle ne sert qu\'à faire pousser des fleurs', isCorrect: false, feedback: 'Trop limité. Tout le vivant en dépend.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c1-photo-pool-sw-co2-toxic',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Le CO₂ n\'est pas un poison.',
      question: 'Vrai ou faux ?',
      card: { title: 'Le CO₂ est un poison toxique pour la nature.', subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Sans CO₂, pas de photosynthèse. Le problème climatique est l\'excès, pas la toxicité.',
      incorrectFeedback: 'Non. Le CO₂ est un nutriment vital pour les plantes.',
      explanation: 'CO₂ = nutriment + climat (équilibre nécessaire).',
      misconceptionId: 'co2-is-toxic',
    },
    {
      id: 'c1-photo-pool-sw-leaves-shape',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Comprendre pourquoi les feuilles sont plates.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les feuilles sont plates pour capter un maximum de lumière.', subtitle: 'Anatomie' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Surface plate = capteur solaire optimisé.',
      incorrectFeedback: 'Si. C\'est l\'évolution qui a sélectionné cette forme.',
      explanation: 'Comme un panneau solaire : plus c\'est large, plus on capte.',
    },
    {
      id: 'c1-photo-pool-sw-fall',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: "Pourquoi les feuilles tombent en automne.",
      question: 'Vrai ou faux ?',
      card: { title: "Les feuilles tombent à cause du froid.", subtitle: 'Saisons' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Le déclencheur est la baisse de luminosité, pas la température.',
      incorrectFeedback: 'Non. C\'est la photopériode (durée du jour) qui déclenche tout.',
      explanation: 'Stratégie d\'économie d\'eau pour l\'hiver.',
      misconceptionId: 'leaves-fall-because-cold',
    },
    {
      id: 'c1-photo-pool-sw-cactus',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Étendre aux cactus.',
      question: 'Vrai ou faux ?',
      card: { title: "Un cactus fait aussi de la photosynthèse.", subtitle: 'Désert' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Mais il ouvre ses stomates la nuit pour économiser l\'eau (CAM).',
      incorrectFeedback: 'Si. Toute plante verte fait de la photosynthèse.',
      explanation: 'Photosynthèse CAM = adaptation au désert.',
    },
    {
      id: 'c1-photo-pool-q-chlorophyll',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Identifier la chlorophylle.',
      question: "Pourquoi les feuilles sont-elles vertes ?",
      options: [
        { text: 'Pigment qui absorbe rouge/bleu, reflète vert', isCorrect: true, feedback: 'Exact. La chlorophylle absorbe rouge et bleu, et nous voyons le vert qui rebondit.' },
        { text: 'Parce qu\'elles aiment le vert', isCorrect: false, feedback: 'Le vert est le résultat physique de l\'absorption sélective.' },
        { text: 'Pour se cacher des animaux', isCorrect: false, feedback: 'Ce n\'est pas la fonction. Le vert est un sous-produit.' },
      ],
    },
    {
      id: 'c1-photo-pool-q-bois-source',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: "Origine de la masse du bois.",
      question: "Quand un arbre prend 100 kg en 10 ans, d'où viennent ces 100 kg ?",
      options: [
        { text: 'Du CO₂ atmosphérique (carbone) + eau', isCorrect: true, feedback: 'Exact. Surtout du CO₂ aérien. Surprenant pour beaucoup.' },
        { text: 'Du sol qu\'il a aspiré', isCorrect: false, feedback: 'Si c\'était vrai, le sol disparaîtrait. Il reste à peu près constant.', misconceptionId: 'plants-eat-soil' },
        { text: "De la pluie qu'il a stockée", isCorrect: false, feedback: 'L\'eau participe, mais elle est en partie expirée par les feuilles.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-photo-pool-q-stomates',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Identifier les stomates.',
      question: "Comment le CO₂ entre-t-il dans la feuille ?",
      options: [
        { text: 'Par de petites ouvertures appelées stomates', isCorrect: true, feedback: 'Exact. Les stomates sont des micro-pores qui s\'ouvrent et se ferment.' },
        { text: 'Par les racines', isCorrect: false, feedback: 'Les racines absorbent eau et minéraux, pas le CO₂.' },
        { text: 'Par le tronc', isCorrect: false, feedback: "Le tronc transporte la sève, il n'absorbe pas le CO₂." },
      ],
    },
    {
      id: 'c1-photo-pool-q-night-respiration',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Distinguer photosynthèse et respiration.',
      question: 'Une plante respire-t-elle aussi ?',
      options: [
        { text: 'Oui, jour et nuit. Elle consomme de l\'O₂', isCorrect: true, feedback: 'Exact. Photosynthèse de jour seulement, respiration permanente.' },
        { text: 'Non, elle ne respire jamais', isCorrect: false, feedback: 'Faux. Toute cellule vivante respire.' },
        { text: 'Seulement la nuit', isCorrect: false, feedback: "La respiration est continue, mais c'est plus visible la nuit (pas de photosynthèse compensatoire)." },
      ],
    },
    {
      id: 'c1-photo-pool-d-photo-equation',
      type: 'DRAG_DROP',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "Reconstituer l'équation simplifiée.",
      instruction: 'Ordonne les éléments :',
      axis: 'horizontal',
      axisRationale: "Sens de la réaction chimique.",
      slotCount: 3,
      items: [
        { id: 'pe-1', text: '💨 CO₂ + 💧 H₂O' },
        { id: 'pe-2', text: '☀️ + 🍃' },
        { id: 'pe-3', text: '🍯 sucre + O₂' },
      ],
      correctFeedback: 'Parfait. Réactifs → catalyseur → produits.',
      incorrectFeedback: 'Le sens va du réactif au produit.',
    },
    {
      id: 'c1-photo-pool-d-light-need',
      type: 'DRAG_DROP',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les plantes par besoin de lumière.',
      instruction: 'Du moins gourmand en lumière au plus :',
      axis: 'horizontal',
      axisRationale: 'Gradient écologique.',
      slotCount: 3,
      items: [
        { id: 'pl-1', text: '🍄 Champignon (peu)' },
        { id: 'pl-2', text: '🌿 Fougère (moyen)' },
        { id: 'pl-3', text: '🌻 Tournesol (fort)' },
      ],
      correctFeedback: 'Excellent. Le champignon ne fait pas de photosynthèse.',
      incorrectFeedback: 'Astuce : un seul ne fait pas du tout de photosynthèse (champignon).',
    },
    {
      id: 'c1-photo-pool-sw-water-glass',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Tester l\'expérience de la plante hydroponique.',
      question: 'Vrai ou faux ?',
      card: { title: "Une plante peut pousser dans l'eau seulement (hydroponie).", subtitle: 'Hydroponie' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. Avec lumière + air + eau enrichie, la plante prospère sans terre.",
      incorrectFeedback: 'Si. C\'est même un mode de culture commercial pour tomates et salades.',
      explanation: 'Preuve directe que la terre n\'est pas le carburant.',
    },
    {
      id: 'c1-photo-pool-q-dark-plant',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Que se passe-t-il sans lumière ?',
      question: 'Quel est le sort d\'une plante laissée dans le noir total ?',
      options: [
        { text: 'Elle meurt faute de refaire ses réserves', isCorrect: true, feedback: 'Exact. Elle continue de respirer, donc elle se vide de ses réserves.' },
        { text: 'Elle continue à pousser normalement', isCorrect: false, feedback: 'Sans lumière, plus de photosynthèse, plus de croissance durable.' },
        { text: 'Elle mange la terre pour compenser', isCorrect: false, feedback: 'Misconception. Elle ne mange pas la terre.', misconceptionId: 'plants-eat-soil' },
      ],
    },
  ],

  authoredLegendary: [
    {
      id: 'c1-photo-leg-1-hook',
      type: 'STORY',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le défi.',
      screens: [
        {
          text: 'Tu vas valider la photosynthèse comme moteur du vivant. 14 questions pour ancrer la chimie verte.',
          imagePrompt: 'Feuille avec photons et molécules autour',
          imageUrl: SPROUT_IMAGE,
          kind: 'hook',
          boldTokens: ['ancrer'],
        },
      ],
    },
    {
      id: 'c1-photo-leg-2-q',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Identifier l\'origine de la masse du bois.',
      question: "Le carbone d'un tronc d'arbre provient principalement de :",
      options: [
        { text: 'L\'air (CO₂)', isCorrect: true, feedback: 'Exact. Surprenant : un arbre est de l\'air solidifié.' },
        { text: 'Le sol', isCorrect: false, feedback: 'Misconception massive.', misconceptionId: 'plants-eat-soil' },
        { text: 'La pluie', isCorrect: false, feedback: 'L\'eau circule mais ne devient pas le bois solide.' },
      ],
    },
    {
      id: 'c1-photo-leg-3-q',
      type: 'QUIZ',
      conceptId: 'oxygen-production',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Identifier les producteurs d\'O₂.',
      question: "Qui produit le plus d'oxygène atmosphérique ?",
      options: [
        { text: 'Le phytoplancton océanique', isCorrect: true, feedback: 'Exact. ~50 à 80 % de l\'O₂ atmosphérique.' },
        { text: 'Les forêts uniquement', isCorrect: false, feedback: 'Importantes mais minoritaires.', misconceptionId: 'oxygen-from-trees-only' },
        { text: 'Les volcans', isCorrect: false, feedback: 'Les volcans rejettent CO₂ et SO₂, peu d\'O₂.' },
      ],
    },
    {
      id: 'c1-photo-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: "Reconstituer l'équation complète.",
      instruction: 'Ordonne le mécanisme complet :',
      axis: 'horizontal',
      axisRationale: 'Chronologie de la réaction.',
      slotCount: 5,
      items: [
        { id: 'pld-1', text: '☀️ Lumière captée' },
        { id: 'pld-2', text: '💨 CO₂ aspiré' },
        { id: 'pld-3', text: '💧 Eau absorbée' },
        { id: 'pld-4', text: '🍯 Sucre fabriqué' },
        { id: 'pld-5', text: '💨 O₂ relâché' },
        { id: 'pld-distract', text: '🪨 Roche broyée', isDistractor: true },
      ],
      correctFeedback: "Excellent. La roche n'a rien à faire dans la photosynthèse.",
      incorrectFeedback: 'Indice : un seul item n\'est pas dans l\'équation.',
    },
    {
      id: 'c1-photo-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Confirmer que CO₂ est nécessaire.',
      question: 'Vrai ou faux ?',
      card: { title: 'Sans CO₂, aucune plante ne pourrait vivre.', subtitle: 'Vital' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Le CO₂ est l\'ingrédient principal du sucre.',
      incorrectFeedback: 'Si. Sans CO₂, photosynthèse impossible.',
      explanation: 'C\'est pourquoi le débat climatique parle d\'équilibre, pas de suppression.',
      misconceptionId: 'co2-is-toxic',
    },
    {
      id: 'c1-photo-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'La plante respire aussi.',
      question: 'Vrai ou faux ?',
      card: { title: 'Une plante respire de l\'O₂ jour et nuit, comme nous.', subtitle: 'Respiration' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Photosynthèse = jour. Respiration = continue.',
      incorrectFeedback: 'Si. Toute cellule vivante respire.',
      explanation: 'La nuit, elle ne fait que respirer (consommer O₂).',
    },
    {
      id: 'c1-photo-leg-7-q',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Choisir la formulation correcte.',
      question: 'Comment résumer la photosynthèse ?',
      options: [
        { text: 'Lumière + CO₂ + eau → sucre + O₂', isCorrect: true, feedback: 'Exact. Équation simplifiée correcte.' },
        { text: 'Terre + lumière → bois', isCorrect: false, feedback: 'La terre n\'apparaît pas.', misconceptionId: 'plants-eat-soil' },
        { text: 'CO₂ → poison', isCorrect: false, feedback: 'Le CO₂ est un nutriment, pas un poison.', misconceptionId: 'co2-is-toxic' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-photo-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Lier Soleil, eau, sol et photosynthèse.',
      instruction: 'Ordonne la chaîne de causes :',
      axis: 'horizontal',
      axisRationale: 'Causalité temporelle.',
      slotCount: 4,
      items: [
        { id: 'pli-1', text: '☀️ Soleil rayonne' },
        { id: 'pli-2', text: '💧 Eau du sol monte' },
        { id: 'pli-3', text: '🍃 Photosynthèse' },
        { id: 'pli-4', text: '🌳 Croissance' },
      ],
      correctFeedback: 'Parfait. Tout part du Soleil et passe par la feuille.',
      incorrectFeedback: 'Indice : la chaîne va du ciel au tronc.',
      interleavesConceptIds: ['sun-energy-source', 'water-cycle-evaporation'],
    },
    {
      id: 'c1-photo-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'carbon-cycle-storage',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : photosynthèse stocke du carbone.',
      question: 'Vrai ou faux ?',
      card: { title: 'Un arbre est un grand bloc de carbone capté à l\'air.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Plus l\'arbre grandit, plus il stocke.',
      incorrectFeedback: 'Si. C\'est ce qui rend les forêts utiles climatiquement.',
      explanation: 'Le bois est ~50 % de carbone en masse sèche.',
    },
    {
      id: 'c1-photo-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Sprint : feuilles tombent à cause de la lumière.',
      question: 'Vrai ou faux ?',
      card: { title: "Les feuilles tombent par baisse de lumière", subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Photopériode = signal principal.',
      incorrectFeedback: 'Si. Le froid n\'est qu\'un facteur secondaire.',
      explanation: 'Étude classique : arbres en serre chauffée perdent quand même leurs feuilles à l\'automne.',
      misconceptionId: 'leaves-fall-because-cold',
    },
    {
      id: 'c1-photo-leg-11-q',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthétiser la fonction écosystémique.',
      question: "La photosynthèse permet ces 3 choses simultanément :",
      options: [
        { text: 'Nourrir le vivant + produire O₂ + stocker du carbone', isCorrect: true, feedback: 'Exact. Triple service vital.' },
        { text: 'Faire pousser des fleurs uniquement', isCorrect: false, feedback: 'Trop limité. Tous les producteurs en bénéficient.' },
        { text: "Refroidir l'air directement", isCorrect: false, feedback: 'Effet indirect via évapotranspiration, pas via photosynthèse pure.' },
      ],
    },
    {
      id: 'c1-photo-leg-12-reveal',
      type: 'STORY',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective : la photosynthèse a façonné l\'atmosphère.',
      screens: [
        {
          text: "L'atmosphère respirable existe grâce à 3 milliards d'années de photosynthèse. Chaque arbre continue ce travail.",
          imagePrompt: 'Atmosphère bleue avec Terre vue depuis l\'espace',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['façonné'],
        },
      ],
    },
    {
      id: 'c1-photo-leg-13-q',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Choisir une action quotidienne cohérente.',
      question: 'Quel geste valorise le mieux la photosynthèse ?',
      options: [
        { text: 'Préserver forêts et phytoplancton (océan)', isCorrect: true, feedback: 'Exact. Ce sont les deux grands « poumons ».' },
        { text: 'Planter uniquement des arbres', isCorrect: false, feedback: 'Insuffisant. ~50 à 80 % de l\'O₂ vient de l\'océan.', misconceptionId: 'oxygen-from-trees-only' },
        { text: 'Bétonner les sols', isCorrect: false, feedback: 'Le béton tue producteurs et microalgues.' },
      ],
    },
    {
      id: 'c1-photo-leg-14-closure',
      type: 'STORY',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: "Annoncer la transition vers l'unité Réflexes du Vivant.",
      screens: [
        {
          text: 'Tu connais les 4 forces : Soleil, eau, sols, photosynthèse. Prêt pour un sprint qui mélange tout ?',
          imagePrompt: 'Mosaïque des 4 forces du vivant',
          imageUrl: FIELD_IMAGE,
          kind: 'closure',
          boldTokens: ['sprint'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'chapter-1-photo-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir la photosynthèse.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'chapter-1-photo-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser la photosynthèse.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 1 },
    },
    {
      id: 'chapter-1-photo-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler la photosynthèse dans des cas pièges.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'chapter-1-photo-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise de la photosynthèse.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 15, label: '15 Graines' },
    },
  ],
}
