import type { AcademyUnitDefinition } from '../../../schema'

const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const SPROUT_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'

export const reflexesUnit: AcademyUnitDefinition = {
  id: 'chapter-1-training',
  slug: 'reflexes-du-vivant',
  chapterId: 'chapter-1',
  schemaVersion: 2,
  title: 'Réflexes du Vivant',
  shortTitle: 'Réflexes',
  pathLabel: 'Entraînement',
  subtitle: 'Sprint mental : Soleil, eau, sols, photosynthèse — sans hésiter.',
  concept: 'Entrelacement Soleil/Eau/Sols/Photosynthèse',
  conceptIds: ['sun-energy-source', 'water-cycle-evaporation', 'soil-living', 'photosynthesis-mechanism'],
  kind: 'training',
  iconKey: 'zap',
  masteryGoal: 'Reconnaître instantanément les 4 piliers de l\'écosystème.',
  order: 5,
  durationMinutes: 3,
  estimatedMinutes: '3 min',
  learningGoal: 'Construire l\'automatisme : associer chaque pilier à son rôle.',
  mascot: 'abeille-transparente',
  rewardAmount: 15,

  authoredDiscovery: [
    {
      id: 'c1-refl-disc-1-hook',
      type: 'STORY',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: "Annoncer le sprint d'entrelacement.",
      screens: [
        {
          text: 'Tu connais les 4 forces. Maintenant on mélange : Soleil, eau, sol, photosynthèse. Réponds vite.',
          imagePrompt: 'Mosaïque : soleil, goutte, terre, feuille',
          imageUrl: FIELD_IMAGE,
          kind: 'hook',
          boldTokens: ['mélange'],
        },
      ],
    },
    {
      id: 'c1-refl-disc-2-sw',
      type: 'SWIPE',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: ['sprint', 'interleaved'],
      learningObjective: 'Sprint Soleil.',
      question: 'Vrai ou faux ?',
      card: { title: "Sans Soleil, la photosynthèse s'arrête.", subtitle: 'Sprint Soleil' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Lumière = ingrédient n°1 de la photosynthèse.',
      incorrectFeedback: 'Si. Sans Soleil, plus d\'énergie pour fabriquer du sucre.',
      explanation: 'Sun = moteur du vivant.',
      interleavesConceptIds: ['sun-energy-source', 'photosynthesis-mechanism'],
    },
    {
      id: 'c1-refl-disc-3-sw',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['sprint', 'interleaved'],
      learningObjective: 'Sprint Eau.',
      question: 'Vrai ou faux ?',
      card: { title: "L'eau circule en boucle entre océan, ciel et terre.", subtitle: 'Sprint Eau' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Cycle infini depuis 4 milliards d\'années.',
      incorrectFeedback: 'Si. Évaporation, pluie, infiltration, ruissellement.',
      explanation: 'Cycle de l\'eau = boucle fermée.',
      interleavesConceptIds: ['water-cycle-evaporation'],
    },
    {
      id: 'c1-refl-disc-4-sw',
      type: 'SWIPE',
      conceptId: 'soil-living',
      difficulty: 'easy',
      cognitiveTags: ['sprint', 'interleaved'],
      learningObjective: 'Sprint Sol.',
      question: 'Vrai ou faux ?',
      card: { title: 'Un sol vivant grouille de bactéries, vers et champignons.', subtitle: 'Sprint Sol' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. C\'est ce qui le rend fertile.',
      incorrectFeedback: 'Si. Sans organismes, sol stérile = sol mort.',
      explanation: 'Sol vivant = écosystème invisible.',
      interleavesConceptIds: ['soil-living'],
    },
    {
      id: 'c1-refl-disc-5-sw',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'interleaved', 'misconception'],
      learningObjective: 'Sprint Photosynthèse + misconception.',
      question: 'Vrai ou faux ?',
      card: { title: 'La masse d\'un arbre vient surtout de la terre.', subtitle: 'Sprint Photo' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Le bois vient du CO₂ de l\'air, pas du sol.',
      incorrectFeedback: 'Misconception classique. La masse vient de l\'air (CO₂).',
      explanation: 'Photosynthèse solidifie l\'air en bois.',
      misconceptionId: 'plants-eat-soil',
      interleavesConceptIds: ['photosynthesis-mechanism'],
    },
    {
      id: 'c1-refl-disc-6-q',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Identifier le moteur des écosystèmes.',
      question: 'Quel est le moteur premier de TOUT le vivant ?',
      options: [
        { text: 'Le Soleil', isCorrect: true, feedback: 'Exact. Énergie de base via la photosynthèse.' },
        { text: 'Le sol', isCorrect: false, feedback: 'Le sol fournit eau et minéraux mais pas l\'énergie.' },
        { text: 'L\'eau', isCorrect: false, feedback: 'L\'eau circule grâce à... la chaleur solaire.' },
      ],
      hint: "Tu l'as vu en unité 1.",
      interleavesConceptIds: ['sun-energy-source'],
    },
    {
      id: 'c1-refl-disc-7-d',
      type: 'DRAG_DROP',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Reconstituer la chaîne complète des 4 piliers.',
      instruction: 'Ordonne la chaîne du vivant :',
      axis: 'horizontal',
      axisRationale: 'Chronologie causale du vivant.',
      slotCount: 4,
      items: [
        { id: 'r1-1', text: '☀️ Soleil' },
        { id: 'r1-2', text: '💧 Eau' },
        { id: 'r1-3', text: '🌱 Sol vivant' },
        { id: 'r1-4', text: '🍃 Photosynthèse' },
      ],
      correctFeedback: 'Excellent. Les 4 piliers en ordre.',
      incorrectFeedback: 'Indice : Soleil en premier, photosynthèse à la fin.',
      interleavesConceptIds: ['sun-energy-source', 'water-cycle-evaporation', 'soil-living', 'photosynthesis-mechanism'],
    },
    {
      id: 'c1-refl-disc-8-sw',
      type: 'SWIPE',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'interleaved', 'misconception'],
      learningObjective: 'Sprint sol + eau.',
      question: 'Vrai ou faux ?',
      card: { title: 'Un sol vivant absorbe ~20× plus d\'eau qu\'un sol bétonné.', subtitle: 'Sprint Sol+Eau' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Les racines + matière organique = éponge naturelle.',
      incorrectFeedback: 'Si. C\'est exactement ce qui distingue un sol vivant.',
      explanation: 'Sols vivants = anti-inondation.',
      misconceptionId: 'concrete-helps-drainage',
      interleavesConceptIds: ['soil-living', 'water-cycle-infiltration'],
    },
    {
      id: 'c1-refl-disc-9-sw',
      type: 'SWIPE',
      conceptId: 'oxygen-production',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'interleaved', 'misconception'],
      learningObjective: 'Sprint photosynthèse + océan.',
      question: 'Vrai ou faux ?',
      card: { title: 'Tout l\'oxygène que nous respirons vient des forêts.', subtitle: 'Sprint Photo+Océan' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Le phytoplancton océanique en produit la majorité.',
      incorrectFeedback: 'Faux. ~50 à 80 % vient de l\'océan.',
      explanation: 'L\'océan est le plus grand poumon du vivant.',
      misconceptionId: 'oxygen-from-trees-only',
      interleavesConceptIds: ['photosynthesis-mechanism', 'oxygen-production'],
    },
    {
      id: 'c1-refl-disc-10-q',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: ['interleaved', 'metacognition'],
      learningObjective: 'Synthétiser : la chaîne complète.',
      question: "Sans LE Soleil, ET sans sol vivant, qu'arrive-t-il aux écosystèmes ?",
      options: [
        { text: 'Ils s\'effondrent : pas de photosynthèse, pas de cycle de l\'eau, pas de nutriments', isCorrect: true, feedback: 'Exact. Les 4 piliers sont interdépendants.' },
        { text: 'Rien ne change', isCorrect: false, feedback: 'Le vivant entier dépend de ces 4 forces.' },
        { text: 'Ils se transforment en désert prospère', isCorrect: false, feedback: 'Sans Soleil, même les déserts seraient morts.' },
      ],
      confidenceCheck: true,
      interleavesConceptIds: ['sun-energy-source', 'soil-living', 'photosynthesis-mechanism', 'water-cycle-evaporation'],
    },
    {
      id: 'c1-refl-disc-11-d',
      type: 'DRAG_DROP',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Mapper chaque pilier à son rôle.',
      instruction: 'Associe chaque pilier à sa fonction :',
      axis: 'horizontal',
      axisRationale: 'Mapping conceptuel.',
      slotCount: 4,
      items: [
        { id: 'r2-1', text: '☀️ Soleil = énergie' },
        { id: 'r2-2', text: '💧 Eau = transport' },
        { id: 'r2-3', text: '🌱 Sol = nutriments' },
        { id: 'r2-4', text: '🍃 Feuille = transformation' },
      ],
      correctFeedback: 'Parfait. Chacun a son rôle, et tous sont nécessaires.',
      incorrectFeedback: 'Indice : énergie → transport → nutriments → transformation.',
      interleavesConceptIds: ['sun-energy-source', 'water-cycle-evaporation', 'soil-living', 'photosynthesis-mechanism'],
    },
    {
      id: 'c1-refl-disc-12-q',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['closure', 'interleaved'],
      learningObjective: 'Synthétiser la grammaire du chapitre 1.',
      question: "Quelle 'grammaire' as-tu acquise dans ce chapitre ?",
      options: [
        { text: "Soleil + eau + sol + photosynthèse = vivant", isCorrect: true, feedback: 'Exact. C\'est la base de tout. Tu vas pouvoir l\'utiliser dans toute la suite.' },
        { text: "Que la nature est compliquée", isCorrect: false, feedback: 'Trop vague. Tu as appris une structure précise.' },
        { text: "Que chaque élément est indépendant", isCorrect: false, feedback: 'Inverse. Tout est lié.' },
      ],
      interleavesConceptIds: ['sun-energy-source', 'water-cycle-evaporation', 'soil-living', 'photosynthesis-mechanism'],
    },
  ],

  pool: [
    {
      id: 'c1-refl-pool-sw-co2',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['interleaved', 'misconception'],
      learningObjective: 'Sprint CO₂ ≠ poison.',
      question: 'Vrai ou faux ?',
      card: { title: 'Le CO₂ est nourriture pour les plantes.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Sans CO₂, pas de photosynthèse.',
      incorrectFeedback: 'Si. C\'est l\'ingrédient principal du sucre.',
      explanation: 'CO₂ = nutriment. Le problème climatique est l\'excès.',
      misconceptionId: 'co2-is-toxic',
    },
    {
      id: 'c1-refl-pool-sw-fungi',
      type: 'SWIPE',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: ['interleaved', 'misconception'],
      learningObjective: 'Sprint champignons ≠ plantes.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les champignons font de la photosynthèse comme les plantes.', subtitle: 'Sprint' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Pas de chlorophylle, pas de photosynthèse.',
      incorrectFeedback: 'Non. Les champignons sont décomposeurs, pas producteurs.',
      explanation: 'Règnes : Plantes ≠ Champignons.',
      misconceptionId: 'mushrooms-are-plants',
    },
    {
      id: 'c1-refl-pool-sw-bacteria',
      type: 'SWIPE',
      conceptId: 'soil-living',
      difficulty: 'easy',
      cognitiveTags: ['interleaved', 'misconception'],
      learningObjective: 'Sprint bactéries utiles.',
      question: 'Vrai ou faux ?',
      card: { title: 'La majorité des bactéries sont utiles ou neutres.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Très peu sont pathogènes.',
      incorrectFeedback: 'Si. Les bactéries sont la base du vivant.',
      explanation: 'Microbiome humain : 40 000 milliards de bactéries utiles.',
      misconceptionId: 'bacteria-always-bad',
    },
    {
      id: 'c1-refl-pool-sw-amazon',
      type: 'SWIPE',
      conceptId: 'forest-water-cycle',
      difficulty: 'medium',
      cognitiveTags: ['interleaved', 'misconception'],
      learningObjective: 'Sprint forêt = pluie.',
      question: 'Vrai ou faux ?',
      card: { title: "Détruire une forêt n'a aucun effet sur les pluies locales.", subtitle: 'Sprint' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Sans forêt, moins de transpiration, moins de pluie.',
      incorrectFeedback: 'Non. La déforestation assèche le climat local.',
      explanation: 'Évapotranspiration = ~50 % des pluies amazoniennes.',
      misconceptionId: 'rain-comes-from-clouds-only',
    },
    {
      id: 'c1-refl-pool-q-link',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Lier 4 piliers en une logique.',
      question: 'Si tu coupes une forêt, quels effets en cascade peuvent apparaître ?',
      options: [
        { text: 'Moins de pluies, érosion du sol, perte de carbone, baisse d\'O₂', isCorrect: true, feedback: 'Exact. Les 4 piliers sont touchés.' },
        { text: 'Aucun effet visible', isCorrect: false, feedback: 'Faux. Effet documenté en Amazonie, Bornéo, Congo.' },
        { text: 'Le sol devient instantanément plus fertile', isCorrect: false, feedback: 'Inverse. Sans racines, le sol s\'érode.' },
      ],
    },
    {
      id: 'c1-refl-pool-q-base',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Identifier la base du vivant.',
      question: 'Que produit la base de toute chaîne alimentaire terrestre ?',
      options: [
        { text: 'Les producteurs (plantes, algues) qui captent la lumière', isCorrect: true, feedback: 'Exact. Sans producteurs, plus rien ne se nourrit.' },
        { text: 'Les super-prédateurs', isCorrect: false, feedback: 'Ils sont en haut, pas à la base.' },
        { text: 'Les décomposeurs', isCorrect: false, feedback: 'Ils ferment la boucle, mais ne la démarrent pas.' },
      ],
    },
    {
      id: 'c1-refl-pool-d-cycle-eau',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Reconstituer le cycle de l\'eau.',
      instruction: 'Ordonne le cycle :',
      axis: 'horizontal',
      axisRationale: 'Cycle temporel.',
      slotCount: 3,
      items: [
        { id: 'rwc-1', text: '💨 Évaporation' },
        { id: 'rwc-2', text: '☁️ Condensation' },
        { id: 'rwc-3', text: '🌧️ Précipitation' },
      ],
      correctFeedback: 'Parfait. Cycle classique acquis.',
      incorrectFeedback: 'Évaporation → nuages → pluie.',
    },
    {
      id: 'c1-refl-pool-d-photo',
      type: 'DRAG_DROP',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Reconstituer la photosynthèse.',
      instruction: 'Ingrédients → produits :',
      axis: 'horizontal',
      axisRationale: 'Sens de la réaction.',
      slotCount: 3,
      items: [
        { id: 'rph-1', text: '☀️ Lumière' },
        { id: 'rph-2', text: '🍃 Réaction' },
        { id: 'rph-3', text: '🍯 Sucre + O₂' },
      ],
      correctFeedback: 'Parfait. Lumière → réaction → produits.',
      incorrectFeedback: 'Réaction au milieu.',
    },
    {
      id: 'c1-refl-pool-sw-soil-water',
      type: 'SWIPE',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Sprint sol = filtre eau.',
      question: 'Vrai ou faux ?',
      card: { title: 'Un sol vivant filtre et purifie l\'eau de pluie qui le traverse.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Racines + organismes filtrent l\'eau.',
      incorrectFeedback: 'Si. C\'est ce qui rend l\'eau souterraine potable.',
      explanation: 'Sol = station d\'épuration naturelle.',
    },
    {
      id: 'c1-refl-pool-sw-tree-co2',
      type: 'SWIPE',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'medium',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Sprint arbre = stockage carbone.',
      question: 'Vrai ou faux ?',
      card: { title: 'Un arbre stocke le carbone du CO₂ pendant des décennies.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. C\'est un coffre-fort à carbone.',
      incorrectFeedback: 'Si. Tant qu\'il vit ou que son bois reste solide, il stocke.',
      explanation: 'Forêts = puits de carbone naturels.',
    },
    {
      id: 'c1-refl-pool-q-meta-pillars',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: ['interleaved', 'metacognition'],
      learningObjective: 'Identifier le pilier le plus fragile.',
      question: 'Quel pilier est le plus menacé par l\'urbanisation ?',
      options: [
        { text: 'Le sol vivant (bétonné, tassé, pollué)', isCorrect: true, feedback: 'Exact. L\'urbanisation est l\'ennemi n°1 du sol vivant.' },
        { text: 'Le Soleil', isCorrect: false, feedback: 'Le Soleil n\'est pas menacé par l\'urbanisation.' },
        { text: 'L\'eau', isCorrect: false, feedback: 'L\'eau circule encore, mais le ruissellement augmente.' },
      ],
      confidenceCheck: true,
    },
  ],

  authoredLegendary: [
    {
      id: 'c1-refl-leg-1-hook',
      type: 'STORY',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le grand sprint final.',
      screens: [
        {
          text: '14 questions, 4 piliers à mélanger. C\'est ici qu\'on voit si tu as la grammaire dans la peau.',
          imagePrompt: 'Mosaïque dynamique des 4 forces',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['mélanger'],
        },
      ],
    },
    {
      id: 'c1-refl-leg-2-q',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Identifier le moteur premier.',
      question: 'Qu\'est-ce qui démarre la chaîne du vivant ?',
      options: [
        { text: 'La lumière du Soleil', isCorrect: true, feedback: 'Exact. C\'est le déclencheur.' },
        { text: 'L\'eau de pluie', isCorrect: false, feedback: 'L\'eau circule grâce au Soleil.' },
        { text: 'Les minéraux du sol', isCorrect: false, feedback: 'Les minéraux ne déclenchent pas la chaîne.', misconceptionId: 'plants-eat-soil' },
      ],
    },
    {
      id: 'c1-refl-leg-3-q',
      type: 'QUIZ',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: ['interleaved', 'misconception'],
      learningObjective: 'Identifier la masse du bois.',
      question: 'Le bois solide d\'un arbre vient surtout de :',
      options: [
        { text: 'Le CO₂ de l\'air', isCorrect: true, feedback: 'Exact. Photosynthèse = solidification de l\'air.' },
        { text: 'Le sol qu\'il aspire', isCorrect: false, feedback: 'Misconception classique.', misconceptionId: 'plants-eat-soil' },
        { text: 'L\'eau seule', isCorrect: false, feedback: 'L\'eau participe mais n\'est pas le matériau final.' },
      ],
    },
    {
      id: 'c1-refl-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Reconstituer la chaîne complète des 4 piliers.',
      instruction: 'Ordonne la grammaire du chapitre 1 :',
      axis: 'horizontal',
      axisRationale: 'Chronologie causale.',
      slotCount: 5,
      items: [
        { id: 'rl-1', text: '☀️ Soleil' },
        { id: 'rl-2', text: '💧 Eau' },
        { id: 'rl-3', text: '🌱 Sol vivant' },
        { id: 'rl-4', text: '🍃 Photosynthèse' },
        { id: 'rl-5', text: '🌳 Vie' },
        { id: 'rl-distract', text: '🪨 Roche', isDistractor: true },
      ],
      correctFeedback: 'Excellent. La roche n\'est pas un pilier vivant.',
      incorrectFeedback: 'Indice : un seul item n\'est pas un pilier.',
    },
    {
      id: 'c1-refl-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'hard',
      cognitiveTags: ['interleaved', 'misconception'],
      learningObjective: 'Sprint sol vs béton.',
      question: 'Vrai ou faux ?',
      card: { title: 'Pour limiter les inondations, il faut bétonner.', subtitle: 'Sprint' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Bétonner = aggraver les inondations.',
      incorrectFeedback: 'Non. Désimperméabiliser = solution prouvée.',
      explanation: 'Stratégie « ville-éponge ».',
      misconceptionId: 'concrete-helps-drainage',
    },
    {
      id: 'c1-refl-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'oxygen-production',
      difficulty: 'medium',
      cognitiveTags: ['interleaved', 'misconception'],
      learningObjective: 'Sprint océan = poumon.',
      question: 'Vrai ou faux ?',
      card: { title: 'L\'océan produit la majorité de l\'O₂ atmosphérique.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Phytoplancton = ~50 à 80 %.',
      incorrectFeedback: 'Si. Les forêts sont importantes mais minoritaires.',
      explanation: 'Microalgues océaniques = champion de l\'O₂.',
      misconceptionId: 'oxygen-from-trees-only',
    },
    {
      id: 'c1-refl-leg-7-q',
      type: 'QUIZ',
      conceptId: 'soil-living',
      difficulty: 'hard',
      cognitiveTags: ['interleaved', 'metacognition'],
      learningObjective: 'Identifier le sol fertile.',
      question: 'Quel signe trahit un sol vraiment fertile ?',
      options: [
        { text: 'Beaucoup d\'organismes vivants', isCorrect: true, feedback: 'Exact. Vie = fertilité.' },
        { text: 'Sa couleur uniforme', isCorrect: false, feedback: 'La couleur seule ne suffit pas.' },
        { text: 'Sa stérilité parfaite', isCorrect: false, feedback: 'Stérile = mort.', misconceptionId: 'dead-soil-is-clean' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-refl-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'photosynthesis-mechanism',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Mapper ingrédient → source.',
      instruction: 'Mappe les ingrédients de la photosynthèse :',
      axis: 'horizontal',
      axisRationale: 'Mapping ingrédient → origine.',
      slotCount: 3,
      items: [
        { id: 'rls-1', text: '☀️ Lumière (Soleil)' },
        { id: 'rls-2', text: '💨 CO₂ (air)' },
        { id: 'rls-3', text: '💧 Eau (sol)' },
      ],
      correctFeedback: 'Parfait. Trois sources, trois ingrédients.',
      incorrectFeedback: 'Indice : ciel, air, sol.',
    },
    {
      id: 'c1-refl-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'forest-water-cycle',
      difficulty: 'medium',
      cognitiveTags: ['interleaved', 'sprint'],
      learningObjective: 'Sprint déforestation = sécheresse.',
      question: 'Vrai ou faux ?',
      card: { title: 'Couper une grande forêt assèche le climat local.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Sans transpiration, moins de pluie.',
      incorrectFeedback: 'Si. Documenté en Amazonie, Congo, Bornéo.',
      explanation: '50 % des pluies amazoniennes viennent de la forêt elle-même.',
    },
    {
      id: 'c1-refl-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: ['interleaved', 'sprint'],
      learningObjective: 'Sprint compost vs engrais.',
      question: 'Vrai ou faux ?',
      card: { title: 'Le compost nourrit le sol, l\'engrais chimique nourrit la plante.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Différence fondamentale.',
      incorrectFeedback: 'Si. Compost = écosystème, engrais = perfusion.',
      explanation: 'Approche durable vs approche ponctuelle.',
    },
    {
      id: 'c1-refl-leg-11-q',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Synthétiser : interdépendance.',
      question: "Quel mot résume le mieux les 4 piliers ?",
      options: [
        { text: 'Interdépendants', isCorrect: true, feedback: 'Exact. Aucun ne marche sans les autres.' },
        { text: 'Indépendants', isCorrect: false, feedback: 'Inverse. Ils dépendent les uns des autres.' },
        { text: 'Ennemis', isCorrect: false, feedback: 'Aucun pilier n\'est l\'ennemi des autres.' },
      ],
    },
    {
      id: 'c1-refl-leg-12-reveal',
      type: 'STORY',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner le sens du chapitre.',
      screens: [
        {
          text: 'Tu as la grammaire. Maintenant tu peux comprendre n\'importe quel écosystème en cherchant ses 4 piliers.',
          imagePrompt: 'Personne contemplant un paysage avec les 4 forces visibles',
          imageUrl: FIELD_IMAGE,
          kind: 'reveal',
          boldTokens: ['grammaire'],
        },
      ],
    },
    {
      id: 'c1-refl-leg-13-q',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Choisir un geste cohérent.',
      question: 'Quel geste protège les 4 piliers à la fois ?',
      options: [
        { text: 'Préserver une zone naturelle (forêt + eau + sol)', isCorrect: true, feedback: 'Exact. Une seule zone protégée = les 4 piliers conservés.' },
        { text: 'Bétonner pour ranger', isCorrect: false, feedback: 'Bétonner = tuer le sol vivant.' },
        { text: 'Stériliser le jardin', isCorrect: false, feedback: 'Stérile = mort.', misconceptionId: 'dead-soil-is-clean' },
      ],
    },
    {
      id: 'c1-refl-leg-14-closure',
      type: 'STORY',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer la transition vers Fabrique du Vivant.',
      screens: [
        {
          text: 'Tu sais identifier les 4 piliers. Reste à voir comment ils s\'assemblent pour faire un écosystème complet.',
          imagePrompt: 'Écosystème complet : forêt + rivière + sol + soleil',
          imageUrl: FOREST_IMAGE,
          kind: 'closure',
          boldTokens: ['assemblent'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'chapter-1-refl-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Sprinter sur les 4 piliers.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'chapter-1-refl-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser en mélangeant les piliers.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.5, interleaveFromPreviousUnits: 3 },
    },
    {
      id: 'chapter-1-refl-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler les 4 piliers dans des cas pièges.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.6, metacognitionRatio: 0.3, hardRatio: 0.7, interleaveFromPreviousUnits: 4 },
    },
    {
      id: 'chapter-1-refl-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Boss : maîtriser la grammaire complète.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 15, label: '15 Graines' },
    },
  ],
}
