import type { AcademyUnitDefinition } from '../../../schema'

const SOIL_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const SPROUT_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'
const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'

export const soilUnit: AcademyUnitDefinition = {
  id: 'chapter-1-soil',
  slug: 'la-magie-des-sols',
  chapterId: 'chapter-1',
  schemaVersion: 2,
  title: 'La Magie des Sols',
  shortTitle: 'Les Sols',
  pathLabel: 'Sols vivants',
  subtitle: 'Entre dans la fabrique souterraine des nutriments.',
  concept: 'Sols vivants, minéraux, racines',
  conceptIds: ['soil-living', 'microbiome-soil', 'decomposers-role'],
  kind: 'foundation',
  iconKey: 'sprout',
  masteryGoal: 'Distinguer un sol vivant d\'un support mort et comprendre les nutriments.',
  order: 3,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: 'Comprendre que le sol est un écosystème vivant qui nourrit les plantes.',
  mascot: 'sylva',
  rewardAmount: 10,

  authoredDiscovery: [
    {
      id: 'c1-soil-disc-1-hook',
      type: 'STORY',
      conceptId: 'soil-living',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : sous tes pieds, un monde grouillant.',
      screens: [
        {
          text: "Sous une cuillère à soupe de bonne terre, il y a plus d'organismes que d'humains sur Terre.",
          imagePrompt: 'Coupe transversale de terre vivante en gros plan',
          imageUrl: SOIL_IMAGE,
          kind: 'hook',
          boldTokens: ['organismes'],
        },
      ],
    },
    {
      id: 'c1-soil-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'soil-living',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester la misconception « bonne terre = terre stérile ».',
      question: 'Vrai ou faux ?',
      card: { title: 'Un bon sol pour les plantes est un sol stérile, sans organismes.', subtitle: 'Intuition jardinière' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bien vu. Un sol stérile est un sol mort. Les plantes y meurent.",
      incorrectFeedback: "C'est l'inverse. Un sol vivant grouille de vie : c'est ce qui le rend fertile.",
      explanation: 'Stérile = sans vie = sans nutriments disponibles.',
      misconceptionId: 'dead-soil-is-clean',
    },
    {
      id: 'c1-soil-disc-3-reveal',
      type: 'STORY',
      conceptId: 'microbiome-soil',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler la composition d\'un sol vivant.',
      screens: [
        {
          text: "Un sol vivant abrite bactéries, champignons, vers, insectes, racines. Tous travaillent ensemble pour recycler la matière.",
          imagePrompt: 'Vie souterraine illustrée : vers, champignons, bactéries',
          imageUrl: SOIL_IMAGE,
          kind: 'reveal',
          boldTokens: ['recycler'],
        },
        {
          text: "Ils décomposent les feuilles mortes en minéraux disponibles. Sans eux, les plantes ne peuvent plus se nourrir.",
          imagePrompt: 'Feuille morte en décomposition avec champignons',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['minéraux'],
        },
      ],
    },
    {
      id: 'c1-soil-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'microbiome-soil',
      difficulty: 'medium',
      cognitiveTags: ['generation', 'misconception'],
      learningObjective: "Identifier le rôle des micro-organismes du sol.",
      question: "À quoi servent les bactéries et champignons du sol ?",
      options: [
        { text: 'Décomposent la matière morte en nutriments', isCorrect: true, feedback: "Exact. Sans eux, les feuilles mortes s'accumuleraient sans nourrir les plantes." },
        { text: 'Ils rendent les plantes malades', isCorrect: false, feedback: "Quelques-uns oui, mais la grande majorité sont neutres ou bénéfiques.", misconceptionId: 'bacteria-always-bad' },
        { text: 'Ils ne servent à rien', isCorrect: false, feedback: "Faux. Ils sont la condition d'un sol fertile.", misconceptionId: 'dead-soil-is-clean' },
      ],
      hint: 'Pense à ce qui se passe quand une feuille tombe : qui la transforme ?',
    },
    {
      id: 'c1-soil-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'decomposers-role',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: "Démolir l'idée que les champignons sont des plantes.",
      question: 'Vrai ou faux ?',
      card: { title: "Les champignons sont des plantes simples.", subtitle: 'Idée reçue scolaire' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bravo. Les champignons forment leur propre règne. Génétiquement plus proches des animaux.",
      incorrectFeedback: "Faux. Pas de chlorophylle, pas de photosynthèse. Ce ne sont pas des plantes.",
      explanation: 'Règnes : Plantes, Animaux, Champignons, Bactéries, Archées, Protistes.',
      misconceptionId: 'mushrooms-are-plants',
    },
    {
      id: 'c1-soil-disc-6-build',
      type: 'STORY',
      conceptId: 'decomposers-role',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Introduire la boucle : matière morte → nutriments → plante.',
      screens: [
        {
          text: 'Quand une feuille tombe, elle devient nourriture pour le sol. Et le sol devient nourriture pour la prochaine plante.',
          imagePrompt: 'Cycle visuel feuille → terre → nouvelle pousse',
          imageUrl: SPROUT_IMAGE,
          kind: 'build-up',
          boldTokens: ['boucle'],
        },
      ],
    },
    {
      id: 'c1-soil-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'decomposers-role',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Reconstituer la décomposition.',
      instruction: 'Ordonne le devenir d\'une feuille morte :',
      axis: 'horizontal',
      axisRationale: 'Chronologie de la décomposition.',
      slotCount: 3,
      items: [
        { id: 'sd-1', text: '🍂 Feuille tombée' },
        { id: 'sd-2', text: '🍄 Décomposée par champignons' },
        { id: 'sd-3', text: '🌱 Nutriments pour racine' },
      ],
      correctFeedback: 'Parfait. La feuille morte devient nourriture pour la prochaine plante.',
      incorrectFeedback: "Le sens va du mort au vivant : décomposeurs au milieu.",
    },
    {
      id: 'c1-soil-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'soil-living',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Récupération rapide sur les vers de terre.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les vers de terre rendent le sol plus fertile.', subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. Ils aèrent le sol et leurs déjections sont un engrais naturel.",
      incorrectFeedback: 'Si. Un sol riche en vers est un sol qui respire mieux.',
      explanation: 'Un ver de terre brasse jusqu\'à 30 tonnes de terre par hectare et par an.',
    },
    {
      id: 'c1-soil-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'microbiome-soil',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Démolir la peur des bactéries.',
      question: 'Vrai ou faux ?',
      card: { title: 'Toutes les bactéries sont dangereuses.', subtitle: 'Sprint 2' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bravo. La majorité des bactéries sont neutres ou utiles. On en a 40 000 milliards dans nos intestins.",
      incorrectFeedback: 'Non. Très peu sont pathogènes. La plupart aident le vivant.',
      explanation: "Les bactéries sont la base de presque tous les écosystèmes.",
      misconceptionId: 'bacteria-always-bad',
    },
    {
      id: 'c1-soil-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'soil-living',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: 'Choisir le sol qui nourrit le mieux les plantes.',
      question: 'Quelle terre fait pousser les plantes le mieux ?',
      options: [
        { text: 'Une terre forestière, riche en humus et organismes', isCorrect: true, feedback: "Exact. C'est le sol idéal : actif, riche, structuré." },
        { text: 'Un sol stérile (sans micro-organismes)', isCorrect: false, feedback: "Sans organismes, pas de recyclage des nutriments. La plante meurt.", misconceptionId: 'dead-soil-is-clean' },
        { text: 'Du sable nu', isCorrect: false, feedback: 'Le sable n\'a quasi pas de nutriments ni de vie.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-soil-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les couches du sol.',
      instruction: 'Empile les couches de la plus haute à la plus basse :',
      axis: 'vertical',
      axisRationale: 'Profondeur réelle du sol : litière en haut, roche-mère en bas.',
      slotCount: 4,
      items: [
        { id: 'sb-1', text: '🍂 Litière (feuilles)' },
        { id: 'sb-2', text: '🌱 Humus (matière noire)' },
        { id: 'sb-3', text: '🪨 Sol minéral' },
        { id: 'sb-4', text: '⛰️ Roche-mère' },
        { id: 'sb-distract', text: '☁️ Nuage', isDistractor: true },
      ],
      correctFeedback: "Excellent. Le nuage n'a pas sa place sous terre.",
      incorrectFeedback: 'Indice : un seul item ne fait pas partie du sol.',
    },
    {
      id: 'c1-soil-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser : le sol est vivant, pas un support inerte.',
      question: 'Pourquoi protéger les sols vivants ?',
      options: [
        { text: 'Car ils nourrissent les plantes et gardent l\'eau', isCorrect: true, feedback: 'Exact. Sans eux, plus de cultures, plus de forêts, plus d\'absorption.' },
        { text: 'Parce qu\'ils sont jolis', isCorrect: false, feedback: 'Esthétique mais à côté du sujet. Le rôle écologique est central.' },
        { text: 'Parce qu\'ils stockent du pétrole', isCorrect: false, feedback: 'Le pétrole se forme dans des conditions très différentes, sur des millions d\'années.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c1-soil-pool-sw-mycorrhize',
      type: 'SWIPE',
      conceptId: 'microbiome-soil',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Découvrir la symbiose racines-champignons.',
      question: 'Vrai ou faux ?',
      card: { title: '95 % des plantes vivent en symbiose avec des champignons souterrains.', subtitle: 'Mycorhizes' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Les mycorhizes échangent eau, minéraux et sucres avec les racines.',
      incorrectFeedback: 'Si. Cette association est massive et essentielle.',
      explanation: 'Sans mycorhizes, la majorité des arbres ne pourraient pas pousser.',
    },
    {
      id: 'c1-soil-pool-sw-internet',
      type: 'SWIPE',
      conceptId: 'microbiome-soil',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Découvrir le « wood wide web ».',
      question: 'Vrai ou faux ?',
      card: { title: 'Les arbres communiquent entre eux via les champignons souterrains.', subtitle: 'Wood Wide Web' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. Réseau découvert par Suzanne Simard dans les années 90.",
      incorrectFeedback: 'Si. Ils échangent même sucres et signaux d\'alerte.',
      explanation: 'Wood Wide Web = réseau mycorhizien interconnecté.',
    },
    {
      id: 'c1-soil-pool-sw-sterile-greenhouse',
      type: 'SWIPE',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Confirmer que stérile ≠ fertile.',
      question: 'Vrai ou faux ?',
      card: { title: 'Plus une terre est stérile, plus elle est saine pour cultiver.', subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Stérile = sans organismes = sans nutriments = sans plantes.',
      incorrectFeedback: 'Non. Sain ≠ stérile. Une terre saine est pleine de vie utile.',
      explanation: "Hôpital ≠ jardin. Le sol est un écosystème, pas une salle d'opération.",
      misconceptionId: 'dead-soil-is-clean',
    },
    {
      id: 'c1-soil-pool-sw-pesticide',
      type: 'SWIPE',
      conceptId: 'microbiome-soil',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Comprendre l\'impact des pesticides sur le sol.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les pesticides chimiques peuvent tuer la vie souterraine.', subtitle: 'Agriculture' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Beaucoup de produits ciblent un nuisible mais touchent aussi vers, champignons, bactéries utiles.',
      incorrectFeedback: 'Si. C\'est ce qui appauvrit les sols agricoles à long terme.',
      explanation: 'Un sol traité longtemps perd sa fertilité naturelle.',
    },
    {
      id: 'c1-soil-pool-q-erosion',
      type: 'QUIZ',
      conceptId: 'soil-living',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Comprendre l\'érosion des sols nus.',
      question: "Pourquoi un sol nu (sans plantes) s'érode-t-il vite ?",
      options: [
        { text: 'L\'eau et le vent emportent la terre sans racines', isCorrect: true, feedback: 'Exact. Les racines sont l\'armature qui retient les particules.' },
        { text: 'Parce qu\'il manque de soleil', isCorrect: false, feedback: 'Le soleil n\'érode pas le sol.' },
        { text: 'Parce qu\'il est trop dur', isCorrect: false, feedback: 'Un sol dur s\'érode aussi en surface.' },
      ],
    },
    {
      id: 'c1-soil-pool-q-microbiome-human',
      type: 'QUIZ',
      conceptId: 'microbiome-soil',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Étendre la notion de microbiome au corps humain.',
      question: 'Combien de bactéries vivent dans nos intestins ?',
      options: [
        { text: '~40 000 milliards (autant que de nos cellules)', isCorrect: true, feedback: 'Exact. On est statistiquement moitié humain, moitié bactérien.' },
        { text: 'Quelques millions', isCorrect: false, feedback: 'Beaucoup plus. ~40 000 milliards.', misconceptionId: 'bacteria-always-bad' },
        { text: 'Aucune chez les gens en bonne santé', isCorrect: false, feedback: 'Aucune = mort. Les bactéries intestinales sont vitales.', misconceptionId: 'bacteria-always-bad' },
      ],
    },
    {
      id: 'c1-soil-pool-q-fungi-kingdom',
      type: 'QUIZ',
      conceptId: 'decomposers-role',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Identifier le règne des champignons.',
      question: 'À quel règne appartiennent les champignons ?',
      options: [
        { text: 'À leur propre règne (Fungi)', isCorrect: true, feedback: 'Exact. Génétiquement, ils sont plus proches des animaux que des plantes.' },
        { text: 'Au règne végétal', isCorrect: false, feedback: 'Pas de chlorophylle, pas de photosynthèse → pas une plante.', misconceptionId: 'mushrooms-are-plants' },
        { text: 'Au règne minéral', isCorrect: false, feedback: 'Ils sont vivants, pas minéraux.' },
      ],
    },
    {
      id: 'c1-soil-pool-q-decomposers',
      type: 'QUIZ',
      conceptId: 'decomposers-role',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Comprendre que la matière ne disparaît pas.',
      question: "Quand une feuille morte « disparaît » dans le sol, que devient sa matière ?",
      options: [
        { text: 'Recyclée en nutriments par les décomposeurs', isCorrect: true, feedback: 'Exact. Loi de conservation : la matière change de forme, ne disparaît pas.' },
        { text: 'Elle disparaît vraiment', isCorrect: false, feedback: 'La matière ne disparaît jamais. Elle est recyclée.' },
        { text: 'Elle se transforme en eau', isCorrect: false, feedback: 'Une partie va dans l\'eau du sol, mais l\'essentiel devient nutriments solides.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-soil-pool-d-decomposers-chain',
      type: 'DRAG_DROP',
      conceptId: 'decomposers-role',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les décomposeurs.',
      instruction: 'Du plus visible au plus invisible :',
      axis: 'horizontal',
      axisRationale: 'Échelle de taille décroissante.',
      slotCount: 3,
      items: [
        { id: 'sdc-1', text: '🪱 Vers de terre' },
        { id: 'sdc-2', text: '🍄 Champignons' },
        { id: 'sdc-3', text: '🦠 Bactéries' },
      ],
      correctFeedback: "Parfait. Tous décomposent, à des échelles différentes.",
      incorrectFeedback: 'Vers > champignons > bactéries en taille.',
    },
    {
      id: 'c1-soil-pool-d-soil-layers',
      type: 'DRAG_DROP',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les couches du sol.',
      instruction: 'Empile de la surface à la profondeur :',
      axis: 'vertical',
      axisRationale: 'Profondeur croissante = axe vertical.',
      slotCount: 3,
      items: [
        { id: 'ssl-1', text: '🌿 Litière' },
        { id: 'ssl-2', text: '🟫 Humus' },
        { id: 'ssl-3', text: '⛰️ Roche-mère' },
      ],
      correctFeedback: 'Excellent. Plus on descend, plus c\'est minéral.',
      incorrectFeedback: 'Litière en haut, roche-mère tout en bas.',
    },
    {
      id: 'c1-soil-pool-sw-organic-matter',
      type: 'SWIPE',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'La matière organique nourrit le sol.',
      question: 'Vrai ou faux ?',
      card: { title: 'Le compost remplace bien les engrais chimiques.', subtitle: 'Pratique' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. Le compost nourrit le sol vivant. Les engrais chimiques nourrissent juste la plante, pas le sol.",
      incorrectFeedback: 'Si. Compost = nourrir l\'écosystème. Engrais = perfusion ponctuelle.',
      explanation: 'Différence : compost rend le sol durablement fertile.',
    },
    {
      id: 'c1-soil-pool-sw-clay-sand',
      type: 'SWIPE',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "Comparer types de sols.",
      question: 'Vrai ou faux ?',
      card: { title: 'Un sol argileux retient mieux l\'eau qu\'un sol sablonneux.', subtitle: 'Géologie' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. L\'argile a des particules fines qui retiennent l\'eau.',
      incorrectFeedback: 'Si. Le sable laisse passer l\'eau, l\'argile la retient.',
      explanation: 'Sol idéal = mix argile (rétention) + sable (drainage) + matière organique.',
    },
  ],

  authoredLegendary: [
    {
      id: 'c1-soil-leg-1-hook',
      type: 'STORY',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le défi : maîtriser le sol vivant.',
      screens: [
        {
          text: 'Tu vas valider que le sol n\'est pas du tout ce que tu pensais. 14 questions pour ancrer le concept.',
          imagePrompt: 'Vue stylisée du sol vivant',
          imageUrl: SOIL_IMAGE,
          kind: 'hook',
          boldTokens: ['ancrer'],
        },
      ],
    },
    {
      id: 'c1-soil-leg-2-q',
      type: 'QUIZ',
      conceptId: 'soil-living',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Identifier le sol fertile.',
      question: 'Quel est le signe d\'un sol vraiment fertile ?',
      options: [
        { text: "Plein d'organismes visibles et invisibles", isCorrect: true, feedback: 'Exact. Plus de vie = plus de fertilité.' },
        { text: 'Il est complètement nu et propre', isCorrect: false, feedback: 'Nu = sujet à l\'érosion + sans vie.', misconceptionId: 'dead-soil-is-clean' },
        { text: 'Il est très compacté', isCorrect: false, feedback: 'Compacté = pas d\'air, pas de vie.' },
      ],
    },
    {
      id: 'c1-soil-leg-3-q',
      type: 'QUIZ',
      conceptId: 'decomposers-role',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Identifier le règne des champignons.',
      question: 'Pourquoi les champignons ne sont-ils pas des plantes ?',
      options: [
        { text: 'Pas de chlorophylle ni de photosynthèse', isCorrect: true, feedback: "Exact. Ils mangent du mort, pas de la lumière. Règne distinct." },
        { text: 'Parce qu\'ils sont petits', isCorrect: false, feedback: 'La taille ne définit pas un règne. Certains champignons font des km.' },
        { text: 'Parce qu\'ils vivent sous terre', isCorrect: false, feedback: 'Beaucoup de plantes ont aussi des racines souterraines.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-soil-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'decomposers-role',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Reconstituer la chaîne de décomposition complète.',
      instruction: 'Ordonne le devenir d\'un tronc mort :',
      axis: 'horizontal',
      axisRationale: 'Chronologie de la décomposition.',
      slotCount: 5,
      items: [
        { id: 'sld-1', text: '🌳 Arbre tombé' },
        { id: 'sld-2', text: '🐛 Insectes le percent' },
        { id: 'sld-3', text: '🍄 Champignons le digèrent' },
        { id: 'sld-4', text: '🦠 Bactéries finalisent' },
        { id: 'sld-5', text: '🌱 Sol nourricier' },
        { id: 'sld-distract', text: '☀️ Soleil', isDistractor: true },
      ],
      correctFeedback: "Excellent. Le Soleil n'est pas un décomposeur direct.",
      incorrectFeedback: 'Indice : un seul item n\'est pas un décomposeur du sol.',
    },
    {
      id: 'c1-soil-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'microbiome-soil',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Confirmer le rôle bénéfique des bactéries.',
      question: 'Vrai ou faux ?',
      card: { title: 'Sans bactéries, aucune vie complexe ne pourrait exister sur Terre.', subtitle: 'Vital' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Elles digèrent, fixent l\'azote, recyclent. Sans elles, blocage total.',
      incorrectFeedback: 'Si. Les bactéries sont la base invisible de tous les écosystèmes.',
      explanation: 'Vie sur Terre = bactéries d\'abord, multicellulaires en évolution.',
      misconceptionId: 'bacteria-always-bad',
    },
    {
      id: 'c1-soil-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Mesurer l\'importance d\'un sol vivant.',
      question: 'Vrai ou faux ?',
      card: { title: 'Un sol vivant peut absorber 20× plus d\'eau qu\'un sol nu.', subtitle: 'Hydrologie' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Racines + matière organique + porosité = éponge naturelle.',
      incorrectFeedback: 'Si. C\'est un facteur clé contre les inondations.',
      explanation: 'Les sols vivants tamponnent crues et sécheresses.',
    },
    {
      id: 'c1-soil-leg-7-q',
      type: 'QUIZ',
      conceptId: 'soil-living',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Choisir la formulation juste de « sol fertile ».',
      question: 'Quelle définition est la plus juste ?',
      options: [
        { text: 'Un écosystème vivant qui recycle la matière', isCorrect: true, feedback: 'Exact. C\'est un écosystème, pas un substrat passif.' },
        { text: 'Un sol enrichi de produits chimiques', isCorrect: false, feedback: 'Trop limité. La fertilité naît du vivant, pas des produits.' },
        { text: 'Un sol fertile est un sol stérile bien drainé', isCorrect: false, feedback: 'Stérile = mort. Aucune fertilité durable.', misconceptionId: 'dead-soil-is-clean' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-soil-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'soil-living',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Lier eau, sol et lumière.',
      instruction: 'Ordonne ce qu\'une plante reçoit du sol et du ciel :',
      axis: 'horizontal',
      axisRationale: 'Chaîne de besoins.',
      slotCount: 4,
      items: [
        { id: 'sli-1', text: '☀️ Lumière (ciel)' },
        { id: 'sli-2', text: '💧 Eau (sol)' },
        { id: 'sli-3', text: '🪨 Minéraux (sol)' },
        { id: 'sli-4', text: '🍃 Photosynthèse' },
      ],
      correctFeedback: 'Parfait. Lumière + sol vivant = vie possible.',
      incorrectFeedback: 'Le sol fournit eau et minéraux. La lumière fournit l\'énergie.',
      interleavesConceptIds: ['sun-energy-source', 'water-cycle-infiltration'],
    },
    {
      id: 'c1-soil-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'decomposers-role',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : la matière ne disparaît pas.',
      question: 'Vrai ou faux ?',
      card: { title: 'La matière d\'une feuille morte disparaît vraiment.', subtitle: 'Sprint' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Elle change de forme : nutriments dans le sol.',
      incorrectFeedback: 'Non. Conservation de la matière : elle est recyclée, pas détruite.',
      explanation: 'Loi de Lavoisier appliquée à l\'écologie.',
    },
    {
      id: 'c1-soil-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'microbiome-soil',
      difficulty: 'hard',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint : symbiose racines-champignons.',
      question: 'Vrai ou faux ?',
      card: { title: '95 % des plantes terrestres dépendent de champignons souterrains.', subtitle: 'Sprint' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. Les mycorhizes sont la règle, pas l'exception.",
      incorrectFeedback: 'Si. Sans mycorhizes, la plupart des forêts ne tiendraient pas.',
      explanation: 'Ces champignons étendent la zone d\'absorption des racines.',
    },
    {
      id: 'c1-soil-leg-11-q',
      type: 'QUIZ',
      conceptId: 'soil-living',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthétiser le rôle écosystémique du sol.',
      question: "Quel rôle clé un sol vivant joue-t-il dans le climat ?",
      options: [
        { text: 'Stocke le carbone, absorbe l\'eau et nourrit', isCorrect: true, feedback: 'Exact. Triple service : carbone, eau, nutriments.' },
        { text: "Il n'a aucun rôle climatique", isCorrect: false, feedback: 'Faux. Les sols stockent ~3× plus de carbone que l\'atmosphère.' },
        { text: 'Il refroidit l\'air directement', isCorrect: false, feedback: 'Effet indirect via l\'eau et les plantes, pas direct.' },
      ],
    },
    {
      id: 'c1-soil-leg-12-reveal',
      type: 'STORY',
      conceptId: 'soil-living',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective : le sol vivant est invisible mais central.',
      screens: [
        {
          text: 'Le sol vivant est l\'écosystème le plus dense de la planète. Tout le visible (forêts, animaux, humains) en dépend.',
          imagePrompt: 'Coupe artistique de sol vivant avec racines lumineuses',
          imageUrl: SPROUT_IMAGE,
          kind: 'reveal',
          boldTokens: ['dépend'],
        },
      ],
    },
    {
      id: 'c1-soil-leg-13-q',
      type: 'QUIZ',
      conceptId: 'soil-living',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Choisir une action quotidienne cohérente.',
      question: 'Quel geste protège le mieux les sols vivants ?',
      options: [
        { text: 'Composter et limiter les pesticides', isCorrect: true, feedback: 'Exact. Composter nourrit la vie. Réduire les pesticides la préserve.' },
        { text: 'Bétonner les jardins pour les rendre propres', isCorrect: false, feedback: 'Bétonner = tuer le sol vivant.' },
        { text: 'Stériliser la terre avant de planter', isCorrect: false, feedback: 'Stériliser = empêcher la fertilité.', misconceptionId: 'dead-soil-is-clean' },
      ],
    },
    {
      id: 'c1-soil-leg-14-closure',
      type: 'STORY',
      conceptId: 'soil-living',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer la transition vers les Plantes/Photosynthèse.',
      screens: [
        {
          text: 'Soleil, eau, sol vivant : les trois piliers sont là. Mais comment la plante les transforme-t-elle en vie ?',
          imagePrompt: 'Jeune pousse au milieu de soleil, gouttes et terre',
          imageUrl: SPROUT_IMAGE,
          kind: 'closure',
          boldTokens: ['transforme'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'chapter-1-soil-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir le sol vivant et son rôle.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'chapter-1-soil-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser le rôle du sol vivant.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 1 },
    },
    {
      id: 'chapter-1-soil-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler le concept de sol vivant.',
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'chapter-1-soil-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise du sol vivant.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 10, label: '10 Graines' },
    },
  ],
}
