import type { AcademyUnitDefinition } from '../../../schema'

const STORY_IMAGE =
  'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?q=80&w=1000&auto=format&fit=crop'
const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'
const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'

export const sunUnit: AcademyUnitDefinition = {
  id: 'chapter-1-sun',
  slug: 'le-pouvoir-du-soleil',
  chapterId: 'chapter-1',
  schemaVersion: 2,
  title: 'Le Pouvoir du Soleil',
  shortTitle: 'Le Soleil',
  pathLabel: 'Pouvoir solaire',
  subtitle: "Découvre l'énergie primaire qui allume presque toute la vie.",
  concept: 'Soleil, énergie, producteurs',
  conceptIds: ['sun-energy-source', 'producers-vs-consumers', 'food-chain-link'],
  kind: 'foundation',
  iconKey: 'sun',
  masteryGoal: 'Expliquer pourquoi le Soleil est le premier moteur des écosystèmes.',
  order: 1,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: "Comprendre que la lumière solaire est la source d'énergie primaire du vivant.",
  mascot: 'ondine',
  rewardAmount: 10,

  // ─── Leçon Découverte (12 exercices écrits main) ──────────────────────────
  authoredDiscovery: [
    // 1. STORY hook — paradoxe d'ouverture
    {
      id: 'c1-sun-disc-1-hook',
      type: 'STORY',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: 'Poser le paradoxe : qu\'est-ce qui « nourrit » vraiment un arbre ?',
      screens: [
        {
          text: "Un grand chêne pèse 5 tonnes. Aucune racine ne pourrait soulever autant de terre. D'où vient sa masse ?",
          imagePrompt: 'Grand chêne majestueux sous un ciel clair',
          imageUrl: FOREST_IMAGE,
          kind: 'hook',
          boldTokens: ['masse'],
        },
      ],
    },
    // 2. SWIPE pre-test — laisse l'utilisateur deviner faux
    {
      id: 'c1-sun-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: ['pre-test', 'misconception'],
      learningObjective: 'Tester l\'intuition fausse : « les plantes mangent la terre ».',
      question: 'Vrai ou faux ?',
      card: {
        title: "Un arbre construit son bois en absorbant la terre par ses racines.",
        subtitle: 'Intuition courante',
      },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bien vu. La terre n'est pas le carburant. On t'explique d'où ça vient.",
      incorrectFeedback: "C'est l'idée la plus répandue, et elle est fausse. Suis bien la suite.",
      explanation: "Le bois ne vient pas du sol. Il vient de l'air et de la lumière.",
      misconceptionId: 'plants-eat-soil',
    },
    // 3. STORY reveal — le « aha »
    {
      id: 'c1-sun-disc-3-reveal',
      type: 'STORY',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Révéler le mécanisme : la lumière fournit l\'énergie, le CO₂ fournit la matière.',
      screens: [
        {
          text: "La feuille capte la lumière du Soleil. Avec elle, elle assemble du CO₂ de l'air en sucre solide.",
          imagePrompt: 'Rayon de soleil traversant une feuille verte translucide',
          imageUrl: STORY_IMAGE,
          kind: 'reveal',
          boldTokens: ['lumière'],
        },
        {
          text: "Ce sucre devient bois, fruit, racine. Le Soleil est donc la source d'énergie de presque tout le vivant.",
          imagePrompt: 'Forêt baignée de soleil avec rayons traversant la canopée',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['énergie'],
        },
      ],
    },
    // 4. QUIZ generation — fixe le concept
    {
      id: 'c1-sun-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['generation', 'misconception'],
      learningObjective: "Identifier la lumière comme source d'énergie de la photosynthèse.",
      question: "D'où vient l'énergie qui fait pousser un arbre ?",
      options: [
        {
          text: 'Du Soleil',
          isCorrect: true,
          feedback: "Exact. La feuille transforme la lumière en sucre. C'est la photosynthèse.",
        },
        {
          text: 'Des minéraux du sol',
          isCorrect: false,
          feedback: 'Idée commune mais fausse. Les minéraux sont des vitamines, pas le carburant.',
          misconceptionId: 'plants-eat-soil',
        },
        {
          text: 'De la chaleur du noyau terrestre',
          isCorrect: false,
          feedback: "Le noyau chauffe les profondeurs, mais sa chaleur n'arrive pas aux feuilles.",
        },
      ],
      hint: 'Pense à ce qui se passe quand on met une plante dans le noir.',
    },
    // 5. SWIPE misconception — démonte un mythe annexe
    {
      id: 'c1-sun-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'oxygen-production',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: "Corriger l'idée que tout l'oxygène vient des forêts.",
      question: 'Vrai ou faux ?',
      card: {
        title: "Tout l'oxygène que nous respirons vient des forêts.",
        subtitle: 'Idée reçue',
      },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Exact. La majorité vient du phytoplancton océanique, pas des forêts.",
      incorrectFeedback: "Faux. ~50 à 80 % de l'oxygène vient du phytoplancton de l'océan.",
      explanation: "Les microalgues océaniques produisent plus d'oxygène que toutes les forêts réunies.",
      misconceptionId: 'oxygen-from-trees-only',
    },
    // 6. STORY build-up — élargit
    {
      id: 'c1-sun-disc-6-build',
      type: 'STORY',
      conceptId: 'producers-vs-consumers',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Introduire la notion de producteurs vs consommateurs.',
      screens: [
        {
          text: "Tout ce qui fait sa propre énergie avec la lumière s'appelle un producteur. Plantes, algues, certaines bactéries.",
          imagePrompt: 'Champ de jeunes pousses brillantes au lever du soleil',
          imageUrl: FIELD_IMAGE,
          kind: 'build-up',
          boldTokens: ['producteur'],
        },
      ],
    },
    // 7. DRAG_DROP somatique — chaîne énergétique horizontale
    {
      id: 'c1-sun-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: "Reconstituer la chaîne énergétique : lumière → producteur → consommateur.",
      instruction: "Ordonne le trajet de l'énergie :",
      axis: 'horizontal',
      axisRationale: "L'axe horizontal lit le temps de gauche à droite : la lumière arrive, puis traverse la chaîne.",
      slotCount: 3,
      items: [
        { id: 'sun-1', text: '☀️ Soleil' },
        { id: 'sun-2', text: '🌱 Plante' },
        { id: 'sun-3', text: '🐇 Lapin' },
      ],
      correctFeedback: "Parfait. L'énergie passe du Soleil au lapin via la plante, jamais l'inverse.",
      incorrectFeedback: "Pas encore. La chaîne va toujours du Soleil vers les animaux, pas l'inverse.",
    },
    // 8. SWIPE sprint 1 — récupération rapide
    {
      id: 'c1-sun-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Récupération active rapide sur le rôle du Soleil.',
      question: 'Vrai ou faux ?',
      card: {
        title: "Sans Soleil, presque toute la vie sur Terre s'éteindrait.",
        subtitle: 'Sprint 1',
      },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. Quelques bactéries résistent près des sources hydrothermales, mais presque tout le reste dépend du Soleil.",
      incorrectFeedback: "Si. Sans Soleil, plus de photosynthèse, plus de chaîne alimentaire.",
      explanation: "Le Soleil est le moteur de plus de 99 % de la biosphère.",
    },
    // 9. SWIPE sprint 2 — autre angle
    {
      id: 'c1-sun-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'producers-vs-consumers',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: 'Récupération active sur la définition de producteur.',
      question: 'Vrai ou faux ?',
      card: {
        title: 'Un loup est un producteur.',
        subtitle: 'Sprint 2',
      },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bien joué. Le loup mange d'autres animaux, c'est un consommateur.",
      incorrectFeedback: "Non. Un producteur fabrique son énergie. Le loup la prend chez d'autres.",
      explanation: 'Producteurs = font leur énergie. Consommateurs = la prennent ailleurs.',
    },
    // 10. QUIZ misconception + metacognition
    {
      id: 'c1-sun-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: "Confirmer la maîtrise du concept en démontant la misconception 'plantes mangent la terre' une seconde fois.",
      question: 'Si tu enferme une plante dans une serre sans terre mais avec air et lumière, que se passe-t-il ?',
      options: [
        {
          text: 'Elle survit',
          isCorrect: true,
          feedback: "Exact. C'est la culture hydroponique : air + eau + lumière suffisent.",
        },
        {
          text: 'Elle meurt sans terre',
          isCorrect: false,
          feedback: "C'est la misconception classique. Le sol fournit eau et minéraux, pas le carburant.",
          misconceptionId: 'plants-eat-soil',
        },
      ],
      confidenceCheck: true,
    },
    // 11. DRAG_DROP boss mini — synthèse
    {
      id: 'c1-sun-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: 'Reconstituer une chaîne plus longue avec un distracteur.',
      instruction: "Ordonne du Soleil au super-prédateur :",
      axis: 'horizontal',
      axisRationale: "L'axe temporel/causal va du producteur au consommateur final.",
      slotCount: 4,
      items: [
        { id: 'sun-boss-1', text: '☀️ Soleil' },
        { id: 'sun-boss-2', text: '🌿 Herbe' },
        { id: 'sun-boss-3', text: '🐇 Lapin' },
        { id: 'sun-boss-4', text: '🦊 Renard' },
        { id: 'sun-boss-distract', text: '🪨 Caillou', isDistractor: true },
      ],
      correctFeedback: "Excellent. Le caillou ne mange ni n'est mangé : il n'a pas sa place dans la chaîne énergétique.",
      incorrectFeedback: "Indice : un seul élément ne fait pas partie du vivant.",
    },
    // 12. QUIZ closure — pourquoi global
    {
      id: 'c1-sun-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Synthétiser pourquoi le Soleil ouvre toute Académie sur le vivant.',
      question: 'Pourquoi commence-t-on cette aventure par le Soleil ?',
      options: [
        {
          text: "Il alimente toute la vie",
          isCorrect: true,
          feedback: 'Exact. Sans cette énergie de base, rien d\'autre ne fonctionne. On va explorer ce que sa lumière permet.',
        },
        {
          text: "Parce qu'il fait pousser uniquement les fleurs",
          isCorrect: false,
          feedback: 'Trop restrictif. Il fait pousser TOUT ce qui est producteur (plantes, algues, certaines bactéries).',
        },
        {
          text: "Parce qu'il est le plus beau dans le ciel",
          isCorrect: false,
          feedback: 'Esthétique mais pas le sujet. Sa fonction biologique est la clé ici.',
        },
      ],
    },
  ],

  // ─── Pool d'exercices (variantes Practice/Mastery) ────────────────────────
  pool: [
    // Misconceptions et variantes Swipe medium
    {
      id: 'c1-sun-pool-sw-co2-toxic',
      type: 'SWIPE',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: "Corriger l'idée que le CO₂ est un poison.",
      question: 'Vrai ou faux ?',
      card: { title: 'Le CO₂ est un poison toxique pour la nature.', subtitle: 'Idée reçue' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bravo. Le CO₂ est essentiel : sans lui, pas de photosynthèse.",
      incorrectFeedback: "Non. Le CO₂ nourrit les plantes. Le problème climatique vient de l'excès, pas de la toxicité.",
      explanation: "Trop de CO₂ = climat dérégulé. Mais le CO₂ lui-même nourrit les producteurs.",
      misconceptionId: 'co2-is-toxic',
    },
    {
      id: 'c1-sun-pool-sw-night-photo',
      type: 'SWIPE',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "Renforcer la dépendance directe à la lumière.",
      question: 'Vrai ou faux ?',
      card: { title: 'Une plante fait sa photosynthèse même la nuit.', subtitle: 'Réflexe' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Exact. La nuit, sans lumière, pas de photosynthèse.',
      incorrectFeedback: "Sans lumière, le mécanisme s'arrête. La plante respire mais ne produit plus.",
      explanation: 'Photosynthèse = lumière + CO₂ + eau → sucre + O₂.',
    },
    {
      id: 'c1-sun-pool-sw-algae',
      type: 'SWIPE',
      conceptId: 'producers-vs-consumers',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Étendre la notion de producteur aux algues.',
      question: 'Vrai ou faux ?',
      card: { title: 'Une algue est un producteur, comme un arbre.', subtitle: "Producteurs marins" },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Les algues font de la photosynthèse, comme les plantes.',
      incorrectFeedback: "Si. Les algues captent la lumière et fabriquent leur sucre, comme un arbre.",
      explanation: 'Producteur = tout ce qui fait son énergie avec la lumière.',
    },
    {
      id: 'c1-sun-pool-sw-fungi',
      type: 'SWIPE',
      conceptId: 'producers-vs-consumers',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: "Corriger l'idée que les champignons sont producteurs.",
      question: 'Vrai ou faux ?',
      card: { title: "Un champignon est un producteur (il pousse comme une plante).", subtitle: 'Piège' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bravo. Les champignons ne font pas de photosynthèse. Ce sont des décomposeurs.",
      incorrectFeedback: "Non. Pas de feuille verte, pas de photosynthèse. Le champignon mange du mort.",
      explanation: 'Les champignons forment leur propre règne — ni plantes ni animaux.',
      misconceptionId: 'mushrooms-are-plants',
    },

    // Quiz medium-hard
    {
      id: 'c1-sun-pool-q-tree-mass',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: "D'où vient la masse d'un arbre ?",
      question: "Un arbre de 5 tonnes : d'où vient l'essentiel de sa masse ?",
      options: [
        { text: "L'air", isCorrect: true, feedback: "Exact. Le carbone du bois vient du CO₂ de l'air. Surprenant mais vrai." },
        { text: 'Du sol', isCorrect: false, feedback: "Misconception classique. Si on pesait le sol avant et après, il aurait à peine bougé.", misconceptionId: 'plants-eat-soil' },
        { text: "De l'eau", isCorrect: false, feedback: "L'eau passe à travers, mais ne reste pas en majorité dans le bois sec." },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-sun-pool-q-energy-chain',
      type: 'QUIZ',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "Comprendre que l'énergie circule à sens unique.",
      question: "Que se passe-t-il quand un loup mange un lapin ?",
      options: [
        { text: "Loup récupère l'énergie", isCorrect: true, feedback: "Exact. L'énergie remonte la chaîne, mais avec des pertes à chaque étape." },
        { text: "Le loup crée de l'énergie nouvelle", isCorrect: false, feedback: "Aucun être vivant ne crée d'énergie. Il la transfère ou la transforme." },
        { text: "L'énergie disparaît", isCorrect: false, feedback: "Elle ne disparaît pas. Elle est utilisée et une partie est dissipée en chaleur." },
      ],
    },
    {
      id: 'c1-sun-pool-q-deep-sea',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: "Connaître l'exception : les écosystèmes des sources hydrothermales.",
      question: "Au fond des océans, certains écosystèmes vivent sans Soleil. De quoi se nourrissent-ils ?",
      options: [
        { text: "Énergie chimique des sources", isCorrect: true, feedback: "Exact. Des bactéries utilisent le soufre pour faire leur énergie. C'est la chimiosynthèse." },
        { text: "De la lumière des poissons", isCorrect: false, feedback: "La bioluminescence existe, mais elle ne fournit pas assez d'énergie pour nourrir un écosystème." },
        { text: "Soleil en profondeur", isCorrect: false, feedback: "À 2000 m, il fait nuit noire. Le Soleil ne va pas si profond." },
      ],
      confidenceCheck: true,
    },

    // Drag&drop variantes
    {
      id: 'c1-sun-pool-d-photo-cycle',
      type: 'DRAG_DROP',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Ordonner les ingrédients de la photosynthèse.',
      instruction: 'Ordonne les étapes de la photosynthèse :',
      axis: 'horizontal',
      axisRationale: 'Chronologie du processus.',
      slotCount: 3,
      items: [
        { id: 'p1', text: '☀️ Lumière captée' },
        { id: 'p2', text: '⚗️ CO₂ + eau combinés' },
        { id: 'p3', text: '🍯 Sucre fabriqué' },
      ],
      correctFeedback: "Parfait. Lumière → réaction → sucre. Et l'oxygène est le bonus.",
      incorrectFeedback: 'La lumière déclenche tout. Sans elle, rien ne se passe.',
    },
    {
      id: 'c1-sun-pool-d-trophic',
      type: 'DRAG_DROP',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser les niveaux trophiques verticalement.',
      instruction: 'Place du producteur au super-prédateur :',
      axis: 'vertical',
      axisRationale: "L'axe vertical exprime la hiérarchie trophique : producteur en bas, prédateur en haut.",
      slotCount: 4,
      items: [
        { id: 't1', text: '🌿 Plante' },
        { id: 't2', text: '🐛 Chenille' },
        { id: 't3', text: '🐦 Oiseau' },
        { id: 't4', text: '🦅 Aigle' },
      ],
      correctFeedback: "Parfait. La pyramide va du producteur (base) au super-prédateur (sommet).",
      incorrectFeedback: 'La base nourrit le sommet, jamais l\'inverse.',
    },

    // Story bonus (rare dans le pool, sert pour la variabilité)
    {
      id: 'c1-sun-pool-s-photosynth',
      type: 'STORY',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'Rappeler le mécanisme de la photosynthèse en une image.',
      screens: [
        {
          text: "La photosynthèse, c'est l'art de fabriquer du solide avec du gaz et de la lumière.",
          imagePrompt: 'Feuille en gros plan avec rayons solaires et molécules de CO₂',
          imageUrl: STORY_IMAGE,
          kind: 'reveal',
          boldTokens: ['solide'],
        },
      ],
    },

    // Quiz misconception bonus
    {
      id: 'c1-sun-pool-q-sun-decoration',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: ['misconception'],
      learningObjective: 'Confirmer le rôle du Soleil contre une option-piège esthétique.',
      question: "Quel est le rôle principal du Soleil dans la nature ?",
      options: [
        { text: "Source d'énergie", isCorrect: true, feedback: 'Exact. Sa lumière démarre presque toute la chaîne du vivant.' },
        { text: 'Décor du ciel', isCorrect: false, feedback: "Ça, c'est pour nos yeux. Sa fonction biologique est bien plus profonde." },
        { text: 'Réserve de minéraux', isCorrect: false, feedback: 'Le Soleil est du gaz incandescent, pas une mine de minéraux.' },
      ],
    },

    // Swipe sprint pour Practice
    {
      id: 'c1-sun-pool-sw-cactus',
      type: 'SWIPE',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Étendre le concept aux plantes désertiques.',
      question: 'Vrai ou faux ?',
      card: { title: 'Un cactus du désert fait aussi de la photosynthèse.', subtitle: 'Désert' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Le cactus capte la lumière comme toute plante. Il économise juste l\'eau.',
      incorrectFeedback: "Si. Toute plante verte fait de la photosynthèse, désert ou non.",
      explanation: "Le cactus fait sa photosynthèse la nuit (CAM) pour économiser l'eau, mais c'est bien la même chimie.",
    },
  ],

  // ─── Leçon Couronne (14 exercices écrits main) ────────────────────────────
  authoredLegendary: [
    // 1. STORY hook — défi
    {
      id: 'c1-sun-leg-1-hook',
      type: 'STORY',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le boss : valider la maîtrise du rôle du Soleil.',
      screens: [
        {
          text: 'Tu vas relier le Soleil à toute la vie. 14 questions pour prouver que le concept est vraiment ancré.',
          imagePrompt: 'Soleil radieux au-dessus d\'un paysage diversifié',
          imageUrl: FIELD_IMAGE,
          kind: 'hook',
          boldTokens: ['relier'],
        },
      ],
    },
    // 2. QUIZ hard misconception
    {
      id: 'c1-sun-leg-2-q',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Démontrer que la masse du bois vient du CO₂.',
      question: "Si on coupe un arbre adulte et qu'on pèse le sol autour, comment a-t-il évolué ?",
      options: [
        { text: 'À peine bougé', isCorrect: true, feedback: 'Exact. La masse du bois vient du CO₂, pas du sol.' },
        { text: 'Il a perdu autant de poids que l\'arbre', isCorrect: false, feedback: "Misconception : si c'était vrai, le sol disparaîtrait sous les forêts.", misconceptionId: 'plants-eat-soil' },
        { text: 'Il a doublé de volume', isCorrect: false, feedback: 'Aucun mécanisme connu pour ça.' },
      ],
    },
    // 3. QUIZ hard
    {
      id: 'c1-sun-leg-3-q',
      type: 'QUIZ',
      conceptId: 'oxygen-production',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Identifier la source majoritaire d\'oxygène.',
      question: "Quelle est la plus grande source d'oxygène atmosphérique ?",
      options: [
        { text: 'Le phytoplancton', isCorrect: true, feedback: 'Exact. ~50 à 80 % vient des microalgues.' },
        { text: 'Les forêts tropicales', isCorrect: false, feedback: 'Importantes mais minoritaires. C\'est l\'océan qui domine.', misconceptionId: 'oxygen-from-trees-only' },
        { text: 'Les volcans', isCorrect: false, feedback: 'Les volcans rejettent du CO₂ et du SO₂, peu d\'O₂.' },
      ],
    },
    // 4. DRAG_DROP big — synthèse
    {
      id: 'c1-sun-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'food-chain-link',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser une chaîne complexe avec distracteur.',
      instruction: 'Empile la chaîne énergétique du bas vers le haut :',
      axis: 'vertical',
      axisRationale: "L'axe vertical figure la pyramide trophique.",
      slotCount: 5,
      items: [
        { id: 'leg-d4-1', text: '🌾 Blé' },
        { id: 'leg-d4-2', text: '🦗 Sauterelle' },
        { id: 'leg-d4-3', text: '🦔 Hérisson' },
        { id: 'leg-d4-4', text: '🦊 Renard' },
        { id: 'leg-d4-5', text: '🦅 Aigle' },
        { id: 'leg-d4-distract', text: '☁️ Nuage', isDistractor: true },
      ],
      correctFeedback: "Excellent. Le nuage n'est pas un être vivant : il n'a pas sa place dans la chaîne.",
      incorrectFeedback: 'Indice : un seul item ne fait pas partie du vivant.',
    },
    // 5. SWIPE
    {
      id: 'c1-sun-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'producers-vs-consumers',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Confirmer que les champignons ne sont pas producteurs.',
      question: 'Vrai ou faux ?',
      card: { title: 'Les champignons captent la lumière du Soleil pour vivre.', subtitle: 'Piège' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Les champignons sont décomposeurs, pas photosynthétiques.',
      incorrectFeedback: 'Non. Pas de chlorophylle = pas de photosynthèse.',
      explanation: 'Les champignons mangent le mort, comme un consommateur.',
      misconceptionId: 'mushrooms-are-plants',
    },
    // 6. SWIPE
    {
      id: 'c1-sun-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: 'Vérifier la dépendance énergie → vivant.',
      question: 'Vrai ou faux ?',
      card: { title: 'Si le Soleil s\'éteignait demain, le vivant tiendrait quelques années.', subtitle: 'Vrai ou faux' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Sans lumière, plus de photosynthèse et la chaîne s\'effondre en quelques semaines.',
      incorrectFeedback: 'Plus de lumière = plus de plantes. Plus de plantes = plus de chaîne alimentaire.',
      explanation: "Quelques bactéries résisteraient près des sources hydrothermales, c'est tout.",
    },
    // 7. QUIZ metacognition
    {
      id: 'c1-sun-leg-7-q',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: 'Choisir la formulation la plus juste de la photosynthèse.',
      question: 'Comment formuler la photosynthèse en une ligne ?',
      options: [
        { text: 'Lumière + CO₂ + eau → sucre', isCorrect: true, feedback: 'Exact. C\'est l\'équation simplifiée correcte.' },
        { text: 'Lumière → plante', isCorrect: false, feedback: 'La terre n\'apparaît pas dans l\'équation.' },
        { text: 'Eau seule → sucre', isCorrect: false, feedback: 'Sans lumière ni CO₂, rien ne se passe.' },
      ],
      confidenceCheck: true,
    },
    // 8. DRAG entrelacement (anticipe Eau / Sols qui viendront)
    {
      id: 'c1-sun-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: 'Lier le Soleil à la formation des sols et au cycle de l\'eau.',
      instruction: 'Ordonne les conséquences de la lumière du Soleil :',
      axis: 'horizontal',
      axisRationale: 'Chronologie de cause à effet.',
      slotCount: 3,
      items: [
        { id: 'leg-d8-1', text: '☀️ Soleil chauffe l\'eau' },
        { id: 'leg-d8-2', text: '💨 Évaporation' },
        { id: 'leg-d8-3', text: '☁️ Pluie sur les forêts' },
      ],
      correctFeedback: 'Parfait. Le Soleil n\'est pas que pour les feuilles : il fait tourner le cycle de l\'eau aussi.',
      incorrectFeedback: 'La chaleur solaire évapore l\'eau, qui retombe ensuite en pluie.',
      interleavesConceptIds: ['water-cycle-evaporation'],
    },
    // 9. SWIPE sprint
    {
      id: 'c1-sun-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'food-chain-link',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: 'Sprint final : vérifier la direction de la chaîne énergétique.',
      question: 'Vrai ou faux ?',
      card: { title: 'L\'énergie circule du super-prédateur vers la plante.', subtitle: 'Sprint final' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. C\'est l\'inverse : du producteur vers le prédateur.',
      incorrectFeedback: 'Non. La chaîne va toujours du producteur vers le consommateur.',
      explanation: 'Producteur → herbivore → carnivore → super-prédateur. Sens unique.',
    },
    // 10. SWIPE sprint
    {
      id: 'c1-sun-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Confirmer que le CO₂ est nécessaire au vivant.',
      question: 'Vrai ou faux ?',
      card: { title: 'Sans CO₂ dans l\'atmosphère, la vie continuerait normalement.', subtitle: 'Sprint final' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Bravo. Sans CO₂, pas de photosynthèse possible.',
      incorrectFeedback: 'Non. Le CO₂ est indispensable : sans lui, pas de plantes.',
      explanation: 'L\'enjeu n\'est pas l\'absence de CO₂ mais son équilibre.',
      misconceptionId: 'co2-is-toxic',
    },
    // 11. QUIZ intégrative
    {
      id: 'c1-sun-leg-11-q',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Relier le Soleil à plusieurs phénomènes simultanément.',
      question: 'Sans le Soleil, lesquels de ces phénomènes s\'arrêteraient ?',
      options: [
        { text: "Photosynthèse, eau et vents", isCorrect: true, feedback: 'Exact. Le Soleil chauffe l\'air et l\'eau, ce qui crée vents et pluies.' },
        { text: 'Seulement la photosynthèse', isCorrect: false, feedback: 'C\'est trop limité. Le Soleil fait aussi tourner le climat.' },
        { text: 'Seulement le cycle de l\'eau', isCorrect: false, feedback: 'Sans Soleil, plus de plantes non plus.' },
      ],
    },
    // 12. STORY reveal final
    {
      id: 'c1-sun-leg-12-reveal',
      type: 'STORY',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: 'Donner la perspective : le Soleil unifie toute l\'Académie.',
      screens: [
        {
          text: 'Sun, plantes, eau, animaux, climat : tout démarre par un photon. Tu viens de poser la première brique.',
          imagePrompt: 'Photon qui se transforme en feuille, en eau, en animal',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['photon'],
        },
      ],
    },
    // 13. QUIZ closure pratique
    {
      id: 'c1-sun-leg-13-q',
      type: 'QUIZ',
      conceptId: 'sun-energy-source',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Choisir une action quotidienne cohérente avec le concept.',
      question: 'Quel geste respecte le mieux ce que tu viens d\'apprendre ?',
      options: [
        { text: 'Préserver les forêts ET l\'océan', isCorrect: true, feedback: 'Exact. Forêts et phytoplancton sont les deux poumons.' },
        { text: 'Planter uniquement des arbres', isCorrect: false, feedback: 'Insuffisant : 50-80 % de l\'O₂ vient de l\'océan.' },
        { text: 'Ne rien faire, le Soleil suffit', isCorrect: false, feedback: 'Le Soleil fournit l\'énergie, pas la protection des écosystèmes.' },
      ],
    },
    // 14. STORY closure
    {
      id: 'c1-sun-leg-14-closure',
      type: 'STORY',
      conceptId: 'sun-energy-source',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer la transition vers l\'unité Eau.',
      screens: [
        {
          text: 'Tu sais d\'où vient l\'énergie. La prochaine question : comment l\'eau circule-t-elle pour rendre tout cela possible ?',
          imagePrompt: 'Goutte d\'eau qui reflète un soleil',
          imageUrl: STORY_IMAGE,
          kind: 'closure',
          boldTokens: ['circule'],
        },
      ],
    },
  ],

  // ─── Métadonnées des 4 leçons ─────────────────────────────────────────────
  lessons: [
    {
      id: 'chapter-1-sun-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: 'Découvrir que le Soleil alimente presque tout le vivant.',
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'chapter-1-sun-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser le rôle du Soleil sans relire la théorie.',
      generation: 'pool-practice',
      rules: {
        exerciseCount: 10,
        misconceptionRatio: 0.4,
        interleaveFromPreviousUnits: 0,
      },
    },
    {
      id: 'chapter-1-sun-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: 'Manipuler le concept dans des cas pièges.',
      generation: 'pool-mastery',
      rules: {
        exerciseCount: 12,
        misconceptionRatio: 0.5,
        metacognitionRatio: 0.3,
        hardRatio: 0.6,
      },
    },
    {
      id: 'chapter-1-sun-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: 'Prouver la maîtrise du Soleil comme moteur du vivant.',
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 10, label: '10 Graines' },
    },
  ],
}
