import type { AcademyUnitDefinition } from '../../../schema'

const WATER_IMAGE =
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?q=80&w=1000&auto=format&fit=crop'
const FOREST_IMAGE =
  'https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?q=80&w=1000&auto=format&fit=crop'
const FIELD_IMAGE =
  'https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=1000&auto=format&fit=crop'

export const waterUnit: AcademyUnitDefinition = {
  id: 'chapter-1-water',
  slug: 'le-voyage-de-leau',
  chapterId: 'chapter-1',
  schemaVersion: 2,
  title: "Le Voyage de l'Eau",
  shortTitle: "L'Eau",
  pathLabel: 'Cycle bleu',
  subtitle: "Suis l'eau qui circule entre ciel, sol et vivant.",
  concept: 'Évaporation, pluie, infiltration',
  conceptIds: ['water-cycle-evaporation', 'water-cycle-infiltration', 'forest-water-cycle'],
  kind: 'foundation',
  iconKey: 'water',
  masteryGoal: "Remettre le cycle de l'eau dans l'ordre et expliquer son rôle vivant.",
  order: 2,
  durationMinutes: 3,
  estimatedMinutes: '3-4 min',
  learningGoal: "Comprendre le cycle de l'eau et son lien avec les écosystèmes.",
  mascot: 'ondine',
  rewardAmount: 10,

  authoredDiscovery: [
    {
      id: 'c1-water-disc-1-hook',
      type: 'STORY',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['hook'],
      learningObjective: "Poser le paradoxe : la même eau circule depuis 4 milliards d'années.",
      screens: [
        {
          text: "L'eau que tu bois aujourd'hui a peut-être été bue par un dinosaure. Sur Terre, l'eau ne disparaît jamais : elle voyage.",
          imagePrompt: "Goutte d'eau au-dessus d'un océan ensoleillé",
          imageUrl: WATER_IMAGE,
          kind: 'hook',
          boldTokens: ['voyage'],
        },
      ],
    },
    {
      id: 'c1-water-disc-2-pretest',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['pre-test'],
      learningObjective: "Tester l'intuition : qu'est-ce qui fait monter l'eau dans le ciel ?",
      question: 'Vrai ou faux ?',
      card: { title: "L'eau monte au ciel parce qu'elle est plus légère que l'air.", subtitle: 'Intuition' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bien vu. Le mécanisme est tout autre : c'est une transformation, pas une question de poids.",
      incorrectFeedback: "Presque. L'eau ne flotte pas : elle change d'état grâce à la chaleur.",
      explanation: "L'eau s'évapore quand elle reçoit de l'énergie (du Soleil).",
    },
    {
      id: 'c1-water-disc-3-reveal',
      type: 'STORY',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: "Révéler le mécanisme : Soleil → évaporation → nuages → pluie.",
      screens: [
        {
          text: "Le Soleil chauffe l'eau. Elle se transforme en vapeur invisible et monte. C'est l'évaporation.",
          imagePrompt: "Soleil au-dessus d'une mer avec de la vapeur qui monte",
          imageUrl: WATER_IMAGE,
          kind: 'reveal',
          boldTokens: ['évaporation'],
        },
        {
          text: "En altitude, la vapeur refroidit, se rassemble en gouttelettes : ce sont les nuages. Puis la gravité les fait retomber en pluie.",
          imagePrompt: 'Nuages chargés au-dessus de montagnes avec pluie',
          imageUrl: FOREST_IMAGE,
          kind: 'reveal',
          boldTokens: ['gravité'],
        },
      ],
    },
    {
      id: 'c1-water-disc-4-quiz',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: "Identifier le moteur du cycle de l'eau.",
      question: "Qu'est-ce qui démarre le cycle de l'eau ?",
      options: [
        { text: 'La chaleur du Soleil', isCorrect: true, feedback: "Exact. Sans Soleil, pas d'évaporation. Pas d'évaporation = plus de cycle." },
        { text: 'La gravité de la Lune', isCorrect: false, feedback: 'La Lune cause les marées, mais pas le cycle de l\'eau.' },
        { text: 'Le vent', isCorrect: false, feedback: "Le vent transporte les nuages, mais c'est la chaleur solaire qui fait évaporer l'eau." },
      ],
      hint: "Pense au moteur de tous les écosystèmes (vu dans l'unité précédente).",
    },
    {
      id: 'c1-water-disc-5-misconception',
      type: 'SWIPE',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: "Démolir l'idée que le béton aide l'eau à s'écouler.",
      question: 'Vrai ou faux ?',
      card: { title: "Le béton aide l'eau de pluie à s'écouler dans le sol.", subtitle: 'Idée reçue urbaine' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bravo. Le béton bloque l'eau. C'est ce qui cause les inondations urbaines.",
      incorrectFeedback: "Non. Le béton est imperméable : il empêche l'infiltration.",
      explanation: 'Un sol vivant absorbe ~20× plus d\'eau qu\'un sol bétonné.',
      misconceptionId: 'concrete-helps-drainage',
    },
    {
      id: 'c1-water-disc-6-build',
      type: 'STORY',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: "Introduire l'infiltration : le sol comme éponge vivante.",
      screens: [
        {
          text: "Quand la pluie touche un sol vivant, elle s'infiltre, nourrit les racines, et remplit les nappes souterraines.",
          imagePrompt: 'Coupe transversale du sol avec eau qui descend vers une nappe',
          imageUrl: FIELD_IMAGE,
          kind: 'build-up',
          boldTokens: ['infiltre'],
        },
      ],
    },
    {
      id: 'c1-water-disc-7-drag',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['generation'],
      learningObjective: "Reconstituer les 3 étapes principales du cycle de l'eau.",
      instruction: "Ordonne les étapes du cycle :",
      axis: 'horizontal',
      axisRationale: 'Chronologie temporelle du cycle.',
      slotCount: 3,
      items: [
        { id: 'wc-1', text: '💨 Évaporation' },
        { id: 'wc-2', text: '☁️ Condensation' },
        { id: 'wc-3', text: '🌧️ Précipitations' },
      ],
      correctFeedback: "Parfait. L'eau passe de liquide à vapeur, puis aux gouttelettes, puis retombe.",
      incorrectFeedback: 'La transformation va du chaud (vapeur) au froid (pluie).',
    },
    {
      id: 'c1-water-disc-8-sprint1',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['sprint'],
      learningObjective: "Récupération rapide : la pluie alimente le vivant.",
      question: 'Vrai ou faux ?',
      card: { title: "Sans pluie, les forêts disparaîtraient.", subtitle: 'Sprint 1' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. L'eau est aussi vitale que la lumière pour les plantes.",
      incorrectFeedback: "Si. Sans eau, les feuilles se ferment, la photosynthèse s'arrête.",
      explanation: "Photosynthèse = lumière + CO₂ + eau. Pas d'eau, pas de sucre.",
    },
    {
      id: 'c1-water-disc-9-sprint2',
      type: 'SWIPE',
      conceptId: 'forest-water-cycle',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: "Démolir l'idée que la pluie vient seulement des océans.",
      question: 'Vrai ou faux ?',
      card: { title: "Toutes les pluies viennent des océans.", subtitle: 'Sprint 2' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bravo. Les forêts génèrent leurs propres pluies. L'Amazonie produit ~50 % de sa pluie.",
      incorrectFeedback: "Non. Les arbres relâchent de la vapeur (transpiration). Les forêts arrosent leurs propres sols.",
      explanation: 'Évapotranspiration : un grand arbre relâche jusqu\'à 400 L de vapeur par jour.',
      misconceptionId: 'rain-comes-from-clouds-only',
    },
    {
      id: 'c1-water-disc-10-meta',
      type: 'QUIZ',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'hard',
      cognitiveTags: ['misconception', 'metacognition'],
      learningObjective: "Choisir le sol qui absorbe le mieux l'eau.",
      question: "Quel sol absorbe le mieux une grosse pluie ?",
      options: [
        { text: 'Un sol forestier riche et vivant', isCorrect: true, feedback: "Exact. Les racines créent des canaux, la matière organique stocke l'eau comme une éponge." },
        { text: 'Une route en goudron', isCorrect: false, feedback: "Le goudron repousse l'eau. C'est ce qui crée les flaques et les inondations.", misconceptionId: 'concrete-helps-drainage' },
        { text: 'Un parking en béton', isCorrect: false, feedback: "Le béton bloque l'infiltration. Idem que le goudron.", misconceptionId: 'concrete-helps-drainage' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-water-disc-11-boss',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "Tracer le parcours d'une goutte d'eau de l'océan jusqu'à la racine.",
      instruction: "Suis le voyage d'une goutte d'eau :",
      axis: 'horizontal',
      axisRationale: 'Chronologie du parcours.',
      slotCount: 4,
      items: [
        { id: 'wb-1', text: '🌊 Évaporation océan' },
        { id: 'wb-2', text: '☁️ Nuage formé' },
        { id: 'wb-3', text: '🌧️ Pluie sur sol' },
        { id: 'wb-4', text: '🌱 Racines arrosées' },
        { id: 'wb-distract', text: '🪨 Roche fondue', isDistractor: true },
      ],
      correctFeedback: "Excellent. La roche fondue n'a rien à voir avec le cycle de l'eau.",
      incorrectFeedback: 'Indice : un seul élément ne fait pas partie du voyage.',
    },
    {
      id: 'c1-water-disc-12-closure',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: "Synthétiser : l'eau est un transporteur, pas une consommable.",
      question: "Pourquoi protéger les sols vivants et les forêts ?",
      options: [
        { text: 'Ils font tourner le cycle de l\'eau localement', isCorrect: true, feedback: "Exact. Sans eux, moins d'infiltration, moins d'évaporation, moins de pluies." },
        { text: 'Parce qu\'ils créent l\'eau à partir de rien', isCorrect: false, feedback: "Aucun être vivant ne crée d'eau. Ils la transportent et la recyclent." },
        { text: 'Parce que c\'est joli', isCorrect: false, feedback: 'Esthétique mais pas le sujet. Le rôle hydrologique est central.' },
      ],
    },
  ],

  pool: [
    {
      id: 'c1-water-pool-sw-fog',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "Comprendre le brouillard comme nuage au sol.",
      question: 'Vrai ou faux ?',
      card: { title: 'Le brouillard est un nuage qui touche le sol.', subtitle: "État de l'eau" },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. Brouillard = condensation au niveau du sol. Même mécanisme.",
      incorrectFeedback: "Si. Brouillard et nuage sont la même chose, à des altitudes différentes.",
      explanation: 'Vapeur qui se condense en gouttelettes : nuage en haut, brouillard en bas.',
    },
    {
      id: 'c1-water-pool-sw-pure-water',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "L'évaporation purifie l'eau.",
      question: 'Vrai ou faux ?',
      card: { title: "Quand l'eau de mer s'évapore, elle laisse le sel derrière elle.", subtitle: 'Chimie' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. C'est pourquoi la pluie est de l'eau douce, même au-dessus des océans.",
      incorrectFeedback: "Si. Seule l'eau s'évapore, pas le sel. La pluie qui tombe est donc douce.",
      explanation: "Distillation naturelle : la nature fabrique de l'eau pure en permanence.",
    },
    {
      id: 'c1-water-pool-sw-tree-transpire',
      type: 'SWIPE',
      conceptId: 'forest-water-cycle',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "Identifier la transpiration des arbres.",
      question: 'Vrai ou faux ?',
      card: { title: "Un grand arbre rejette des centaines de L d'eau par jour", subtitle: 'Forêts' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. Jusqu'à 400 L/jour pour un grand chêne. C'est la transpiration foliaire.",
      incorrectFeedback: "Si. Les arbres pompent l'eau du sol et la relâchent par les feuilles.",
      explanation: 'La forêt est une pompe à eau active, pas un décor.',
    },
    {
      id: 'c1-water-pool-sw-deforest',
      type: 'SWIPE',
      conceptId: 'forest-water-cycle',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: "Comprendre l'impact de la déforestation sur les pluies.",
      question: 'Vrai ou faux ?',
      card: { title: "Couper une forêt n'a aucun effet sur les pluies locales.", subtitle: 'Conséquence' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bravo. Sans transpiration, moins d'humidité atmosphérique, moins de pluies.",
      incorrectFeedback: "Non. La déforestation assèche le climat local sur des dizaines de km.",
      explanation: "Étude Salati 1979 : sans Amazonie, ~50 % des pluies disparaîtraient.",
      misconceptionId: 'rain-comes-from-clouds-only',
    },
    {
      id: 'c1-water-pool-sw-snow',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: [],
      learningObjective: 'La neige fait partie du cycle.',
      question: 'Vrai ou faux ?',
      card: { title: "La neige fait aussi partie du cycle de l'eau.", subtitle: 'États' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. Neige = précipitation solide. Elle fond et alimente rivières et nappes.",
      incorrectFeedback: "Si. La neige est de l'eau gelée qui retournera tôt ou tard liquide.",
      explanation: 'Glaciers et neiges sont des réservoirs lents du cycle.',
    },
    {
      id: 'c1-water-pool-q-glacier',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Comprendre le rôle des glaciers comme réservoirs.',
      question: "Pourquoi la fonte des glaciers inquiète les scientifiques ?",
      options: [
        { text: "Les glaciers sont des réservoirs d'eau douce", isCorrect: true, feedback: "Exact. ~2 milliards de personnes dépendent de l'eau des glaciers." },
        { text: 'Parce que la glace fondue est polluée', isCorrect: false, feedback: 'La fonte elle-même n\'est pas polluante. Le problème est la perte du stock.' },
        { text: 'Parce que les glaciers absorbent du CO₂', isCorrect: false, feedback: "Les glaciers ne stockent pas de CO₂. Le sujet est la ressource en eau." },
      ],
    },
    {
      id: 'c1-water-pool-q-permeable',
      type: 'QUIZ',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'medium',
      cognitiveTags: ['misconception'],
      learningObjective: 'Identifier le sol qui empêche les inondations.',
      question: "Quelle surface limite le mieux les inondations en ville ?",
      options: [
        { text: 'Un parc avec arbres et sol vivant', isCorrect: true, feedback: "Exact. Le sol vivant absorbe l'eau, les racines la stockent." },
        { text: 'Un grand parking bétonné', isCorrect: false, feedback: "Le béton renvoie l'eau en surface. C'est ce qui crée les flots urbains.", misconceptionId: 'concrete-helps-drainage' },
        { text: 'Une route asphaltée', isCorrect: false, feedback: "Asphalte = imperméable. Toute la pluie ruisselle.", misconceptionId: 'concrete-helps-drainage' },
      ],
    },
    {
      id: 'c1-water-pool-q-amazon',
      type: 'QUIZ',
      conceptId: 'forest-water-cycle',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: "Comprendre le rôle climatique des forêts tropicales.",
      question: "Pourquoi l'Amazonie est-elle souvent appelée « pompe à eau du continent » ?",
      options: [
        { text: "Ses arbres relâchent de la vapeur en pluie", isCorrect: true, feedback: "Exact. L'Amazonie influence les pluies jusqu'en Argentine." },
        { text: "Parce qu'elle pompe l'eau de l'océan vers la terre", isCorrect: false, feedback: "Aucun arbre ne pompe l'eau de l'océan. C'est l'évaporation qui le fait." },
        { text: "Parce qu'elle stocke des lacs souterrains", isCorrect: false, feedback: "Pas spécialement. Le mécanisme est aérien : transpiration → vapeur → pluie." },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-water-pool-d-states',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "Ordonner l'eau du chaud vers le froid.",
      instruction: "Ordonne du plus chaud au plus froid :",
      axis: 'horizontal',
      axisRationale: 'Continuum thermique.',
      slotCount: 3,
      items: [
        { id: 'ws-1', text: '💨 Vapeur (chaud)' },
        { id: 'ws-2', text: '💧 Liquide' },
        { id: 'ws-3', text: '❄️ Glace (froid)' },
      ],
      correctFeedback: "Parfait. Plus c'est froid, plus l'eau est dense et solide.",
      incorrectFeedback: "Vapeur = très chaud. Glace = très froid. Liquide entre les deux.",
    },
    {
      id: 'c1-water-pool-d-impact',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Hiérarchiser des surfaces selon leur capacité d\'infiltration.',
      instruction: 'Du sol qui absorbe le moins au plus :',
      axis: 'horizontal',
      axisRationale: "Gradient d'absorption croissante.",
      slotCount: 4,
      items: [
        { id: 'wi-1', text: '🛣️ Goudron' },
        { id: 'wi-2', text: '🪨 Sol nu compact' },
        { id: 'wi-3', text: '🌾 Sol cultivé' },
        { id: 'wi-4', text: '🌳 Sol forestier' },
      ],
      correctFeedback: "Excellent. Plus le sol est vivant, plus il boit la pluie.",
      incorrectFeedback: 'Le sol forestier (vivant + racines) absorbe ~20× plus que le goudron.',
    },
    {
      id: 'c1-water-pool-sw-evapo-cold',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: "L'évaporation peut se produire à basse température.",
      question: 'Vrai ou faux ?',
      card: { title: "L'eau ne s'évapore qu'à 100 °C.", subtitle: 'Idée scolaire' },
      correctDirection: 'left',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Bravo. L'eau s'évapore à toute température, même 0 °C (sublimation).",
      incorrectFeedback: "Faux. 100 °C = ébullition (généralisée). Évaporation = en surface, à toute température.",
      explanation: 'Une flaque sèche au soleil sans bouillir : c\'est de l\'évaporation.',
    },
    {
      id: 'c1-water-pool-q-rain-source',
      type: 'QUIZ',
      conceptId: 'forest-water-cycle',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "Identifier les sources de la vapeur atmosphérique.",
      question: "D'où vient la vapeur d'eau de l'atmosphère ?",
      options: [
        { text: 'Océans, lacs ET transpiration des plantes', isCorrect: true, feedback: "Exact. Les trois sources comptent. Les forêts pèsent ~10 % de la vapeur globale." },
        { text: 'Uniquement des océans', isCorrect: false, feedback: 'Trop restrictif. Les plantes contribuent significativement.' },
        { text: 'Uniquement des nuages existants', isCorrect: false, feedback: 'Les nuages reçoivent la vapeur, ils ne la créent pas.' },
      ],
    },
  ],

  authoredLegendary: [
    {
      id: 'c1-water-leg-1-hook',
      type: 'STORY',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['hook'],
      learningObjective: 'Annoncer le défi : maîtriser le cycle de l\'eau.',
      screens: [
        {
          text: "Tu vas relier l'eau du Soleil à la racine. 14 questions pour ancrer le cycle pour de bon.",
          imagePrompt: 'Cycle complet de l\'eau illustré',
          imageUrl: WATER_IMAGE,
          kind: 'hook',
          boldTokens: ['relier'],
        },
      ],
    },
    {
      id: 'c1-water-leg-2-q',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Identifier le moteur du cycle.',
      question: "Quel est le moteur premier du cycle de l'eau ?",
      options: [
        { text: 'La chaleur du Soleil', isCorrect: true, feedback: "Exact. Sans Soleil, pas d'évaporation, pas de cycle." },
        { text: 'La gravité terrestre', isCorrect: false, feedback: "La gravité fait tomber la pluie, mais elle ne déclenche pas l'évaporation." },
        { text: 'Le vent', isCorrect: false, feedback: 'Le vent transporte la vapeur, il ne la crée pas.' },
      ],
    },
    {
      id: 'c1-water-leg-3-q',
      type: 'QUIZ',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Identifier le meilleur sol pour absorber la pluie.',
      question: 'Pour limiter une inondation, quel aménagement urbain est le plus efficace ?',
      options: [
        { text: 'Désimperméabiliser les surfaces', isCorrect: true, feedback: 'Exact. C\'est la stratégie « ville-éponge » utilisée à Copenhague et Singapour.' },
        { text: 'Bétonner pour évacuer plus vite', isCorrect: false, feedback: 'Le béton aggrave les inondations en empêchant l\'absorption.', misconceptionId: 'concrete-helps-drainage' },
        { text: 'Construire des routes plus larges', isCorrect: false, feedback: 'Plus de surface imperméable = plus de ruissellement.' },
      ],
    },
    {
      id: 'c1-water-leg-4-d',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Reconstituer le cycle complet en 5 étapes.',
      instruction: "Ordonne le cycle complet :",
      axis: 'horizontal',
      axisRationale: 'Chronologie du cycle.',
      slotCount: 5,
      items: [
        { id: 'wlc-1', text: '☀️ Évaporation' },
        { id: 'wlc-2', text: '☁️ Condensation' },
        { id: 'wlc-3', text: '🌧️ Précipitation' },
        { id: 'wlc-4', text: '🌱 Infiltration' },
        { id: 'wlc-5', text: '🏞️ Ruissellement vers océan' },
        { id: 'wlc-distract', text: '🪨 Fossilisation', isDistractor: true },
      ],
      correctFeedback: "Excellent. La fossilisation n'a rien à voir avec le cycle de l'eau.",
      incorrectFeedback: 'Indice : un seul item ne fait pas partie du cycle.',
    },
    {
      id: 'c1-water-leg-5-sw',
      type: 'SWIPE',
      conceptId: 'forest-water-cycle',
      difficulty: 'hard',
      cognitiveTags: ['misconception'],
      learningObjective: 'Confirmer le rôle des forêts dans les pluies.',
      question: 'Vrai ou faux ?',
      card: { title: "Détruire une forêt assèche le climat local sur des décennies.", subtitle: 'Conséquence' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Sans transpiration, moins de vapeur, moins de pluies.',
      incorrectFeedback: 'Si. Le climat local devient plus sec et chaud.',
      explanation: 'Effet documenté en Amazonie, Bornéo, Congo.',
      misconceptionId: 'rain-comes-from-clouds-only',
    },
    {
      id: 'c1-water-leg-6-sw',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: [],
      learningObjective: "L'évaporation purifie l'eau.",
      question: 'Vrai ou faux ?',
      card: { title: "La pluie est plus douce (moins salée) que l'eau de mer.", subtitle: 'Chimie' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. L'évaporation laisse le sel derrière. La pluie est de l'eau pure.",
      incorrectFeedback: "Si. C'est une distillation naturelle.",
      explanation: 'Le cycle est aussi un système de purification de l\'eau.',
    },
    {
      id: 'c1-water-leg-7-q',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: ['metacognition'],
      learningObjective: "Choisir la formulation correcte de l'évaporation.",
      question: 'Comment décrire correctement l\'évaporation ?',
      options: [
        { text: 'Liquide → vapeur grâce à de l\'énergie thermique', isCorrect: true, feedback: 'Exact. C\'est une transformation d\'état endothermique.' },
        { text: 'Liquide qui devient plus léger', isCorrect: false, feedback: 'Pas de notion de poids ici. C\'est un changement de phase.' },
        { text: 'Liquide qui se transforme en gaz par gravité', isCorrect: false, feedback: 'La gravité fait tomber la pluie, pas s\'évaporer.' },
      ],
      confidenceCheck: true,
    },
    {
      id: 'c1-water-leg-8-d',
      type: 'DRAG_DROP',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: ['interleaved'],
      learningObjective: "Lier le Soleil au cycle de l'eau (entrelacement).",
      instruction: "Ordonne la chaîne causale :",
      axis: 'horizontal',
      axisRationale: 'Chronologie causale.',
      slotCount: 4,
      items: [
        { id: 'wli-1', text: '☀️ Soleil chauffe' },
        { id: 'wli-2', text: '💨 Eau s\'évapore' },
        { id: 'wli-3', text: '☁️ Nuages se forment' },
        { id: 'wli-4', text: '🌧️ Pluie sur forêt' },
      ],
      correctFeedback: "Parfait. Le Soleil démarre tout, même la pluie.",
      incorrectFeedback: "Tout part de la chaleur solaire. Sans elle, rien ne bouge.",
      interleavesConceptIds: ['sun-energy-source'],
    },
    {
      id: 'c1-water-leg-9-sw',
      type: 'SWIPE',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'medium',
      cognitiveTags: ['sprint'],
      learningObjective: "Sprint final : direction du cycle.",
      question: 'Vrai ou faux ?',
      card: { title: "L'eau circule de la mer au ciel, à la terre, puis retour", subtitle: 'Sprint final' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: "Vrai. C'est exactement le cycle, en boucle infinie.",
      incorrectFeedback: "Si. Ce cycle continu existe depuis 4 milliards d'années.",
      explanation: 'L\'eau ne disparaît jamais : elle change juste de forme et de lieu.',
    },
    {
      id: 'c1-water-leg-10-sw',
      type: 'SWIPE',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'medium',
      cognitiveTags: ['sprint', 'misconception'],
      learningObjective: 'Confirmer que le sol vivant est meilleur que le béton.',
      question: 'Vrai ou faux ?',
      card: { title: "Pour mieux gérer la pluie, mieux vaut un sol vivant qu'un sol bétonné.", subtitle: 'Sprint final' },
      correctDirection: 'right',
      leftLabel: 'FAUX',
      rightLabel: 'VRAI',
      correctFeedback: 'Vrai. Sol vivant = ~20× plus d\'absorption que le béton.',
      incorrectFeedback: 'Si. Le sol vivant absorbe et retient. Le béton renvoie tout.',
      explanation: 'Stratégie « ville-éponge » : remplacer du bitume par des sols vivants.',
      misconceptionId: 'concrete-helps-drainage',
    },
    {
      id: 'c1-water-leg-11-q',
      type: 'QUIZ',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'hard',
      cognitiveTags: [],
      learningObjective: 'Synthétiser : énergie + eau + vivant.',
      question: "Sans Soleil ET sans forêts, qu'arriverait-il au cycle de l'eau ?",
      options: [
        { text: 'Il s\'effondrerait : moins d\'évaporation et de pluies', isCorrect: true, feedback: 'Exact. Le cycle dépend des deux moteurs : énergie solaire et vivant.' },
        { text: 'Rien ne changerait', isCorrect: false, feedback: 'Le cycle dépend de l\'énergie pour démarrer.' },
        { text: 'Les océans déborderaient', isCorrect: false, feedback: 'Sans évaporation, les océans monteraient à peine. Le problème serait l\'absence de pluies sur terre.' },
      ],
    },
    {
      id: 'c1-water-leg-12-reveal',
      type: 'STORY',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['reveal'],
      learningObjective: "Donner la perspective : l'eau lie tous les écosystèmes.",
      screens: [
        {
          text: "L'eau est le lien invisible : elle traverse plantes, animaux, sols, océans, atmosphère. Sans elle, plus rien ne tient.",
          imagePrompt: "Goutte d'eau qui se réfléchit dans une feuille avec écosystème en arrière-plan",
          imageUrl: WATER_IMAGE,
          kind: 'reveal',
          boldTokens: ['lien'],
        },
      ],
    },
    {
      id: 'c1-water-leg-13-q',
      type: 'QUIZ',
      conceptId: 'water-cycle-infiltration',
      difficulty: 'medium',
      cognitiveTags: ['closure'],
      learningObjective: 'Choisir une action quotidienne cohérente.',
      question: "Quel geste protège le mieux le cycle de l'eau ?",
      options: [
        { text: 'Préserver les forêts ET les sols vivants', isCorrect: true, feedback: 'Exact. Les deux régulent les pluies et l\'absorption.' },
        { text: 'Bétonner pour mieux gérer les inondations', isCorrect: false, feedback: 'Inverse : le béton aggrave les inondations.', misconceptionId: 'concrete-helps-drainage' },
        { text: 'Pomper plus d\'eau dans les nappes', isCorrect: false, feedback: 'Pomper plus = épuiser la ressource. Pas une solution durable.' },
      ],
    },
    {
      id: 'c1-water-leg-14-closure',
      type: 'STORY',
      conceptId: 'water-cycle-evaporation',
      difficulty: 'easy',
      cognitiveTags: ['closure'],
      learningObjective: 'Annoncer la transition vers les Sols.',
      screens: [
        {
          text: "Tu sais d'où vient l'eau. Mais où va-t-elle quand elle s'infiltre ? Bienvenue dans la fabrique souterraine : les sols vivants.",
          imagePrompt: 'Coupe de sol avec racines et eau qui descend',
          imageUrl: FIELD_IMAGE,
          kind: 'closure',
          boldTokens: ['souterraine'],
        },
      ],
    },
  ],

  lessons: [
    {
      id: 'chapter-1-water-lesson-1',
      slug: 'decouverte',
      title: 'Découverte',
      kind: 'discovery',
      order: 1,
      estimatedMinutes: '3 min',
      learningGoal: "Découvrir le cycle de l'eau et son lien avec le vivant.",
      generation: 'authored-discovery',
      rules: { exerciseCount: 12 },
    },
    {
      id: 'chapter-1-water-lesson-2',
      slug: 'revision-active',
      title: 'Révision active',
      kind: 'practice',
      order: 2,
      estimatedMinutes: '3 min',
      learningGoal: 'Réviser le cycle de l\'eau sans relire la théorie.',
      generation: 'pool-practice',
      rules: { exerciseCount: 10, misconceptionRatio: 0.4, interleaveFromPreviousUnits: 1 },
    },
    {
      id: 'chapter-1-water-lesson-3',
      slug: 'maitrise',
      title: 'Maîtrise',
      kind: 'mastery',
      order: 3,
      estimatedMinutes: '3-4 min',
      learningGoal: "Manipuler le cycle de l'eau dans des cas pièges.",
      generation: 'pool-mastery',
      rules: { exerciseCount: 12, misconceptionRatio: 0.5, metacognitionRatio: 0.3, hardRatio: 0.6, interleaveFromPreviousUnits: 2 },
    },
    {
      id: 'chapter-1-water-lesson-4',
      slug: 'couronne',
      title: 'Couronne',
      kind: 'legendary',
      order: 4,
      estimatedMinutes: '4-5 min',
      learningGoal: "Prouver la maîtrise du cycle de l'eau.",
      generation: 'authored-legendary',
      rules: { exerciseCount: 14 },
      reward: { type: 'seeds', amount: 10, label: '10 Graines' },
    },
  ],
}
